### ISSUE TITLE
usage of deprecated module static-favicon

### ISSUE THREAD

**Issue by vsmurali** [strongloop/loopback#1054]
Current npm uses deprecated static-favicon module.  Warning can be observed during npm install
"WARN deprecated static-favicon@1.0.2"

serve-favicon module to be used instead of static-favicon across the application and its dependencies

Direct References in
1. test/fixtures/simple-integration-app/app.js
2. server/middleware/favicon.js

Dependency references in
1. karma/node_modules/connect/examples/
    1.1  favicon.js
    1.2  profiler.js
    1.3  Logger.js
    1.4  Session.js
    1.5  rollingSession.js
    1.6  Logger.fast.js

**Comment by PradnyaBaviskar** [comment]
Tried reproducing this by taking following steps...
<ol><li>
Scaffolded a demo app using "slc loopback".<ol><li>
 "slc loopback" automated "npm install" for me.</li><li> 
But,  the install logs did not show up any warning.</li></ol><li>
Later I started the app using "slc run".  
That too did NOT report any warning. </li>
</li></ol>

Seems this issue is already fixed.

cc / @bajtos
