### ISSUE TITLE
Docs chapter "Add a static web page" has several typos & wrong parts

### ISSUE THREAD

**Issue by aantipov** [strongloop/loopback#1067]
Hey there!
I think you should re-read the chapter [Add a static web page](http://docs.strongloop.com/display/public/LB/Add+a+static+web+page) - it contains several typos (`pplication`, missed comma in server/middleware.json code sample) & wrong suggestion about how to remove using of `loopback.status()`.
By default the scaffolded application has not a boot script named root.js, so the provided there solution doesn't work.
To remove using of `loopback.status()` we should edit `routes` property in `server/middleware.json`

**Comment by crandmck** [comment]
Thanks for catching the typo. I corrected it.

> wrong suggestion about how to remove using of loopback.status().
By default the scaffolded application has not a boot script named root.js, so the provided there solution doesn't work.
To remove using of loopback.status() we should edit routes property in server/middleware.json

The scaffolded LB app changed recently.  There was a brief period when it did not include `root.js`, but it does again now due to https://github.com/strongloop/generator-loopback/issues/80.  Thus, the doc as written is correct.

You may need to update your installation.  The latest version is v2.10.10 (`slc --version`).
