### ISSUE TITLE
Discovery: MySQL dataLength is 3x larger than in DB

### ISSUE THREAD

**Issue by hotaru355** [strongloop/loopback#1145]
Running `dataSource.discoverSchema()` against a MySQL database generates model definitions with incorrect `dataLength` properties for all database columns of type `VARCHAR`. Interestingly, the discovered `dataLength` is exactly 3 times the value of what is defined in the database.
Related post on StackOverflow:
http://stackoverflow.com/questions/25988681/loopback-2-0-mysql-db-field-length-conversion-not-working-properly

**Comment by raymondfeng** [comment]
Does your MySQL DB use multibyte character sets? The dataLength is in bytes.

**Comment by hotaru355** [comment]
I see, thanks for the clarification. The database uses UTF8 as the default character set, so the number of bytes would be variable (?). Is there any way for loopback to get the "length in characters" instead of getting the "length in bytes" ?

**Comment by partap** [comment]
I figure MySQL is allocating 3x the amount of characters requested because it doesn't know if the field is likely to be mostly ASCII or mostly Asian-language characters.  They would have to store the declared character length somewhere though...otherwise `describe` and `show create table` wouldn't work right...

in [`queryColumns`](https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/discovery.js#L143-L165), loopback-connector-mysql is querying `character_octet_length` as `dataLength`.  There is another column in that table called `character_max_length` which is what you're looking for (the declared varchar length).

You could just insert something like:
```
' character_max_length as "length", ' +
```
at around lines 148 and 160 for a quick easy patch.
(at first I was going to use `characterLength` and then `stringLength`...but simply `length` makes more sense in a javascript context)

**Comment by raymondfeng** [comment]
We can switch to `character_max_length`. PR?

**Comment by partap** [comment]
I figured you'd probably want to add `character_max_length` rather than replace `character_octet_length` ... there could be people relying on the current behavior.

Also, byte length makes more sense in some cases...blob, for instance.

**Comment by partap** [comment]
Oops, it's actually called `character_maximum_length`

**Comment by partap** [comment]
[PR Here](https://github.com/strongloop/loopback-connector-mysql/pull/79)

**Comment by hotaru355** [comment]
Thanks for the quick fix. A last mandatory and mundane question: when will the release with this change roll out?

**Comment by raymondfeng** [comment]
Once the PR is landed, we can release it right away.

**Comment by partap** [comment]
@raymondfeng 
I couldn't run some of the tests...the including and excluding views tests seem to want some existing db schema  that I don't have...
I didn't worry about it too much because the part I modified seems to work.

**Comment by loay** [comment]
PR https://github.com/strongloop/loopback-connector-mysql/pull/79 is already merged. 

Closing the issue. If issue is still persisting, please feel free to leave a comment and I will re-open the issue. Thanks.
