### ISSUE TITLE
ACL Allows Relation access even though DENY *

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#115]
@raymondfeng 

See https://github.com/strongloop/loopback-example-access-control/issues/2#issuecomment-31125104

For a reproducible case.

Connect to strongloop/loopback#1362

**Comment by hotaru355** [comment]
I have just bumped into this issue and it is a **major** roadblock for us to get our server into production. I tried to track down the problem and would greatly appreciate your help. All I can say is that the `before.**` event is never fired for second level endpoints (/model/:id/relatedModel). Since the
[application.js]
(https://github.com/strongloop/loopback/blob/master/lib/application.js#L298) calls `Model.checkAccess` on this event, the entire ACL evaluation is disabled for those remotes. Clearly, those second level remotes must be setup differently than the first level remotes. Are those second level remotes maybe created after the eventhandler is registered?
Any hint would be greatly appreciated.

**Comment by ritch** [comment]
> I have just bumped into this issue and it is a major roadblock for us to get our server into production. I tried to track down the problem and would greatly appreciate your help. All I can say is that the before.**  event is never fired for second level endpoints (/model/:id/relatedModel). 

I don't think this is correct. Or to be specific I don't think you are attaching your `before` hook to the correct model. Consider this endpoint:

```
/customers/1/reviews
```

This calls the `Customers.prototype.__get__reviews` method. It triggers the `Customers` before hook (not the `Review`s). I have just confirmed this with `loopback@2.17.2`.

A potential issue (depending on how you expect ACL to work) is that the set of `Review` access controls **are not applied** when accessing `Review` through a relation. Only the `Customer` ACL is enforced.

**Comment by ritch** [comment]
I'm closing this as its no longer an issue.

Improvements will come to relation access control. Keep an eye on https://github.com/strongloop/loopback/issues/1362
