### ISSUE TITLE
New type: ENUM

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1321]
Implement a new property type - enum (enumeration).

Example model definition:

``` json
{
  "name": "Person",
  "properties": {
    "sex": {
      "type": "enum",
      "values": ["male", "female", "other"]
    }
  }
}
```

Example remoting argument definition:

``` js
{
  accepts: { 
    arg: 'sex', type: 'enum', values: ['male', 'female', 'other'],
    http: { source: 'query' }
  }
}
```

Implementation details:
- support both "string" and "number" as a backing datatype
- [ ] strong-remoting should validate and coerce enumeration types
- [ ] loopback-datasource-juggler should validate property values of enum type
- connectors should map enum type to appropriate database counterpart
  - [ ] SQL connectors - see https://github.com/strongloop-internal/scrum-loopback/issues/603
  - [ ] MongoDB - see https://github.com/strongloop-internal/scrum-loopback/issues/604
- [ ] loopback-swagger should emit correct json-schema descriptor for enum properties
- [ ] autodiscovery

**Comment by raymondfeng** [comment]
Instead of introducing a new type, I would prefer to add a `enum` constraint to model properties, such as:

```
color: {
  type: 'string',
  enum: ['red', 'green', 'blue', ...]
}
```

It's similar as https://github.com/hapijs/joi#anyvalidvalue---aliases-only-equal

**Comment by bajtos** [comment]
> Instead of introducing a new type, I would prefer to add a enum constraint to model properties

Sounds good :+1:

**Comment by violet-day** [comment]
+1

**Comment by bajtos** [comment]
FWIW, we already have ENUM validation implemented via `MyModel.validatesInclusionOf('gender', {in: ['male', 'female', 'other']});`

I guess we only need to map `enum` property flag to `validatesInclusionOf` and implement support for `enum` in strong-remoting.

**Comment by ainesophaur** [comment]
+1

Would these additions then translate to loopback explorer? It'd be nice to show the allowed values.

**Comment by billinghamj** [comment]
+1

**Comment by gausie** [comment]
:+1:

**Comment by Bramanga** [comment]
:+1:

**Comment by ezraroi** [comment]
+1

**Comment by MyNameIsURL** [comment]
+1

**Comment by terehov** [comment]
+1

**Comment by parvbhullar** [comment]
+1

**Comment by mayke5421** [comment]
+1

**Comment by geoand** [comment]
+1

**Comment by riteshjagga** [comment]
+1

**Comment by ataraxus** [comment]
+1

**Comment by g3k0** [comment]
+1

**Comment by wesleycoder** [comment]
+1

**Comment by MarkAndrewJohnson** [comment]
The benefit of making this a type instead of a loopback option is that if you need to provision for a secondary access method which isn't via loopback then the enum won't validate the input.  Obviously not every use case by far but worth keeping in mind.

**Comment by AndreasPizsa** [comment]
+1

Enums are a common pattern; adding enum support - whether as a type or a constraint - would greatly simplify repeated validity checks on parameters.

**Comment by adrien-candiotti** [comment]
+1

**Comment by yadavji83** [comment]
+1

**Comment by lucasftp** [comment]
+1

**Comment by FluxAugur** [comment]
+1

**Comment by raghav135** [comment]
Same example can be thought of as a enum which is defined in type registry as a "custom type".

And in model, have property as type : "sex"

So that adding a new entry in enums can be done in central type registry?

**Comment by martinjuhasz** [comment]
:+1:

**Comment by timneedham** [comment]
:+1:

**Comment by evinw** [comment]
+1

**Comment by daxsorbito** [comment]
+1

**Comment by f0ysal** [comment]
+1

**Comment by seanmangar** [comment]
+1

**Comment by gzurbach** [comment]
+1

**Comment by shelbys** [comment]
@bajtos - FYI, we already have `enum` validation in our Fork, see: https://github.com/strongloop/strong-remoting/compare/master...shelbys:master

**Comment by ShaharHD** [comment]
+1

**Comment by ShaharHD** [comment]
+1
@shelbys do you plan to have pull request with that specific change (enum)?

**Comment by sebastianhaas** [comment]
+1

**Comment by hulutter** [comment]
+1

**Comment by aws-na-ss-usplu** [comment]
What the status?
+1

**Comment by Undrium** [comment]
+1

Sweet type or constraint, would organize alot for our project

**Comment by PowerP** [comment]
+1

**Comment by lsroman** [comment]
+1

**Comment by aws-na-ss-usplu** [comment]
Novice: Our very small two cents **_;-)_**

We currently develop solutions in two worlds… LoopBack/Node.js & WebApi/Asp.net

 We would love to have a solution that complements each others interpretation of the concepts around

- Generic Extensions for Enum
- Implement of Enum
- Solution path to transition from Swagger Extension to first class member of Swagger 2.x schema

We currently use swagger to generate both client/server code for LoopBack & .NET, and client code in Java and PHP.  When it comes to **Enum** and **Additional Properties** we have to deal with exceptions because like HTML specs each community is interpreting the specifications a little differently rather than each community discussing the discrepancy to improve the understanding and interpreting of the Swagger Specs.

Here is how AutoRest community is currently dealing with Enums with AutoRest

- [Azure's AutoRest Generic Extensions](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md) 
- [AutoRest x-ms-enum](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-enum)
- [Enums with x-ms-enum definition](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Enum-x-ms-enum)
- [AutoRest Enum Github Issue#393](https://github.com/Azure/autorest/pull/393/files)

We still need to investigate where the StrongLoops/ IBM thoughts on implementing Enum, and we plan to review shortly.

We just propose that all participants in providing a Swagger Code Generators to deal with Enum to converge on a solution rather than have a lot of silo implementations of swagger generic extensions for Enum.

We have investigated the following code generators to date.  Non have a consist implementation to deal with **Additional Properties** or **Enum**

- [Azure AutoRest](https://github.com/Azure/autorest)
- [NSwag ](http://nswag.org)
- [Swagger-API Online Editor](http://editor.swagger.io)
- [Swagger-API CodeGen](https://github.com/swagger-api/swagger-codegen )
- [Loopback Swagger Generator](https://docs.strongloop.com/display/public/LB/Swagger+generator ) 

Appreciate feedback, concerns and issues with our thoughts…

**Comment by juanpujol** [comment]
👍

**Comment by ejaigom** [comment]
+1

**Comment by edoswaldgo** [comment]
👍

**Comment by petrlyapin** [comment]
+1

**Comment by rflipo-dev** [comment]
👍

**Comment by mamartins** [comment]
+1

**Comment by jamesobd** [comment]
+3

**Comment by younes200** [comment]
Hi,
Is this feature still planned ? which release, version it may be available ?
Thank you.
Cheers
/Y

**Comment by siyb** [comment]
+1

**Comment by BoLaMN** [comment]
I do this in my json files with a mixin I wrote for validations [link](https://github.com/BoLaMN/loopback-validate-mixin)

```
validations:
    colour:
         inclusion: 
             in: [ 'red', 'blue' ]
```

**Comment by neoPix** [comment]
+1

**Comment by raymatos** [comment]
Is this resolved?  Or is there a best practice for enums?

**Comment by chadwithuhc** [comment]
👍

**Comment by joseluisjb1990** [comment]
+1

**Comment by phil-hawkins** [comment]
+1

**Comment by hoangtrongphuc** [comment]
I have a solution and I'm using it in my project: 
In model Game : 
```
color: {
  type: 'string'
}
```
In game.js file: 
```
module.exports = function(Game) {
  Game.validatesInclusionOf('color', {in: ["hello", "bye"]});
};
```

**Comment by hckhanh** [comment]
+100000000

**Comment by scippio** [comment]
+1

**Comment by kjdelisle** [comment]
Feature development on loopback@3.x is winding down as a result of our push towards loopback-next. Given the nature of the new framework and its use of TypeScript, support for things like enums will be much easier to implement going forward rather than on this current version.

**Comment by terehov** [comment]
Does it mean that loopback-next is around the corner and there is a clear migration path?

**Comment by kjdelisle** [comment]
Loopback-next is going into beta soon and will consist of the most core components of the framework. The intention of the new platform is to focus more of our energy on providing a solid foundation, rather than attempting to build every connector and component for everyone.

**Migration**
There is a repository implementation called the [legacy-juggler-bridge](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/legacy-juggler-bridge.ts) that will allow continued use of your JSON model definitions and the existing loopback-datasource-juggler.

However, there won't necessarily be a direct upgrade path for your application that transforms your existing logic into a loopback@4.x compatible application. I'd strongly encourage reading the wiki (https://github.com/strongloop/loopback-next/wiki); it's still a work-in-progress but combining it with the [loopback-next-example](https://github.com/strongloop/loopback-next-example) repo should give you insight into loopback-next's many potential workflows and designs.

**Comment by kjdelisle** [comment]
@terehov Sorry, forgot to add your name to the comment. :P

**Comment by SrChip15** [comment]
@kjdelisle Where should I look for enum related model data validations in Loopback 4?

**Comment by bajtos** [comment]
Let's move the discussion to https://github.com/strongloop/loopback-next/issues/3033.

**Comment by bajtos** [comment]
For anybody who lands in this issue: if ENUMs are important to you, then please up-vote  strongloop/loopback-next#3033 by adding a 👍 reaction at the top. Please DO NOT post +1 comments, those are not helpful.
