### ISSUE TITLE
Why PersistedModel.destroyAll is not shared in rest api

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback#1337]
Any reason for [this](https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L614)? I just wanted to use it from the rest api, but now I have to use find instead and delete one by one or define my own method.

**Comment by bajtos** [comment]
IIRC, the method is disabled because it's potentially dangerous. If you omit the filter (or specify it incorrectly), then you will wipe out your entire table.

You should be able to enable the `destroyAll` method using JS API:

```js
MyModel.sharedClass.find('destroyAll', true).shared = true;
```

Please post any further questions to our [mailing list](https://groups.google.com/forum/#!forum/loopbackjs).

**Comment by mackwan84** [comment]
When I try to set this code,
```javascript
MyModel.sharedClass.find('destroyAll', true).shared = true;
```

it always throws this error:
TypeError: Cannot set property 'shared' of null

**Comment by sleroy** [comment]
Same for me as @mackwan84

**Comment by ambrt** [comment]
@sleroy it seems that answer is here https://github.com/strongloop/loopback/issues/1499#issuecomment-118250091
