### ISSUE TITLE
Update example apps to use middleware phases, etc.

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1352]
General issue for updating LB examples:
- To use middleware phases
- To use operation hooks LB per https://github.com/strongloop/loopback/issues/1092

These examples need a `middleware.json`:
- https://github.com/strongloop/loopback-example-passport/
- https://github.com/strongloop/loopback-example-ssl
- https://github.com/strongloop/loopback-faq-rest-connector

See http://docs.strongloop.com/display/LB/Defining+middleware for general info.

Also review examples listed in https://github.com/strongloop/loopback-example to see if any others require updating.

**Comment by hacksparrow** [comment]
Why is the use of `middleware.json` the **recommended way** of adding middleware, as mentioned at http://docs.strongloop.com/display/public/LB/Defining+middleware?

Since `middleware.json` is a json file, it takes away the flexibility of loading helper modules and using JavaScript code. Example: it is impossible to do, something like  `app.use(loopback.static(path.resolve(__dirname, '../client/public')));`.

I am more in favor of using a middleware-loading module which would use the `app.middleware()`method to load the middleware at the right phases. The code is much neater compared to the use of `middleware.json`, especially when the number of middleware is high with lots of configuration options.

**Relevant to this issue**

Is there a way to port `app.use(loopback.static(path.resolve(__dirname, '../client/public')));` to `middleware.json`? I can't think of a way, apart from using an absolute path or a relative path from the `loopback-boot` module, which are inelegant.

**Comment by hacksparrow** [comment]
Also, this one:
```
app.use(loopback.token({
  model: app.models.accessToken
}));
```
How would this be ported to `middleware.json`?

Using a custom loader using `app.middleware()` solves the problem.

**Comment by hacksparrow** [comment]
[Opened a PR](https://github.com/strongloop/loopback-example-ssl/pull/5) for https://github.com/strongloop/loopback-example-ssl. `middleware.json` works well for simple cases, such as this.

**Comment by hacksparrow** [comment]
[Opened a PR](https://github.com/strongloop/loopback-faq-rest-connector/pulls) for https://github.com/strongloop/loopback-faq-rest-connector.

**Comment by hacksparrow** [comment]
@crandmck how about using a custom middleware loader for **loopback-example-passport**? It would make a good introductory example for `app.middleware()`.

**Comment by crandmck** [comment]
@bajtos Can you address the above questions?

**Comment by bajtos** [comment]
> Why is the use of middleware.json the recommended way of adding middleware, as mentioned at http://docs.strongloop.com/display/public/LB/Defining+middleware?

Configuration in JSON files is editable programatically, for example using `slc loopback` and StrongLoop Arc. Configuration in arbitrary javascript code is very difficult to modify by a tool.

> Since middleware.json is a json file, it takes away the flexibility of loading helper modules and using JavaScript code. Example: it is impossible to do, something like app.use(loopback.static(path.resolve(__dirname, '../client/public')));.

1) You can always use `middleware.local.js` and modify (customize) middleware parameters using javascript.

2) The particular example of building paths relative to `__dirname` is solved by a special syntax, where you prefix the string with `$!`, e.g. `$!../client/public`).

> How would this be ported to middleware.json?

> ```js
app.use(loopback.token({
  model: app.models.accessToken
}));
```

The token middleware should support string-values passed as model value. Please open a GH issue (or send a pull request) if it does not.

```js
"loopback#token": {
  "params": {
    "model": "accessToken"
  }
}
```

**Comment by hacksparrow** [comment]
Thanks @bajtos. The configurability is a valid point. I will evaluate 2 and 3 and report the details. Having said that, I think `app.middleware()` also deserves some love :)

**Comment by crandmck** [comment]
@raymondfeng What do you think of this?
> how about using a custom middleware loader for loopback-example-passport? It would make a good introductory example for app.middleware().

**Comment by crandmck** [comment]
> Having said that, I think app.middleware() also deserves some love :)
@hacksparrow Do you think we need more than what's in:
http://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-UsingtheLoopBackAPI ?
If so, feel free to add it.

**Comment by hacksparrow** [comment]
The details about `middleware.local.js` is supposed to be found at http://docs.strongloop.com/display/public/LB/Environment-specific+configuration, but there is no mention of it on the page. Where are the details of modifying (customizing) middleware parameters using JavaScript?

@crandmck the fact about `$!` is not in the docs, except for its use in the example. I wonder if there are other special characters like `$!`. 

@bajtos how do you do `app.get('cookieSecret')` in `middleware.json`?

**Comment by crandmck** [comment]
@hacksparrow Please add to the docs whatever is missing (when you are able).  Thanks!

**Comment by bajtos** [comment]
> The details about middleware.local.js is supposed to be found at http://docs.strongloop.com/display/public/LB/Environment-specific+configuration, but there is no mention of it on the page. Where are the details of modifying (customizing) middleware parameters using JavaScript?

It uses the same principle as other files. Your JS file exports a json-like structure mirroring the original JSON file, providing only the values to override.

> I wonder if there are other special characters like `$!`.

Not ATM.

> how do you do `app.get('cookieSecret')` in middleware.json?

That's not supported now. https://github.com/strongloop/loopback-boot/issues/75 proposes `$!{cookieSecret}` syntax, but that haven't been implemented yet. Would you mind contributing the implementation yourself?

**Comment by hacksparrow** [comment]
Thanks, I will look into contributing the implementation.

**Comment by hacksparrow** [comment]
The following example and faq repos are listed on https://github.com/strongloop/loopback-example.

https://github.com/strongloop/loopback-faq-operation-hooks
https://github.com/strongloop/loopback-example-app
https://github.com/strongloop/loopback-example-recipes
https://github.com/strongloop/loopback-example-recipes
https://github.com/strongloop/loopback-faq-rest-connector
https://github.com/strongloop/loopback-component-push
https://github.com/strongloop/loopback-component-storage
https://github.com/strongloop/loopback-example-offline-sync
https://github.com/strongloop/loopback-example-passport
https://github.com/strongloop/loopback-faq-model-relations

I have opened PRs addressing the middleware phase and operation hook updates, wherever applicable.

**loopback-component-push** and **loopback-component-storage** have older and newer (2.0) server versions. Since the newer versions use the updated API, I am assuming the older version need not be updated.

This issue could be closed after reviewing the PRs.

**Comment by crandmck** [comment]
In list above, I've checked off the merged PRs.  Otherwise:
- There doesn't seem to be a PR for https://github.com/strongloop/loopback-component-push
- Work seems to be ongoing for https://github.com/strongloop/loopback-example-offline-sync
- Ran into a problem with https://github.com/strongloop/loopback-example-passport but not sure it's related to the PR.

Waiting for tests for the others above that are not checked.

**Comment by hacksparrow** [comment]
https://github.com/strongloop/loopback-component-push has a directory named `server-2.0`, with a `middleware.json`, so no update required, if I am not wrong.

**Comment by hacksparrow** [comment]
The problem in https://github.com/strongloop/loopback-example-passport was in the original state as well. If the requirement is known, I can fix it.

**Comment by bajtos** [comment]
> https://github.com/strongloop/loopback-component-push has a directory named server-2.0, with a middleware.json, so no update required, if I am not wrong.

I believe you are correct @hacksparrow and no update is required there.

**Comment by crandmck** [comment]
I think this can now be closed.  All the changes have been merged, except https://github.com/strongloop/loopback-example-offline-sync/pull/70 which is waiting on other work.
