### ISSUE TITLE
RFC: Tests as documentation.

### ISSUE THREAD

**Issue by OwenBrotherwood** [strongloop/loopback#1381]
## Tests as documentation
The concept of using a test to document the api: with special focus on the test can be referred to with issues.

Tests are 'good': is it possible also to use a test to document an api: with test normal and unnormal usage?

[mocha (the test framework used by loopback)](http://mochajs.org/) could possible be used to give a nice output of an api call.

Apart from normal and unnormal usage, the test can (should) have a section showing breaking changes as  future loopback versions are being developed.

### Use case
A new api, or change to an api.

#### Work Flow
- Create a small test file (the interface) that requires a lib test file (the glue) to test the code change (the result) and show how the api should be used.normal and unnormal
- The test file should be small, and can include breaking tests to show where the breakage is @ritch (1380)
- The test file should be readable, with out to much code so can almost be used as doc @crandmck 
- The lib test file should be readable and small and preferably, usable by several test files.
- The code change should be fantastic and contain the usual call documentation

### Look and feel: the test output
The look and feel can be improved with describes and probably longer text's within some limit of length of line length (80?)
```
$ mocha -g 'api:loopback:middleware:token'
  api:loopback:middleware:token(options)
    loopback.token({})
      V header (41ms)
      Breaking change
        V None
    options
      searchDefaultTokenKeys:[true|false]
        Normal usage: false for use case, restrict location of token
          Example, token in header
            V options.headers is empty, true
            V options.headers has header, false
        Unormal usage: testing or unknown usage
          Example, token in header
            V options.headers is empty, false
        Breaking change
          V None
  6 passing (97ms)
```
### Some 'code'
- [test/api-loopback-middleware-token.js](https://github.com/strongloop/loopback/blob/8cf7e877ced02c8fb3efccafa28c5322e6d5fb63/test/api-loopback-middleware-token.js)
- [test/lib/lib-loopback-middleware-token.js](https://github.com/strongloop/loopback/blob/0303b7d2626dc841576aec8420e5963273e4748a/test/lib/lib-loopback-middleware-token.js)

@bajtos : ty for test help 
@raymondfeng : fast moving branches, while retaining tests and doc (1380)

Shoot me down if this already 'done' :)
I continue to google for what is normal in this field.

Edit: Googling
- https://strongloop.com/strongblog/nodejs-testing-documenting-apis-mocha-acquit/
  - 'Generating Documentation from Tests'

**Comment by bajtos** [comment]
I am personally doing Test-Driven and Test-First development, where I focus on writing tests to cover the code changes I am making. While I try to keep the test output as a readable specification (run `mocha -R spec` to see yourself), it's a second-level concern to me. (Note that other team members may see this differently.)

I think it's a good idea to revisit test naming strategy to make the output of `mocha -R spec` more readable, so that it can be used a sort of a living documentation.

I personally don't think it's a good idea to significantly rewrite the current test suite and/or impose strict structure like you proposed in [test/api-loopback-middleware-token.js](https://github.com/strongloop/loopback/blob/8cf7e877ced02c8fb3efccafa28c5322e6d5fb63/test/api-loopback-middleware-token.js). It requires non-trivial effort and the gains seems low to me.

Here is a small part of the output of `mocha -R spec` for illustration of the current state of things:

```
  loopback.token(options)
    ✓ should populate req.token from the query string
    ✓ should populate req.token from an authorization header
    ✓ should populate req.token from an X-Access-Token header
    ✓ should populate req.token from an authorization header with bearer token
    ✓ should populate req.token from a secure cookie
    ✓ should populate req.token from a header or a secure cookie
    ✓ should rewrite url for the current user literal at the end without query
    ✓ should rewrite url for the current user literal at the end with query
    ✓ should rewrite url for the current user literal in the middle
    ✓ should skip when req.token is already present
    populating req.toen from HTTP Basic Auth formatted authorization header
      ✓ parses "standalone-token"
      ✓ parses "token-and-empty-password:"
      ✓ parses "ignored-user:token-is-password"
      ✓ parses "token-is-username:ignored-password"
```

Comparing the current test output with what you propose, it seems to me that you are missing more API-oriented unit tests, because the current test suite is focused more on testing the implementation details. If that's correct, then perhaps we can simply add some new tests that would be more API-oriented. Would that address your needs?
      
Let's add few more people to the discussion: @ritch @fabien @clarkorz @STRML

**Comment by OwenBrotherwood** [comment]
@bajtos Thank you for spending time on relying.
Yes:  the API oriented tests could be a help allowing community contributions with a readable test structure in order to show the delelopers what the community is wanting or finding in the code.
It is important to reduce the time on the core developers a easy test system for the community is so important

**Comment by ritch** [comment]
I have a few opinions on this.

 - Naming tests in a structured way is only useful for making it easier to write tests (you shouldnt have to think about the name of a test for more than n seconds). Naming conventions that need documentation or explanation are too complicated.
 - Tests should not replace documentation, but they should represent the "spec". You should be able to use tests to write the documentation.
 - If its easy to test, we'll have better tests since everyone will have more time and energy to focus on writing good tests. Lets not make it harder to write tests for some theoretical benefit.

Other than that I defer any opinions on testing to @bajtos, @superkhau and @rmg (and some other people: shoutout to @tj). I'm still trying to learn from them the right and wrong ways of testing.

**Comment by rmg** [comment]
>  If that's correct, then perhaps we can simply add some new tests that would be more API-oriented. Would that address your needs?

:+1: :heavy_multiplication_x: :100: 

Modules with public APIs should definitely have full coverage of the exposed API that are not tied to the implementation. It could be argued that those are the _only_ tests of any value.

**Comment by OwenBrotherwood** [comment]
An opionated POV:
Tests can be catogorised:
- environment
  - tests using the environment
    - the test of the api was in an app environment, TestEnvironment object
- api
  - tests looking into the api of the code
- implementation
  - tests of the implementation: sometimes called unit tests
  - these tests can sometimes show environment issues

It could be argued that implementation/environment tests could be made at startup with a parameter.
The cost is small, and the tests can save time by giving clear indications or stopping at "problems". These tests are a part of the implementation code, not an external test to the implementation code.

I have to google a bit more, but I think the transition of javascript from the client to the server has also taken a method that tests the environment, ie the browser, and that the api/implementation tests _may_ be something requires thought.

**Comment by OwenBrotherwood** [comment]
I feel that the implementation code in loopback is being overloaded with documentation to support some auto generation of documentation ... with examples.
It just doesn't seem right.

---

For some reason, I keep thinking about http://en.wikipedia.org/wiki/Modula-2: those where the old days

**Comment by OwenBrotherwood** [comment]
Can we close the issue?

I feel that comments have been made and it is now up to some form of issue that carries the whole test/doc/what do we want of Things

@crandmck can keep a reference to this issue even if it is closed.
