### ISSUE TITLE
PUT for belongsTo relation

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#1387]
Rest API has put/post for hasMany relations but only GET for belongsTo relation.

It would be nice to have CRUD for belongsTo relation

**Comment by fabien** [comment]
+1

**Comment by Martodox** [comment]
Guys, please address this issue. We are working on an open source angular project with loopback as a backend and to go over this limitation we have to delete an entity first then create once more for the relatio to work, otherwise two update queries are fired by the framework and data never gets updated.

**Comment by superkhau** [comment]
Contributions are welcome! ;)

**Comment by Martodox** [comment]
Not a bad idea. Could you assign me to this issue so I won't forget to resolve it in a spare time?
