### ISSUE TITLE
server break down if password is in numeric form on reset password

### ISSUE THREAD

**Issue by dhirender-tyagi** [strongloop/loopback#1437]
server get break down if i give password as numeric in reset password case because it is handled as number so number.indexOf() get break

**Comment by BerkeleyTrue** [comment]
This method is also causing us huge issues when used in combination with loopback-component-passport. We had to revert our production servers back to our old setup after a surge of (crashing) errors in this method from our live users using oauth.

Seems like it tries to set password when oauth is being used. Since no password is given and no password is required in this situation why isn't there a check here for existence and type of string?

@ritch Would you be open to a PR. This is blocking for us from moving forward with loopback.

something like this:

```js
UserModel.setter.password = function(plain) {
      if (!plain) {
         return;
      }

      // for the issue above
      plain = '' + plain;
      if (plain.indexOf('$2a$') === 0 && plain.length === 60) {
        // The password is already hashed. It can be the case
        // when the instance is loaded from DB
        this.$password = plain;
      } else {
        this.$password = this.constructor.hashPassword(plain);
      }
};
```


cc @quincylarson @terakilobyte

![keymetrics___app](https://cloud.githubusercontent.com/assets/6775919/8185917/e8281cb4-13fb-11e5-9a76-b5761a4ac98f.png)
