### ISSUE TITLE
User.afterRemote('confirm') has undefined model instance

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback#1475]
When adding a hook to the 'confirm' method for a model extending the default User model, the instance parameter in the cb is always undefined:

```
MyUser.afterRemote('confirm', function (context, user, next) {
    console.log(user) //undefined
}
```

Is this intended behavior?

**Comment by superkhau** [comment]
I don't beleieve it's always undefined. See the tests at https://github.com/strongloop/loopback/blob/master/test/user.test.js#L996 for some of the use cases.

For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by DaGaMs** [comment]
I see the same behaviour as @csvan: a remote hook on `confirm` has no `user` instance set. It's peculiar because the confirm succeeds otherwise.

@superkhau I don't see how the reference to the test cases is relevant here? I don't see a test of `afterRemote('confirm')`. What makes you think it's _not_ always undefined? I have no problem with `afterRemote('create')`, which is tested aplenty, but `confirm` seems to be have differently somehow. I apologise if this is an "RTFM" but it's not at all obvious to me that I'm doing anything wrong.

**Comment by superkhau** [comment]
@DaGaMs No problem, that link seems to have moved down. See this test https://github.com/strongloop/loopback/blob/master/test/user.test.js#L1264 -- it asserts user should include result or fail. The tests are passing ATM so I came to the conclusion that something is there.

However, that said I do recall the obvious weirdness to the API when I created loopback-example-app-logic with the strange fact that we always have to include the second arg `user`. I believe this was due to some history with the taking over of JugglingDB -- @ritch can you confirm this? I remember talking to you about this before a long time ago.

> I apologise if this is an "RTFM" but it's not at all obvious to me that I'm doing anything wrong.

Nah, we're probably doing something wrong because it's not easy to figure out why. @crandmck I think need some more clarification in the docs regarding this. @ritch is the SME here, possibly @bajtos too since he worked on the hook code.

**Comment by bajtos** [comment]
Note that `create` and `confirm`

> However, that said I do recall the obvious weirdness to the API when I created loopback-example-app-logic with the strange fact that we always have to include the second arg user. I believe this was due to some history with the taking over of JugglingDB -- @ritch can you confirm this? I remember talking to you about this before a long time ago.

I agree the current method signature `(ctx, unused, cb)` is confusing. Perhaps it's time to simplify it to promise-based `(ctx) -> Promise`, with a fallback to support old three-arg handlers?

As for this particular issue with `User.confirm`. I believe the second argument holds the result of the method call, not the model instance. (See [lib/model.js](https://github.com/strongloop/loopback/blob/6b6ca95e2d8d6bb0f0ddeaa66b14abca83ec47f0/lib/model.js#L211).)

```js
User.create(data, function(err, result) {
  // result is the user instance created
});

User.confirm(uid, token, redirect, function(err) {
  // result is undefined
});

User.afterRemote('**', function(ctx, result, cb) {
  // result may be the user created, but also undefined
});
```

Does our documentation say that the second handler argument is "the instance parameter"? If it's so, then we should fix the docs. Any volunteers to contribute this change? See http://loopback.io/doc/en/contrib/doc-contrib.html.

**Comment by superkhau** [comment]
>I agree the current method signature (ctx, unused, cb) is confusing. Perhaps it's time to simplify it to promise-based (ctx) -> Promise, with a fallback to support old three-arg handlers?

+1 for Promise based API

**Comment by DaGaMs** [comment]
@superkhau I think I see the misunderstanding now: the link to the code that you sent refers to hooks on the `create` method. I was talking about `confirm`, which is what is invoked when a user clicks on the verification email (whereas `create` is invoked on POST to `/Users`). After some head-scratching, I realised that the problem is probably that no access_token is set upon confirmation, and hence no user object is returned? The confirmation url has a confirmation one-time token, which is matched against the user table, but it doesn't seem to resolve into a user object in the remote hook.

**Comment by DaGaMs** [comment]
So as a workaround, I currently have to fetch the user "manually" using the user ID, which is part of the request, via `User.findById(context.args.uid)`.

**Comment by ritch** [comment]
As long as `context, user, next` is documented as part of the before/after remote api - we should be good. This is confusing for many other cases.

**Comment by bajtos** [comment]
Note that for after remote hooks, handler's signature is `context, result, next` (at least AFAIK). It happens that most CRUD operations return the model instance as the result, therefore `result` is often the model (user) instance, but not always.
