### ISSUE TITLE
Add a Windows Phone client API.

### ISSUE THREAD

**Issue by James-Parsons** [strongloop/loopback#1497]
One of my biggest holdbacks in using Loopback is the client SDK's. Loopback provides support for iOS, Android, and AngularJS. It would be nice to have a Windows Phone API that could connect C#, VB.Net, JavaScript, and C++ Windows Phone apps to Loopback. I would just use the Loopback AngularJS SDK plus WinJS, but I am iffy about learning AngularJS 1.0, and I don't know if you are going to upgrade when AngularJS 2.0 comes out.

**Comment by BLamy** [comment]
Web components are pretty cool I would suggest trying to understand them before just dismissing loopback because of their choice of client sdk. 
Angular 2 is also a lot more then just web components. And personally I would prefer to see their efforts go toward angular 2 instead of windows. 
 

I don't work at strong loop just giving my two cents.

**Comment by crandmck** [comment]
@James-Parsons Check out the new Xamarin SDK.  It hasn't been officially announced yet, but it should support creating a Windows Phone API:
- http://docs.strongloop.com/display/LB/Xamarin+SDK
- https://github.com/strongloop/loopback-sdk-xamarin

**Comment by James-Parsons** [comment]
Awesome, I am starting to use Xamarin, so this will be cool

**Comment by crandmck** [comment]
I'm going to close this.  If there are specific issues related to Xamarin, Windows, etc., please open a new issue.  Thanks!
