### ISSUE TITLE
Express 5

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1507]
Express 5 beta should be released soon. I am wondering if anyone has any thoughts on how we should upgrade. Some options I am considering:

**Idea 1**
Factor out hard dependencies on express 5 in loopback (not very many) and strong-remoting (quite a bit more). This would allow users to supply their own version of express 4 or 5. It would be harder to guarantee applications using advanced features of express (and friends) will work as expected though. Right now we get this by using Express 4 explicitly and making that a requirement for LB components / apps.

**Idea 2**
Deprecate support for Express 4 and explicitly require Express 5. I don't think this is quite as useful as factoring out Express as a hard dependency. It is probably a bit simpler. There are only a few fairly trivial changes (eg. moving code from express to another module).

Either way, it would be nice to have something on the roadmap before the beta is concluded.

@raymondfeng @bajtos @fabien

**Comment by bajtos** [comment]
I would personally go with Idea2 and simply upgrade loopback's and strong-remoting's dependencies to use Express 5, in a similar way as LoopBack 2.0 upgraded from Express 3 to Express 4. My opinion is based on the assumption that most loopback users want a framework that has made some of the hard decisions for them, a framework that has picked the right set of express core modules, so that loopback users can focus on implementing their application.

OTOH, I don't know almost anything about the differences between Express 4 and Express 5. @ritch could you please briefly describe the benefits of allowing loopback users to supply their own express version and also the (most important) differences between express 4 and 5? I think that's an important factor to take into consideration.

**Comment by fabien** [comment]
As someone who has been using LB as a part of an existing Express 4 setup, I would definitely appreciate this still being supported, without too much hassle on the Express side of things (meaning: the eco-system around it, like middleware). I don't know 4 is different from 5, and what's expected to break, but keeping BC sounds best to me.
