### ISSUE TITLE
Cascade delete

### ISSUE THREAD

**Issue by Nutelac** [strongloop/loopback#1520]
What is best way to handle cascade delete?

Note that I’m using replication, so `SomeModel.observe(‘before delete’, …)` is not probably good idea, because:
- observe just in `LocalModel` will not work on server side.
- observe just in `Model` will cause delay until replication is done.
- observe in both `LocalModel` and `Model` will “broke" replication because `LocalModel` extending `Model` => `LocalModel` will do two observe actions.).

Any other ideas?

**Comment by jmls** [comment]
did you get an answer to this ?

**Comment by Amir-61** [comment]
I believe this is related: https://github.com/strongloop/loopback-datasource-juggler/issues/88

**Comment by jannyHou** [comment]
@Amir-61 Thank you for providing the related link. I think the `cascade delete` in that link happens between related models. While the requirement in this issue is something like offline-sync
@Nutelac I am not quite familiar with the solution of your scenario. Could you take a look of example:
https://github.com/strongloop/loopback-example-offline-sync
and see if that helps? 
Any feedback are appreciated. Thanks.

**Comment by jannyHou** [comment]
I am closing this issue here since it's 1 year ago. Please feel free to reopen it if you have further questions. Thanks.
