### ISSUE TITLE
Problem with ValidationAsync

### ISSUE THREAD

**Issue by FelipeAguayo** [strongloop/loopback#1523]
every time I do a validation with 'ValidationAsync' I get the following response:

```json
{
  "error": {
    "name": "ValidationError",
    "status": 422,
    "message": "The 'Model' instance is not valid. Details: (unknown).",
    "statusCode": 422,
    "details": {
      "context": "Model",
      "codes": {},
      "messages": {}
    },
    "stack": "ValidationError: The 'Model' instance is not valid. Details: (unknown).\n    at EmbedsMany.create (node_modules\\loopback-datasource-juggler\\lib\\relation-definition.js:2682:39)\n    at ModelConstructor.method (node_modules\\loopback-datasource-juggler\\lib\\relation-definition.js:726:33)\n    at ModelConstructor.fn_create [as __create__models] (node_modules\\loopback-datasource-juggler\\lib\\scope.js:282:7)\n    at SharedMethod.invoke (node_modules\\loopback\\node_modules\\strong-remoting\\lib\\shared-method.js:234:25)\n    at HttpContext.invoke (node_modules\\loopback\\node_modules\\strong-remoting\\lib\\http-context.js:375:12)\n    at node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:608:11\n    at execStack (node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:448:7)\n    at RemoteObjects.execHooks (node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:452:10)\n    at node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:605:10\n    at node_modules\\loopback\\lib\\application.js:357:13"
  }
}```

and the model instance is VALID!! u.u

**Comment by ekussberg** [comment]
I have the same problem, is it already fixed? @raymondfeng @bajtos 
Use embedsMany and testing from explorer the POST method. All values are valid.

**Comment by bajtos** [comment]
I am personally not familiar with embedded relations, perhaps @fabien can be more helpful?

**Comment by fabien** [comment]
@ekussberg @FelipeAguayo is this related to this, perhaps?

https://github.com/strongloop/loopback/issues/1552#issuecomment-127844476

Do you have more information on the data you're posting? As outlined in the comment (and the updated documentation), it won't work when you POST data with embedded relations as nested data.

**Comment by jannyHou** [comment]
@ekussberg @FelipeAguayo Please see [doc](https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-EmbedsMany) and example here(https://github.com/strongloop/loopback-example-relations/blob/master/server/boot/z-customer-emails.js#L15) and (https://github.com/strongloop/loopback-example-relations/blob/master/server/boot/z-customer-emails.js#L15) to follow the right way to create instance.
If you still have questions please provide your code (you can fork this repo https://github.com/strongloop/loopback-sandbox and upload your project to sandbox, then let's solve problems together!)
For future reference, please ask questions on [google group](https://groups.google.com/forum/#!forum/loopbackjs)
I will close this issue because it looks like a duplicate issue of https://github.com/strongloop/loopback/issues/1552#issuecomment-127844476, if it's not your case, please leave comment then I can reopen the issue for you. Thanks!
