### ISSUE TITLE
user.confirm is not redirecting.

### ISSUE THREAD

**Issue by mercuriete** [strongloop/loopback#1541]
Maybe I am missing something but i dont get the redirection working properly.

I set the redirect parameter to the link url that is sent by email.

and when I follow this link what happen is that the loopback server tries to connect to this page and then delivers a copy to the client.

This is not a redirection but a proxying of another page.

This is not correctly well documented and makes me imposible to redirect to a different server.

My set up of my application is an application server that routes to the loopback when the url starts with /api.

What i wanted to do is when i follow the link from the email is to get redirected to the first server and not continuing in this /api/user/confirm endpoint.

Thanks in advance.

edited:

maybe i sould create a dummy page with a redirection to change the url.
because the problem that i have is that the url is different that i expect so the application router thinks that i am in a wrong page.

So in fact it would be nice that the loopback behaviour will be send a page with a redirection instead of a copy with the content of this page.

edited2:

finally I get a solution for my problem. I added a route to this page and now I could manage to do what i wanted.

**Comment by jannyHou** [comment]
Hey @mercuriete glad to know that your problem is solved! If you still have questions about document or routing related issues, please provide the  doc link as well as your code (you can fork this repo https://github.com/strongloop/loopback-sandbox and upload your project to sandbox, then we can solve any problem together more easily!)
For future reference, please ask questions on [google group](https://groups.google.com/forum/#!forum/loopbackjs)
