### ISSUE TITLE
Update and Remove Model Definitions and Configurations at runtime

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1590]
Right now it is only possible to `boot()` a set of `ModelConfig`s and `ModelDefinition`s. There are no APIs that allow for updating or removing these models. I have heard this feature requested a few times, so I'd like to make a formal issue to represent those requests.

If you are reading this and would also find this feature useful please speak up. This isn't a trivial feature to add, but if there is enough demand I think we can justify the time spent to add it.

**Comment by lidatong** [comment]
I'm new to loopback, and was looking for a way to do this with the generator. I guess it's manual removal for now - I agree this feature would be cool!

**Comment by superkhau** [comment]
+1 There are only generators, no de-generators. I suppose we can just add -d flags to the current set of generators, etc.

**Comment by SukantGujar** [comment]
We are managing loopback instance and allowing dynamic extension of models. It'd be great to have APIs to remove models.

**Comment by bajtos** [comment]
Cross-posting my answer from https://stackoverflow.com/a/45594066/69868:

Let's take a look at the REST API first. In order to remove the model from the REST API, we need to remove it from the list of "shared classes" maintained by strong-remoting and then clean the cached handler middleware.

    delete app.remotes()._classes[modelName];
    delete app.remotes()._typeRegistry._types[modelName];
    delete app._handlers.rest;

When the next request comes in, LoopBack will create a new REST handler middleware and rebuild the routing table.

In essence, we need to undo the work done by [this code](https://github.com/strongloop/loopback/blob/74cbe129186a164b79d26620323b3650dcb857e5/lib/application.js#L140-L150).

In order to remove the model from LoopBack JavaScript APIs, we need to remove it from the list of models maintained by application's registry:

    delete app.models[modelName];
    delete app.models[classify(modelName)];
    delete app.models[camelize(modelName)];
    app.models.models.splice(app.models.indexOf(ModelCtor), 1);

(This is undoing the work done by [this code](https://github.com/strongloop/loopback/blob/74cbe129186a164b79d26620323b3650dcb857e5/lib/application.js#L133-L138)).

Next, we need to remove it from loopback-datasource-juggler registries:

    delete app.registry.modelBuilder.models[modelName];

Caveats:

 - I haven't run/tested this code, it may not work out of the box.
 - It does not handle the case where the removed model has relations with other models.
 - It does not notify loopback-component-explorer about the change in the API

**Comment by shrimaliakash** [comment]
how to remove model in loopback using command line using slc tool???

**Comment by shrimaliakash** [comment]
please give the answer fast

**Comment by bajtos** [comment]
https://github.com/strongloop/loopback/pull/3858 has added a new api `app.deleteModelByName()` that allows developers to delete a model from the app.
