### ISSUE TITLE
REST API of PersistedModel should expose a way to delete several instances

### ISSUE THREAD

**Issue by ezraroi** [strongloop/loopback#1620]
The REST API of PersistedModel and the Angular SDK don't have a way to delete several instances by supplying a WHERE filter.

**Comment by bajtos** [comment]
This was an intentional decision. If you enable bulk-delete and the user does not provide a WHERE filter that's narrow enough (e.g. because they construct the filter argument incorrectly), then the call would delete all model instances in the database.

I am recommending two options:
 - Write a custom remote method ([introduction](https://strongloop.com/strongblog/remote-methods-in-loopback-creating-custom-endpoints)) that will accept a limited set of properties and build the `where` filter on the server. 
 - Ignore my warning and expose the built-in `deleteAll` method in the REST, see https://github.com/strongloop/loopback/issues/491#issuecomment-116833323
