### ISSUE TITLE
Cannot pass data between operation hooks

### ISSUE THREAD

**Issue by h2non** [strongloop/loopback#1621]
This doesn't works. There's another alternative and consistent way to pass data between hooks in the same transaction scope without doing global weird stuff??

```js
Customer.observe('before save', function(ctx, next) {
  ctx.modelData = "A"
  next()
})

Customer.observe('after save', function (ctx, next) {
  console.log('modelData', ctx.modelData)
  next()
})
```

**Comment by h2non** [comment]
As workaround, I've just discovered that sharing data inside `ctx.options` works, since the reference to that object remains across the hooks pipeline.

This is so ugly. Another solution?

**Comment by superkhau** [comment]
@bajtos ^

**Comment by bajtos** [comment]
`ctx.hookState` is the answer, see [docs](https://docs.strongloop.com/display/LB/Operation+hooks#Operationhooks-SharedhookStateproperty) for more details.

**Comment by h2non** [comment]
I saw it also, but I thought it's used for internal purposes. I guess that's enough. Thanks

**Comment by barocsi** [comment]
then whats the difference between ctx.options and ctx.hookState?

**Comment by bajtos** [comment]
> then whats the difference between ctx.options and ctx.hookState?

 - `ctx.options` is set using `options` argument provided to DAO methods like `MyModel.find` or `MyModel.create`. If there are was `options` argument provided, then `ctx.options` is set to an empty object, so that hooks don't have to check whether `ctx.options` is set.
 - `ctx.hookState` is for sharing data between hooks (e.g. "before save" and "after save").

@crandmck Perhaps this is something to capture in our docs?

**Comment by barocsi** [comment]
Thanks it was already cleared for me as well as for a legacy code to be turned to option propagation it means to run over ALL the code and all DAO methods to properly implement the new parameter. 

I think to persist ctx without passing parameters on and on would require an isolated DAO provider with a ctx instance that is used to factory the remaining Model instances. 
DAO layer could be created for each remote method call and garbage collected afterwards. However it would sound pretty complicated and I bet would soon face the issues of the currentContext paradigm.

**Comment by bajtos** [comment]
> I think to persist ctx without passing parameters on and on would require an isolated DAO provider with a ctx instance that is used to factory the remaining Model instances.
DAO layer could be created for each remote method call and garbage collected afterwards. However it would sound pretty complicated and I bet would soon face the issues of the currentContext paradigm.

I see what you mean. I am exploring this concept for Controllers, where a new controller instance would be created for each request. I don't have anything specific to share yet.

BTW if CLS-based context propagation works well for you, then you can use https://www.npmjs.com/package/loopback-context after upgrading your app to LB 3.x. The package version `1.x` contains the very same code that was part of LoopBack 2.x. The package version `2.x` uses `cls-hooked` instead of `continuation-local-storage` under the hood, it seems to be more reliable.

**Comment by barocsi** [comment]
Yes, I am using it right now, thanks. 
However still some packages break loopback-context 3.0.0 still, like loopback mongodb connector ^1.8.0 so one should be aware of that.

**Comment by crandmck** [comment]
> Perhaps this is something to capture in our docs?

I clarified and added a bit more to http://loopback.io/doc/en/lb3/Operation-hooks.html#sharedhookstateproperty.  Hopefully that covers it.

LMK if anything else is needed.

**Comment by bajtos** [comment]
@crandmck awesome, thank you!

I think you have a typo in the new text: "If *an* options argument was provided" should be "If *no* options argument was provided".

**Comment by crandmck** [comment]
OK, this text came from your [comment above](#issuecomment-276061223) which seems to have a typo as well, which I apparently misinterpreted:
>  If there are was options argument provided, then ctx.options is set to an empty object, so that hooks don't have to check whether ctx.options is set.

I changed to "If an options argument was provided" but just wanted to be sure that is correct.

**Comment by barocsi** [comment]
actually the oroblem might be extended to between operation hooks of different persistedmodels

**Comment by crandmck** [comment]
@barocsi Please suggest wording changes in PR to https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Operation-hooks.md

I'm not confident of my understanding of this area, so your help is appreciated!

**Comment by bajtos** [comment]
@crandmck I checked loopback.io, the current version LGTM. Thanks for fixing it!

> @barocsi 
> actually the problem might be extended to between operation hooks of different persistedmodels, not only the same

Are you asking how to pass hook state between let's say "before save" hook on a `Product` model and "before save" hook on a `Category` level, invoked e.g. by a single embedded relation method? I am afraid this is a use case we haven't considered yet. Please open a new issue to discuss it and mention my handle (`@bajtos`) so that I get notification.

**Comment by barocsi** [comment]
That would be the same scope as the the currentcontext, options propagation and createoptionsfromremotecontext scope I guess?
