### ISSUE TITLE
Why embedsOne document update validates the parent model?

### ISSUE THREAD

**Issue by h2non** [strongloop/loopback#1630]
I'm just trying to perform a pretty simple transaction. 

Given the `User` model, which has one `embedsOne` persisted relations to `stats` and another `embedMany` relation to `settings`, I'm just trying to update one field in the embedded model. 

```js
// `user` is a filled model
user.stats.update({ likes: 1 }, function (err, stats) {
   // ...
})
```

But I'm getting a validation error from the parent `User` model related to `settings` relation:
```js
{
    "error": {
        "name": "ValidationError",
        "status": 422,
        "message": "The `user` instance is not valid. Details: `settings` contains invalid item at index `0`: `id` is blank."
    }
}
```

Why the whole `User` model is validated if I'm just updating a embedded document? 
How can I do that properly?

**Comment by h2non** [comment]
@fabien @raymondfeng Please, can someone provide some light here? 
This is silly but really blocking issue.

**Comment by h2non** [comment]
After a frustrating experience, I've started reviewing the code, more specifically the `datasource-juggler` and `connector-mongodb`, and as a workaround I did a hack to call directly [`updateAttributes()`](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L795) in the mongo connector. 

This is so ugly, but at the end it was the unique solution I've found in a reasonable time to perform a partial update the specific document properties.

This kind of issues are very annoying, because in this case the operation is pretty trivial and very common, and doing it was a big trouble in Loopback, however, using the MongoDB driver, o even some ODM like Mongoose is trivial.

**Comment by loay** [comment]
we only accept feature requests and bug reports there.
SEE: https://groups.google.com/forum/#!forum/loopbackjs

**Comment by h2non** [comment]
Oh, grand! Looks like since you has been bought by IBM you're improving the company support policies with fresh modern and ultra useful ways. 

(irony off)
Leaving Github is a really bad choice IMHO.

**Comment by superkhau** [comment]
@h2non Sorry for the confusion, we have a lot of new people coming on board to help with the triaging of GitHub issues so bear with us. This sounds like a question for @raymondfeng or @fabien.

**Comment by superkhau** [comment]
@h2non Could you provide a sample for us to reproduce the issue? https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by superkhau** [comment]
>Why the whole User model is validated if I'm just updating a embedded document?

@raymondfeng @fabien ^

>How can I do that properly?

@crandmck ^ You'll probably need input from @raymondfeng or @fabien  to update the docs with their answer.

**Comment by superkhau** [comment]
>Leaving Github is a really bad choice IMHO.

@bajtos @ritch @raymondfeng Any opinion here? I also prefer GitHub for all things issue related.

**Comment by bajtos** [comment]
> @superkhau Any opinion here? I also prefer GitHub for all things issue related.

I don't have a strong opinion.

While I personally prefer to keep all discussions that may lead to a bug/enhancement report on GitHub, I do understand that offloading questions to the mailing list reduces the amount of GH issues we have to process as part of our triage process.

**Comment by bajtos** [comment]
> Why the whole User model is validated if I'm just updating a embedded document?

In order to save the updates made in an embedded model, the embedded model calls `save()` on the parent model, which triggers validation of the parent model. See the [source](https://github.com/strongloop/loopback-datasource-juggler/blob/1e8fe6a0d7b5c84a3f67ad4d6a05ddaa8d1229ba/lib/relation-definition.js#L2195).

I am not sure what's the right behaviour, whether embedded relation should or should not trigger validation of the parent model. I can imagine a use case where the parent model validates properties inside embedded models. For example, if `Person` has `phone` property and embedded `address`, one may want to validate that the international prefix of `this.phone` matches the country filled in `this.address.country`.

@h2non is this issue still relevant? I think the behaviour you are observing may be partially caused by the way how you are creating the `user` instance. Could you please provide us with a full app which we can use to reproduce your problem, per instructions here? https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by h2non** [comment]
Thanks for the answer, but I'm not using loopback anymore. Fell free to close the issue.

**Comment by loay** [comment]
Closing the issue. 
@bajtos please re-open if you still think it is relevant for any work/discussion. Thanks.
