### ISSUE TITLE
Where is the swagger.json file used by the explorer?

### ISSUE THREAD

**Issue by danielrvt** [strongloop/loopback#1641]
I would like to get the swagger json file used by the loopback explorer, tweak it and install it somewhere else. How can I get this file?

**Comment by raymondfeng** [comment]
Do you refer to swagger 1.2? If so, the resource listing file is available from http://localhost:3000/explorer/resources.

We have swagger 2.0 support almost ready. The spec will be served from http://localhost:3000/explorer/swagger.json

**Comment by javierfdr** [comment]
From http://localhost:3000/explorer/resources you only have the resource list in a general way. Since Loopback-explorer is loading Swagger manually does not seem possible to do that yet. Howerver if you click the option "RAW" beside each resource you will have a part of the documentation. You could join those parts together to build a full swagger.json

**Comment by raymondfeng** [comment]
API specs for swagger 1.2 consists the resource listing file and individual apis. We use this code to download the complete list - https://github.com/strongloop/generator-loopback/blob/master/swagger/spec-loader.js. Feel free to borrow some code.

Swagger 2.0 will only have one swagger.json for all apis.

**Comment by jmls** [comment]
when will 2.0 support be ready ?

**Comment by SandeshSarfare** [comment]
How do I change swaggerVersion to 2.0? And is the support ready for the same?
