### ISSUE TITLE
$owner ACL requires model to be persisted

### ISSUE THREAD

**Issue by esco** [strongloop/loopback#1710]
Let say I have a Post model and a User model. Post has a `belongsTo` relation to User. There is an ACL denying `$everyone` anything and allowing `$owner` "WRITE". When POSTing a new Post that contains a `userId` field (the name of the belongsTo relation) via /api/Post, a 401 is returned. From the [looks of it ](https://github.com/strongloop/loopback/blob/e68cd8fc87730404a78e1475b828886e3582bd6f/common/models/role.js#L199), the $owner ACL only works on models that are already persisted. Is this intended? Shouldn't the `$owner` ACL be applicable to models that haven't yet been persisted and are currently being POSTed for creation? According to the [docs](https://docs.strongloop.com/display/public/LB/Controlling+data+access), "WRITE" applies to the create method.

https://github.com/strongloop/loopback/blob/e68cd8fc87730404a78e1475b828886e3582bd6f/common/models/role.js#L199

https://docs.strongloop.com/display/public/LB/Controlling+data+access

**Comment by superkhau** [comment]
Please ask questions on one of our official channels. See https://github.com/strongloop/loopback/wiki/Questions. Closing.

**Comment by Neil-UWA** [comment]
I agree that the ACL implementation should check whether the user who does the create action is the owner before the records persisted. Also the loopback doc states that the acl works on write methods including write, but the current behaviour doesn't comply with what the doc states.

**Comment by ahmed-abdulmoniem** [comment]
@superkhau Any solution to this .. I don't think it is a question .. it is unwanted behavior opposite to what stated in the docs!

**Comment by superkhau** [comment]
@ahmed-abdulmoniem Let's reopen this then. ;) @crandmck Can you work with us here to reword the docs so the correct behaviour is stated?

**Comment by crandmck** [comment]
> ... the $owner ACL only works on models that are already persisted. Is this intended? Shouldn't the $owner ACL be applicable to models that haven't yet been persisted and are currently being POSTed for creation? 
> ...
> it is unwanted behavior opposite to what stated in the docs!

It's not clear to me that the docs are incorrect.  From the above comments, it sounds like it doesn't work as it should--which is the behavior that is documented.

Am I misunderstanding?

**Comment by samdidos** [comment]
I don't think that letting all $owner create post would be a good idea. $owner ACL is a dynamic role, so the role is only attributed if the user is trying to do something to an object that already belongs to him. So by default, this role is not attributed to someone who want to create a post. If by default an $owner ACL let create posts, it would mean that ALL users that can possess posts (aka $everyone since Posts belong to Users) can, which is rarely a wanted case (if I rely on the fact that you have deny access to $everyone).

It makes more sens if you assign a static role to those who can create a post (ex. User), or those who are connected to your app ($authenticated), or even another custom dynamic role.

Example with $authenticated (every authenticated users can read and post, but only owners can update/delete their posts)
```
...
"acls": [
  {
    accessType: '*',
    principalType: 'ROLE',
    principalId: '$everyone',
    permission: 'DENY'
  },
  {
    accessType: 'READ',
    principalType: 'ROLE',
    principalId: '$authenticated',
    permission: 'ALLOW'
  },
  {
    accessType: 'WRITE',
    principalType: 'ROLE',
    principalId: '$owner',
    permission: 'ALLOW'
  },
  {
    property: 'create',
    accessType: 'EXECUTE',
    principalType: 'ROLE',
    principalId: '$authenticated',
    permission: 'ALLOW'
  }
]
...
```
The [access control example](https://github.com/strongloop/loopback-example-access-control/) helps a lot to understand how [dynamic roles](https://loopback.io/doc/en/lb2/Defining-and-using-roles.html#dynamic-roles) works.


Hope that helped

**Comment by acrodrig** [comment]
@samdidos I just got bitten by this. If I understand correctly what you are saying then based on your example any authenticated user would be able to post to my blog, not only their own blog, which is not the desired behavior.

From a loopback user perspective (and without understanding the internals of what a dynamic role entails), I think it's desirable to be able to restrict object creation based on the user. If I have this in my ACL:

...
  {
    accessType: 'WRITE',
    principalType: 'ROLE',
    principalId: '$owner',
    permission: 'ALLOW'
  }
...

Then the owner should be able to create/update/delete. As it stands the owner cannot create and that is semantically misguiding.

**Comment by samdidos** [comment]
The original example above only includes a user that owns posts, not blogs. But yeah, that's what I'm saying, and I'm still convinced that owners should not be able to create things, because that's not an action that can be defined by ownership.

An ACL apply to a given model (post), so a user that is owner of posts cannot create something that is not already his. I know that the usage of WRITE in accessType can be misguiding,  but if you allow owners to create something that isn't belonging to anybody, it means that everybody that CAN possess posts can create one (i. e. $everyone, since anybody visiting your app is a user). In the case where the entire app is made to be a blog, you probably want to let only authenticated user create posts (or use an admin role if authenticated users can do other stuff like commenting posts ).

To be more explicit, if you allow or deny 'create' for only owners in any model, it will do nothing, because the dynamic role $owner allocution rely on the fact that an instance is linked to the actual user :
 ```
 {
    accessType: 'EXECUTE',
     property: 'create'
    principalType: 'ROLE',
    principalId: '$owner',
    permission: 'ALLOW'
  } // no effects at all
```
In case of a multiple blog app, you'll need a blog model that belongs to a user which the owner can publish posts in it (so blogs has many posts). In the blog, you can add an ACL that looks like this (based on [this](https://loopback.io/doc/en/lb3/Accessing-related-models.html#restricting-access-to-related-models)) : 
 ```
 {
    accessType: 'EXECUTE',
     property: [
         '__create__posts',
         '__updateById__posts',
         '__delete__posts',
         ...
       ]
    principalType: 'ROLE',
    principalId: '$owner',
    permission: 'ALLOW'
  }
```
I'm aware that there is a lack of documentation since $owner is a built-in role and the actual [documentation](https://loopback.io/doc/en/lb3/Defining-and-using-roles.html#dynamic-roles) only includes what you can do with it but not its limitation. But it do make sense to me the way it is actually.

**Comment by acrodrig** [comment]
@samdidos thanks for taking the time to explain your thought process. I respectfully disagree with your assessment. 

Having a permission to `WRITE` should include creation of entities. As originally stated above, *if* the creation of an entity via `POST` includes the `userId` attribute, then there is a clear case for allowing owners to create their OWN objects.

I believe this is how most people would interpret the permission. If the "feature" requires this much explaining, there is probably something with it.
