### ISSUE TITLE
Add role.principals() and role.roles() to API docs

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#1794]
@crandmck 

Cannot find API info of these two functions from the following code.

Line 50:

```
userRole.principals(function(err, principals) {
        assert.equal(principals.length, 1);
});
userRole.roles(function(err, roles) {
        assert.equal(roles.length, 1);
});
```

https://github.com/strongloop/loopback/blob/9a33602458712afecedd25062f02bd8b5c4e01a5/test/role.test.js

**Comment by crandmck** [comment]
I don't know anything about these methods.  I don't see them in [the source code](https://github.com/strongloop/loopback/blob/master/common/models/role.js).  I do see [principals in the role.json file](https://github.com/strongloop/loopback/blob/master/common/models/role.json#L20), so that might be the source of `userRole.principals`.

Someone in engineering needs to take this and let me know if I need to add something to docs, and if so, what.  I suspect they might not be something that we should document, but I don't know for sure.

**Comment by ritch** [comment]
Those functions come from relations

**Comment by crandmck** [comment]
@ritch I realize they come from relations, but if those relations are intrinsic to how roles work, then should we add them to the API docs?

**Comment by ritch** [comment]
Yes we should add them, similarly to how we've added the `PersistedModel` methods.

**Comment by lobabob** [comment]
So it's been more than a year already. Any updates on where this is at?

**Comment by crandmck** [comment]
I'll try to sort it out.

**Comment by buokae** [comment]
Any update on this? Looking for a way to programmatically remove users from the admin role. The docs only explain giving a user the admin role via Role.principals.create() but not taking it away again. Is there a principals.destroy() or principals.delete() or something like that to do that?

**Comment by buokae** [comment]
Nevermind, I'll persist RoleModel to my datasource and work with that. I'll see if I can update the docs.
