### ISSUE TITLE
swagger.json not including models added after boot?

### ISSUE THREAD

**Issue by timneedham** [strongloop/loopback#1820]
Hi,

It seems when adding models programmatically via `app.model()` __after__ booting via `loopback-boot` and `app.listen()`... everything works fine, but the runtime-added models don't appear in swagger.json and consequently not showing in Strongloop explorer?

* New to Loopback, very impressed... apologies if I'm missing something: adding runtime models is central to my use-case.

Many thanks

Tim

**Comment by gunjpan** [comment]
@timneedham Hey Tim, I am looking into this issue. Could you please provide me a sample repo to reproduce the issue?

**Comment by timneedham** [comment]
@gunjpan Hi, I've put a sample repo here:

https://github.com/timneedham/loopback_issue_1820

...hope it makes sense? Thanks for taking the time to look into this.
Tim

**Comment by gunjpan** [comment]
@timneedham :Hi, after investigating, I've found out that this issue is a know limitation of the current explorer implementation, I am changing the labels to "enhancement". We need to prioritize this request against other stories in our backlog. Found the same issue: https://github.com/strongloop/loopback-component-explorer/issues/140

**Comment by timneedham** [comment]
@gunjpan Great stuff, I look forward to seeing it in a story soon!
Tim

**Comment by timneedham** [comment]
@bajtos Thank you, this works perfectly now. Tim
