### ISSUE TITLE
Documentation Middleware 

### ISSUE THREAD

**Issue by daslicht** [strongloop/loopback#1824]
Hi,
see here:
https://docs.strongloop.com/display/public/LB/Add+a+static+web+page#Addastaticwebpage-Introductiontomiddleware
The Files Middleware wont work until you remove the following from middleware.json:
```
  "routes": {
    "loopback#status": {
      "paths": "/"
    }
  },
```

This should be mentioned there.

**Comment by Amir-61** [comment]
Hi @daslicht,

Thanks for mentioning this here! You are absolutely right; if you have the following in the `middleware.json`, you already defined a route for `/` to show the loopback status in `routes` phase, which happens before `files` middleware and you no longer get `files` middleware, sinceresponse is sent in `route` phase: 

    ```  "routes": {
    "loopback#status": {
      "paths": "/"
    }
  }```

This is an expected behaviour since order of middleware is important; however, we can definitely clarify this in the documentation you cited.

Thanks for mentioning it here!

**Comment by daslicht** [comment]
Thank you for the Reply !
