### ISSUE TITLE
Datasource 

### ISSUE THREAD

**Issue by digitalsadhu** [strongloop/loopback#1849]
@bajtos @superkhau @raymondfeng @ritch (apologies to anyone else who I haven't had the pleasure of interacting with yet) and apologies if this is A: already supported in some way or B: already has an issue somewhere else.

**Problem:**
Mapping custom datatypes for specific databases is limited. You can override a mapping in model schema but as far as I can tell you can't define a way to translate from the incoming json payload to something that can be inserted into the database table in cases where the datatype defined is not supported. Likewise, if you can't define how a datatype will be converted to json on the way out of the table.

**Examples use cases:**
- With postgres, I would like to use array datatypes.
- With postgis, I would like to use geospatial types

**Solution:**
I propose an API to allow connector level in/out mappings to/from json. Ember js has this type of concept with "transforms". This situation is a bit more complex since typically we would need to map json -> SQL and vice versa, however the idea seems sound to me. A user should be able to define a "transforms" key on a column in model.json which could then have keys for "in" and "out" where SQL/json mappings could be defined. This would provide a flexible solution to the problem above and reduce the need for PRs to be landed for every specific connector specific feature.

If this is something that would be of interest, i'd be happy to do a more detailed proposal write up with detailed examples and perhaps an initial API proposal to get some discussion happening. If this is a misguided effort just let me know :)

**Comment by bajtos** [comment]
Hi @digitalsadhu, thank you for the interesting feature idea. Your proposal makes sense to me from the high level point of view, as far as I can judge it without specific examples of what the customized SQL would look like.

Let's give @raymondfeng and @ritch few days to comment before we continue to a more detailed proposal.

**Comment by digitalsadhu** [comment]
Sure thing :+1:

**Comment by superkhau** [comment]
@digitalsadhu +1 for your proposal, makes sense to have a transform layer in between. With regards to the implementation, we'll definitely need to see examples of SQL/NoSQL before going any further IMO.

**Comment by raymondfeng** [comment]
@digitalsadhu Did you look at https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L1272-L1284?

**Comment by amenadiel** [comment]
I'm both a heavy user of both loopback and postgis, and as much as I'd like loopback to be able to deal with postgis datatypes, I don't see it coming anytime soon.

You see, binary geometries are stored in WKB (Well Known Binary) and can be printed as WKT or GeoJSON before sending them to the client. For this, it would be helpful to have loopback support transformed properties. This way the geometry attribute of the model could be the result of calling `ST_AsGeojson` on the geometry field of the table. This one is faily easy.

However, this would bring a lot of added complexity, since you'd have to call [`ST_Geomfromgeojson`](http://www.postgis.org/docs/ST_GeomFromGeoJSON.html) on the model before persisting any changes back to the DB. Also, any spatial predicate such as determining the overlapping entities of two models would have to be done at the DB level, because once converted to geojson they will be treated as regular objects.

I tried using [spatialite](http://www.gaia-gis.it/gaia-sins/) as a substitute, but WKB unpacking behaves erratically, perhaps because that package is meant to read from a local sqlite db instead of dealing with the latency of a remote DB. Anyway, in the end I resorted to running native SQL sentences. 

```js

    var postGis = server.dataSources.mypostgisDB;
    postGis.connector.query(
            "SELECT id, st_asgeojson(the_geom,6) from stores", 
            null, 
            function (err, theresults) {
               ... do something with results ...
            });
```
