### ISSUE TITLE
Filter relations

### ISSUE THREAD

**Issue by BenjaminHorn** [strongloop/loopback#1862]
```javascript
{  
   "where":{  
      "age":{  
         "gt":30
      }
   },
   "include":{  
      "relation":"orders",
      "scope":{  
         "where":{  
            "total":{  
               "gt":3000
            }
         }
      }
   }
}
```
this returns ALL customers with age 30+ and if they have one or more orders with a total more then 3000. Is it possible to query ONLY the customers, where orders > 3000 AND age > 30?

In SQL I would write it in one statement:
```SQL
SELECT * FROM order o, customer c WHERE c.id = o.customer_id AND o.total > 3000 AND c.age > 30 
```
So I can have it with one SELECT

**Comment by richardpringle** [comment]
@superkhau, no one is assigned to this issue, you on top of it?

**Comment by superkhau** [comment]
no

**Comment by richardpringle** [comment]
Hey @BenjaminHorn, I'm not sure it's possible to do what you are attempting (but it should be). I think there may be a feature request asking for the same thing.

In the meantime, try using this as a workaround: https://docs.strongloop.com/display/public/LB/Executing+native+SQL

Hope that helps!

**Comment by richardpringle** [comment]
@BenjaminHorn, I just got the confirmation that what you are trying to do is not possible, you cannot use information from related models as the criteria to query the main model. Please let me know if executing native SQL works.

I am going to close the issue though since the functionality you are looking for is not supported. If you would like to open a new issue requesting that feature, please do so.

**Comment by BenjaminHorn** [comment]
@richardpringle  we use native SQL, and it works. But still, it would be nice to have this feature.
