### ISSUE TITLE
Feature Request - Multiple models with same plural name

### ISSUE THREAD

**Issue by pktippa** [strongloop/loopback#1873]
As suggested by @richardpringle in #1863 raising a request for the feature.

While creating model from 
1. [loopback-workspace](https://github.com/strongloop/loopback-workspace) api, if we POST /ModelDefintions
2. loopback.createModel
3. datasource.createModel

with the same plural name existing in already in previously created models, should stop creating models or atleast warn and stop model creation.

**Comment by pktippa** [comment]
Hi @richardpringle I would like to work on this feature, please let me know the pointers and code to debug the same.

**Comment by richardpringle** [comment]
Hey @pktippa, glad you would like to help! I'm actually pretty new to Loopback, so I don't have an answer off the top of my head :confused:. What I would do if I were you is step through the code with a debugger (I like [node-inspector](https://github.com/node-inspector/node-inspector)).

If you're using the standard scaffolding, the [execute function](https://github.com/strongloop/loopback-boot/blob/master/index.js#L140) is probably the first place you want to look.

You might want to handle the warning in the [setupModels function](https://github.com/strongloop/loopback-boot/blob/master/lib/executor.js#L173-L183) but you would have to check against every model that has been loaded already which could be time consuming.

@bajtos, what do you think?

**Comment by bajtos** [comment]
> loopback-workspace api, if we POST /ModelDefintions

We already validate uniqueness of model name, see https://github.com/strongloop/loopback-workspace/blob/bfcf676204d3be69e7362b7974399508f930f7ea/common/models/model-definition.js#L33

> datasource.createModel

loopback-datasource-juggler is not aware of remoting configuration (like plural model name). Instead of reporting an error at definition time, you should report an error when the model is attached to an app via `app.model`.

> loopback.createModel

Same comment as above - it doesn't make much sense to validate plural model name if the model is not exposed via REST API.

I think this is the right place where to implement the validation: https://github.com/strongloop/loopback/blob/326f11c8d08d5c1d57a86de22c55e1c31ffc4e18/lib/application.js#L148-L153

Few more notes:
 - It is possible to explicitly specify REST endpoint via `{ http: { '/mypath' } }` in which case the plural name is not used. You should take that into account too.
 - Many existing applications define `user` model extending built-in `User` model, where these models map to `/users` and `/Users` respectively. We should keep this in mind and preserve backwards compatibility.
