### ISSUE TITLE
"after delete" hook of "Through" model runs on /rel/ endpoint even if the relationship doesn't exist anymore

### ISSUE THREAD

**Issue by holisticode** [strongloop/loopback#1886]
Context: a hasMany:Through relationship
ModelA hasMany ModelB through ModelC

Consider this:
PUT /modelA/:id/modelB/rel/:fk
Establishes a new relationship. 

If ModelC has a "after save" hook, it correctly gets triggered only when PUT is executed the first time, in other words when the relationship is established; subsequent PUT calls don't execute the "after save" hook.

But the behavior seems inconsistent with the "after delete" hook, where the hook is called on any 
DELETE /modelA/:id/modelB/rel/:fk 
call, even if the relationship doesn't exist anymore.

Also, contrary to what the documentation states, at least for me the Through's model "after delete" hook doesn't have a ctx.instance when a single instance is being deleted.

**Comment by jannyHou** [comment]
hey @fablife, thanks for your question and I am glad to discuss it here.
I think the `after save` hook in ModelC doesn't work because when you call:
PUT /modelA/:id/modelB/rel/:fk
It updates modelB's properties, not modelC, and since the foreign key can't be changed, then no property in instance of modelC would change, then nothing to save.
In another word, if you define `after save` in ModelB, you will see the update.

I reproduced your concern about `DELETE`. thanks for your suggestion! we will take a look. I will upload an example to explain the problem in a more detailed way later.

**Comment by jannyHou** [comment]
I reproduced the issue of `DELETE /modelA/:id/modelB/rel/:fk ` [here](https://github.com/jannyHou/loopback-sandbox/tree/example/has-many-through)
But I think this problem could be described in a easier way:
First we create a model by `slc loopback:model myModel`, 
add hook as [document](https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-afterdelete) says: 
MyModel.observe('after delete', function(ctx, next) {
  if (ctx.instance){
      console.log('Deleted %s', ctx.instance.id);
  }
  next();
});
(The example code in document doesn't suggest in this way but the note above says "However, when deleting a single model instance the hook receives ctx.instance that contains the instance being deleted.")
Then when we delete an instance from explorer by `DELETE /myModels/{id}`, we cannot get `ctx.instance`, and `ctx.instance` is undefined.
