### ISSUE TITLE
Remote Hook - beforeRemote - upsert not getting triggered

### ISSUE THREAD

**Issue by pktippa** [strongloop/loopback#1955]
As per [Remote Hooks](https://docs.strongloop.com/display/public/LB/Remote+hooks) and [PersistedModel REST API](https://docs.strongloop.com/display/public/LB/PersistedModel+REST+API#PersistedModelRESTAPI-Update/insertinstance) documentation, we can use 'upsert' Remote hook.

I have a mixin 
```javascript
module.exports = function(Model, options){
	Model.beforeRemote('upsert',function(ctx,next){
		console.log('upsert called');
		next();
	});
};
```

but this is not getting triggered when I add a new model instance. Please help.

**Comment by jannyHou** [comment]
hey @pktippa the main problem is that you miss an argument `modelInstance` in your callback function, since `upsert` is an instance method, the syntax should be:
```js
Model.beforeRemote('upsert', function(ctx, modelInstance, next){
       // Your Code
});
```
Please check our [remote hook docs](https://docs.strongloop.com/display/public/LB/Remote+hooks) for more details. In the signature part, it explains the syntax for instance method.

I also created a [repo](https://github.com/jannyHou/loopback-sandbox/tree/testUpsert) to reproduce your issue:

Model `test` has a RemoteHook for `upsert`:
```js
Test.beforeRemote('upsert',function(ctx, modelInstance, next){
        console.log('upsert called');
        next();
});
```

And it works with endpoint `PUT /tests`

**Comment by pktippa** [comment]
hey @jannyHou thanks for the response.
I observed 3 things here.
a. As per API docs [Upsert](https://apidocs.strongloop.com/loopback/#persistedmodel-upsert) goes under static methods but not instance methods.
b. The 'upsert' hook getting triggered when we do a PUT but **not** for **POST** why?
c. The 'upsert' hook **not** getting triggered for PUT/{id}

**Comment by jannyHou** [comment]
hey @pktippa sorry for misguiding you yesterday, `upsert` is a static method not instance, and the point is `upsert` is a build-in method instead of remote method. That's why you will get problem when you use a [remote hook](https://docs.strongloop.com/display/public/LB/Remote+hooks).
So you can either do the trigger with a [Model hook](https://docs.strongloop.com/display/public/LB/Model+hooks) or [Operation hook](https://docs.strongloop.com/display/public/LB/Operation+hooks)

btw, POST matches `create` not `upsert`.

**Comment by richardpringle** [comment]
@pktippa you might have to use the alias `updateOrCreate`. I'm not quite sure why it doesn't work but it should. 

Also, `upsert` was implemented as a static method because of the way prototype methods are called by strong-remoting. Any operation performed on this example endpoint `/api/Examples/{id}/` will first call `findById(...)` and then the remote method you originally wished to call. If you try to call `PUT /api/Examples/{id}/` for a model that doesn't exist, the `findById` call with throw an error before `upsert` is even called.

I think this is a major design flaw and really introduces an inconsistency with the REST endpoints. We are currently working on improving the behavior.

**Comment by richardpringle** [comment]
^ EDIT:
> the findById call with throw an error before **`upsert`** is even called

changed to:

>the findById call with throw an error before **`updateAttributes`** is even called

**Comment by richardpringle** [comment]
@pktippa 
>a. As per API docs Upsert goes under static methods but not instance methods.
b. The 'upsert' hook getting triggered when we do a PUT but not for POST why?
c. The 'upsert' hook not getting triggered for PUT/{id}

a) It is a static method because of my above explanation (the design flaw)
b) The `create` method is mapped to POST and `updateOrCreate` (alias is `upsert`) is mapped to PUT
c) The 'updateAttributes` method is mapped to PUT MyModels/{id}

There are no bugs here, the functionality is as expected, but I agree, it is all rather inconsistent and thus confusing. I believe I created an issue somewhere to improve the design.

**Comment by pktippa** [comment]
@richardpringle Thanks for the explanation.

**Comment by IvanAlegre** [comment]
Is it possible that `updateAttributes` remote hook is not being fired when making a PUT to Test/{id}?

```js
Test.beforeRemote('upsert',function(ctx, modelInstance, next){
        console.log('PUT called');
        next();
});
```

The code from above does not print anything. At the moment i'm doing this:

```js
Test.beforeRemote('**',function(ctx, modelInstance, next){
        if (ctx.method.name === 'updateAttributes') console.log('PUT called');
        next();
});
```

And this works as expected

**Comment by richardpringle** [comment]
@IvanAlegre, I think you need to use `updateAttributes` in place of `upsert`. Have you tried that?

**Comment by IvanAlegre** [comment]
@richardpringle sorry, I had a typo, I have `updateAttributes` in the remote hook

**Comment by richardpringle** [comment]
@IvanAlegre

Can you do me a huge favor and open a new issue in [strong-remoting](https://github.com/strongloop/strong-remoting/issues)?

Mention me in a comment and I will label it as a bug.

**Comment by richardpringle** [comment]
@IvanAlegre... I found the solution!

Instead of just `updateAttributes`, use `prototype.updateAttributes`.

**Comment by IvanAlegre** [comment]
Thank you so much @richardpringle !!

**Comment by pbrain19** [comment]
put works fine but what about patch?

**Comment by clearmirror** [comment]
Model.beforeRemote('prototype.updateAttributes', function(ctx, modelInstance, next){
    console.log(modelInstance);
    next();
  })

The modelInstance is always empty object {}. However ctx.instance is the instance snapshot before the update. What modelInstance is supposed to be?

**Comment by Cerberus** [comment]
`prototype.patchAttributes` for method PATCH
for the others I found it when set _methodname_ to _**_ and console.log context object (ctx)

ModelName.beforeRemote( "**", function( ctx, unused, next) {
    console.log('ctx.methodString', ctx.methodString)
    next();
});

Use the string that append ModelName
(I've tried on LoopBack 3.0)

**Comment by Freundschaft** [comment]
I also always get an empty object for beforeRemote, thats really strange :/

**Comment by shaheero** [comment]
for PATCH aka upsert, you should use '**patchOrCreate**'

e.g.

```
Model.beforeRemote('patchOrCreate', function(ctx, modelInstance, next){
       // Your Code
});
```
