### ISSUE TITLE
Update after query with fields leads to an incorrect update. 

### ISSUE THREAD

**Issue by nkint** [strongloop/loopback#1972]
Hi,
maybe I'm doing it wrong. 
But it seems to me that this sequence of operation is broken:
- query an instance of a model selecting only few parameters via `fields` object to make the query faster
- update the istance 

Please be patient I've tried to paste only a minimum working example, maybe there is something wrong in the code that follow but it is only to try to explain. I'm experiencing this problem in a larger model with a lot of properties and a lot of logic.

I have a Project model: 

```
{
  "properties": {
      "title": {
        "type": "string",
        "required": true
      },
      "type": {
        "type": "string",
      },
      "count": {
        "type": "number",
      }
   }
}
```

With this code:

```
const project = yield app.models.Project.findOne({
  where: { id: theTargetId },
  fields: { type: true }
});

if( project.type === 'foo' ) {
    yield project.updateAttributes({ count: 10 });
}
```

into the update procedure also the title is updated.. and the new value is `undefined`. While I'm expecting in this update the `title` property is not touched at all..

Let me think that in the update all properites present inside the object (loaded via the `fields` parameters in the query before) are update and not only the ones specified into the `updateAttributes` parameter.

I see the new istance field in a **before save** hook:

```
Project.observe('before save', function(ctx, next) {
  P.coroutine(function*(){

    const instance = ctx.instance || ctx.currentInstance;
    const oldInstance = yield app.models.Project.findById(instance.id);
    let changedFields = [];
    for(const key in instance) {
      if( key[0]==='_' || typeof instance[key]==='function' ) continue;
      if( !_.isEqual(oldInstance[key], instance[key]) ) changedFields.push(key);
    }  

    //print changed fields here: also title is changed and new value is undefined
    return next();
  }
}
```

Am I doing it wrong?

**Comment by davidcheung** [comment]
Hi @nkint,  I'm trying to reproduce your issue, may I ask which connector are you using?

**Comment by nkint** [comment]
thanks!

I'm using mongodb

**Comment by davidcheung** [comment]
@nkint  I am facing an issue related but not exactly the same, I am getting an error saying my other required fields are not found. But I can't reproduce where it updated fields where I didn't specify in my updateAttributes

#### Scenario
- query with Filter fields
  - scenario `fields : { id : true, type : true }`, update with that instance `{ comment : "foobar" }`   works
  - scenario `fields : { type : true }`  -> receive `No folder found for id undefined`(no primary key found)
- then using the instance(with less fields) to call updateAttributes causes problems because of lack of data, and lack of awareness of lack of data

#### Problem 
- Instance with no primary key still lets the instance call updateAttributes.
- validation on instance with `some fields` throws error for required fields that was not queried.


@superkhau any idea?

**Comment by bajtos** [comment]
@davidcheung I though it was not possible to create models with no primary key, because then the datasource/connector would inject one. Is thus just a model instance that does not have the primary key set? Perhaps when applying the `fields` filter, we should always include the primary key even if it's not listed in the `fields` array?

@raymondfeng thoughts?
