### ISSUE TITLE
Mixins Operational Hook "after save" is not getting triggered on built in User model POST/PUT end point.

### ISSUE THREAD

**Issue by kalimulhaq** [strongloop/loopback#1973]
I have a Mixin Script in common/mixin/log.js file

``` javascript
module.exports = function (Model, options) {
var app = Model.app;

Model.observe('after save', function (ctx, next) {
    // Log CREATE/UPDATE operations on every model
    next();
});
};
```

this 'after save' hook getting triggered for all of my Custom models in common/models directory but not getting triggered for built-in User model. Although I have Enable User model with my "Log" mixins like

``` json
{
    "name": "User",
    ...
    "mixins": {
        "Log": true
    },
    ...
}
```

I spent a lot of time but i didn't find where it is my code issue or loopback issue??

**Comment by fabien** [comment]
The built-in models are a bit different in this regard, as they don't fully participate in the loopback-boot loading cycle. Please create a file: `server/boot/user.js` and try something like:

```
module.exports = function(app) {                                                              
   var User = app.models.User;
   User.mixin('Log');
};
```

**Comment by kalimulhaq** [comment]
@fabien Thank it work, 
But it should mention in documentation

**Comment by davidcheung** [comment]
@crandmck, is there somewhere that documents behavior differences between build-in models and extended/customized models. 

And for built-in user model maybe we can change the wording from [**Using built-in models**](https://docs.strongloop.com/display/LB/Using+built-in+models) 's user model section. 
> Typically, you'll want to extend the built-in User model with your own model,

to something closer to [**Managing Users**](https://docs.strongloop.com/display/LB/Managing+users#Managingusers-Overview) 
>IMPORTANT
You must create your own custom model (named something other than "User") that extends the built-in User model rather than use the built-in User model directly.  The built-in User model provides a great deal of commonly-used functionality that you can use via your custom model.

any thoughts?

**Comment by crandmck** [comment]
> is there somewhere that documents behavior differences between build-in models and extended/customized models.

We have https://docs.strongloop.com/display/LB/Extending+built-in+models but it doesn't directly address the differences.  LMK if there are specific points you think we should make.

> And for built-in user model maybe we can change the wording ...

I changed https://docs.strongloop.com/display/LB/Using+built-in+models#Usingbuilt-inmodels-Usermodel as you suggested.

**Comment by ank-it** [comment]
The same issue is being faced by me. While trying to add the operational hooks across the models. 'After save' is not being executed. I tried @fabien 's solution but it is not working for the Custom models. 
Have added the mixin file in : common/mixin/send.js and added it to the model-config.json and models as well.

**Comment by JustinTRoss** [comment]
I can only get @fabien 's solution to work if I use the mixin on a custom component in addition to the built-in component. Else, I receive an error that the built-in model is using an unknown mixin.
