### ISSUE TITLE
Inheritance model validation error

### ISSUE THREAD

**Issue by giowe** [strongloop/loopback#1991]
I have 3 models, for example People, Student and Teacher.
Student and Teacher inherites from People.
People model has an "email" property that i want to be unique (but not primary key)
What I expect to do is to put the validation code in People.js as it follows:

```
module.exports = function(People) {
  People.validatesUniquenessOf('email', {message: 'email is not unique'});
};
```
What I got is not what I expected: Student and Teacher won't execute the father validation and I have to repeat the previous code in both child models...

**Comment by loay** [comment]
Hello @giowe 
The issue is already been reported and it is escalated and we are working to fix it as soon as possible. 
However, here is a work around that you can use in the mean time : 

I think the workaround solution is to define the validators from withing `MyModel.setup`. That method is called whenever a model is subclassed, which will cause the validators to be defined again on the new model.

```js
// common/models/parent.js
module.exports = function(Parent) {
  Parent.setup = function() {
    Parent.base.setup.apply(this, arguments);

    Parent.validatesPresenceOf('name');
  };

  // Note that the setup function is not run automatically for the actual model it's defined on
  Parent.setup();
};
```

Please follow this issue for a fix to be released soon:
https://github.com/strongloop/loopback/issues/1485

**Comment by giowe** [comment]
very good, tnx!
