### ISSUE TITLE
property types documentation inconsistency

### ISSUE THREAD

**Issue by giowe** [strongloop/loopback#2002]
I use mysql connector to generate tables from my looback models.
I have a model with a text property I want to be a TEXT type on mysql.
In the loopback types documentation I can see only String type but this will be converted to VARCHAR(512). [https://docs.strongloop.com/display/public/LB/LoopBack+types](url)

In MySQL connector documentation page instead, I can see a table titled "LoopBack to MySQL types" and i can see a "TEXT" type.  [https://docs.strongloop.com/display/public/LB/MySQL+connector](url)
So what? Can I use this TEXT type in my model's props or not? neither in the SLC cli I can see this TEXT type...

**Comment by amenadiel** [comment]
Yes you can use it. However, since it is a trait of MySQL conector, if you ever change the datasource engine there's no guarantee about the outcome.

If you are seriously commited to MySQL that's not an issue. 

Regarding the  documentation there are heaps of  methods and modules missing just because loopback evolves so fast it's challenging to follow. Same goes for slc generators.

**Comment by richardpringle** [comment]
Thanks for answering @amenadiel!

@giowe, are you satisfied with your answer? We're trying to continuously improve our docs as well as LoopBack but it can be a slow process.

**Comment by giowe** [comment]
tnx! very good :)
