### ISSUE TITLE
Lack of explicit code examples in documentation

### ISSUE THREAD

**Issue by TrySpace** [strongloop/loopback#2006]
Let me first say, loopback looks really robust and customizable, so the steep learningcurve is understandable.

However, I've been spending a lot of time just `console.log`ging a lot of objects that are returned from methods in my server console because there is a huge lack of code examples in the documentation at some critical points.

For example at: https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-Helpermethods.1

It mentions helper methods, but nowhere can I find a code example of where these methods are used, like `customer.emails.add()`. I've tried to inspect about all methods i could find with `Object.keys(ctx)` or with `instance` but nowhere can I find these helper methods.

Perhaps it is because my models are not defined right, but I've tried to use example code where they should be defined right, but still nothing.

You can refer to this: https://stackoverflow.com/questions/35081213/strongloop-embedsmany-helper-methods-not-found for my issue with helper methods.

Secondly, there are a lot of embedded code example that don't match up to what the documentation talks about. And also some outdated documentation where the github example code doesn't match up, like: https://docs.strongloop.com/display/public/LB/Tutorial%3A+model+relations talks about `Reviews`, while in the code it has no `Review` model defined.

I see a lot of people complaining about the state of the documentation, and I can't disagree, it is rather messy at points. For example the `Core concepts` page links to `hooks` which directly links to the deprecated `Remote Models` page.

I understand that some changes are hard to track, and keep in sync with documentation, but besides that, at time the docs skip over certain points that might be unimportant to people that already understand how strongloop works, but for newcomers are rather confusing and misses some very imporant things like _when and where_ to use certain methods. And skips for example the file that the code should be in, or when in that file it should be placed.

What this issue is mainly about is lack of in-depth explanation of some of the concepts, and a more consistent set of embedded example code.

**Comment by crandmck** [comment]
@TrySpace  We've tried to include examples as much as possible, and we're always trying to improve the docs.  As you say, LoopBack has a lot of surface area, and is constantly advancing/changing, so it's a challenge to keep the docs in sync, especially as I'm the only writer on the project, and I can spend maybe 1/3 of my time as I have additional projects as well.

> ... For example at: https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-Helpermethods. It mentions helper methods, but nowhere can I find a code example ...

There are examples of calling the "helper methods" from embedded relations in [oopback-example-relations boot scripts](https://github.com/strongloop/loopback-example-relations/blob/master/server/boot/), for example https://github.com/strongloop/loopback-example-relations/blob/master/server/boot/z-customer-emails.js.  I added a link to the doc.  Thanks for bringing it to my attention.

> Secondly, there are a lot of embedded code example that don't match up to what the documentation talks about. And also some outdated documentation where the github example code doesn't match up, like: https://docs.strongloop.com/display/public/LB/Tutorial%3A+model+relations talks about Reviews, while in the code it has no Review model defined.

Recently @superkhau made a bunch of changes to the examples, but in many cases I didn't get an explicit indication of what would affect the docs and I simply haven't had time to comb through all the examples, sort out what changed, and where docs were affected.  I'm trying to bring the docs up to date, but we have a lot of examples and they are closely interwoven with the docs, so it's a challenge as well.  I appreciate being alerted to specific cases.

If you haven't found it already, https://github.com/strongloop/loopback-example links to ALL our LoopBack examples, and you should find it useful.

> ...docs skip over certain points that ... for newcomers are rather confusing and misses some very imporant things like when and where to use certain methods. And skips for example the file that the code should be in, or when in that file it should be placed.

We did make a concerted effort to put the folder/file name in the heading of every code example, but I'm sure we've missed some.  We certainly want the docs to be useful to new users, so please alert us to specific cases.

> What this issue is mainly about is lack of in-depth explanation of some of the concepts, and a more consistent set of embedded example code.

We appreciate the input and we are aware in general of the need to do this.  I'm going to close this issue because I addressed the specific note above, and we welcome additional input where we  can address specific instances.

We used to allow external editing of the docs, but recently had to discontinue that, and haven't determined another way to enable it.  So just continue to report specific issues as you encounter them.  It's fine to lump a bunch of related problems together in a single GH issue--as long as its actionable.

@TrySpace Thanks again for your comments.

**Comment by TrySpace** [comment]
This cleared up a few things, but still the issue of accessing `helper methods` is not clear. 
Sure, the code example uses this, but it's a boot script, and also a method I'm not using.

I'm trying to access it in a `.remoteMethod`, but clearly that doesn't work.

And I also tried it in a `.observe('after save') or `before save`, but still not available, and I also think that method is not suited for it..

**Comment by crandmck** [comment]
@TrySpace I strongly suggest asking on the LoopBack forum/Google Group: https://groups.google.com/forum/#!forum/loopbackjs
You can also try the Gitter channel: https://gitter.im/strongloop/loopback

I personally don't know the answer to your question, and we discourage people from asking "how to" questions in GH issues.  Of course, it can be unclear sometimes if something is a bug or just a matter of not knowing how to do it, so it's understandable not being sure where to post.  But usually starting in those two places is a good idea.  Once you determine that there is a bug or incorrect/lacking docs, then you can post a GH issue with a link (or copy/paste) of the info from forum/Gitter.

**Comment by TrySpace** [comment]
@crandmck Thing is, the docs basically explain "how to" do it, but it just doesn't work like it promises. So that I would call an issue.

I've been on gitter the whole day yesterday trying to get this to work, so I'm starting to suspect this is a bug or misinformation in the docs.

**Comment by crandmck** [comment]
> docs basically explain "how to" do it, but it just doesn't work like it promises

OK,
