### ISSUE TITLE
Add a static web page - Documentation issue

### ISSUE THREAD

**Issue by TrySpace** [strongloop/loopback#2012]
Says `git checkout step3` while it should be `step4` ( https://docs.strongloop.com/display/public/LB/Add+a+static+web+page )

Same issue for https://docs.strongloop.com/display/public/LB/Add+a+custom+Express+route should say `step5`

**Comment by jannyHou** [comment]
hey @crandmck , can you take a look? thanks. I didn't see any step branches in:
https://github.com/strongloop/loopback-getting-started.git

**Comment by crandmck** [comment]
@jannyHou They are not branches, but release tags: https://github.com/strongloop/loopback-getting-started/releases

@TrySpace It's actually correct, because you should be getting the state of the app at the end of the PREVIOUS step.  That is, when you checkout `step3` you should get the app as it stands after completing [Extend your API](https://docs.strongloop.com/display/LB/Extend+your+API).  The idea is to let people jump into the tutorial at any point without having to actually perform all the previous steps.

So I believe the docs are correct.

However @superkhau I think there is a small problem with `step4`.
When I check out that release, it is not reflecting the change made in 
[Change or modify the default root route handler](https://docs.strongloop.com/display/LB/Add+a+static+web+page#Addastaticwebpage-Changeormodifythedefaultrootroutehandler) -- that is, `server/boot/root.js` should be renamed to `server/boot/root.js.disabled` or it could just be deleted (it doesn't matter, since it will work either way, but it might be more obvious if the file is there but just renamed with a non-.js extension).

**Comment by jannyHou** [comment]
A duplidate issue of https://github.com/strongloop/loopback/issues/2010

**Comment by superkhau** [comment]
>However @superkhau I think there is a small problem with step4.

@gunjpan Please fix this as it's probably from the changes we worked on last time.

**Comment by gunjpan** [comment]
@superkhau: Thank you, will do. 
@crandmck : Could you please create an issue for it and assign to me. Thanks.

**Comment by crandmck** [comment]
@jannyHou I think we can close this issue, as I created an issue for the example app as requested.

**Comment by jannyHou** [comment]
thank you @crandmck @superkhau @gunjpan !
I am closing it.
