### ISSUE TITLE
Redifined built-in CRUD method called with wrong arguments

### ISSUE THREAD

**Issue by Nautigsam** [strongloop/loopback#2016]
Hello, I would like to change implementation of built-in CRUD methods to filter results. I followed the instructions [here](https://docs.strongloop.com/display/public/LB/Customizing+models) to define new implementation in Javascript model definition file but I think something is wrong.
I changed the method `count` like this:

```
module.exports = function(MyModel) {
    MyModel.on('dataSourceAttached', function () {
        MyModel.count = function (where, callback) {
            // code
        };
    });
};
```
I took the signature of `count` from the [API doc](https://apidocs.strongloop.com/loopback/#persistedmodel-count). But it seems that the function is called with 3 arguments (filter, options, callback).
While I was debugging, I saw that the method was called from [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L872). So what should I refer to? Is my implementation wrong?

**Comment by richardpringle** [comment]
Hey @Nautigsam, you shouldn't be redefining any built-in methods. We are working on making it a little easier to customize functionality at specific endpoints such as `MyModels/count`, but currently the method registered with that endpoint is the method you found in the *DataSource Juggler* code and you shouldn't try to override it. For now, you can implement your own method as a standard remote method at a different endpoint (`MyModels/counter`, for example).

I am going to close this issue because we are trying to limit GitHub issues to *bugs* and *feature requests*. See [the wiki](https://github.com/strongloop/loopback/wiki/Questions) for details. If you have any new questions, please post them on [the Google Group](https://groups.google.com/forum/#!forum/loopbackjs).

In the meantime, feel free to carry on this discussion here and I will answer you as best I can.

Good luck!

**Comment by Nautigsam** [comment]
Thank you for your answer, that's true that modifying built-in methods is a bit hacky. I can't wait for a better way to customize endpoints. Good luck!
