### ISSUE TITLE
docs: wrong example at referencesMany

### ISSUE THREAD

**Issue by yorkie** [strongloop/loopback#2020]
See https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-ReferencesMany:

```js
"accounts": {
  "type": "referencesMany",
  "model": "Account",
  "property": "accountIds",  // should be `foreignKey`
  "options": {
    "validate": true,
    "forceId": false
  }
}
```

**Comment by jannyHou** [comment]
Thank you @yorkie and yes in relation referencesMany it uses `foreignKey` instead of `property`.

`property` is the name used in embedsOne and embedsMany
But in referencesMany it's called `foreighKey`,
see [`var fk = params.foreignKey || i8n.camelize(modelTo.modelName + '_ids', true);`](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/relation-definition.js#L2851)
and [`keyFrom: fk`](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/relation-definition.js#L2859)

**Comment by yorkie** [comment]
By the way, could we have a way to patch strongloop docs from user-side?

**Comment by crandmck** [comment]
> By the way, could we have a way to patch strongloop docs from user-side?

Unfortunately, this is no longer possible.  Sorry, I wish it were!

**Comment by jannyHou** [comment]
Changed. I am closing it.

**Comment by crandmck** [comment]
Thanks, Janny!
