### ISSUE TITLE
Unable to define polymorphic relations, Could not find "relation" relation for Model

### ISSUE THREAD

**Issue by sahilanguralla** [strongloop/loopback#2051]
I am facing an issue with polymorphic relations. 

```
{
  "name": "Organisation",
...
  "relations": {
...
    "behalfWriteAuthorizations": {
      "type": "hasMany",
      "model": "WriteAuthorization",
      "polymorphic": {
        "as": "authority",
        "foreignKey": "authorityId",
        "discriminator": "authorityType"
      }
    }
...
```

This code raises an error saying

> Could not find "behalfWriteAuthorizations" relation for Organisation

While the same code in another model "Writer", it just works fine

```
{
  "name": "Writer",
...
  "relations": {
...
    "behalfWriteAuthorizations": {
      "type": "hasMany",
      "model": "WriteAuthorization",
      "polymorphic": {
        "as": "authority",
        "foreignKey": "authorityId",
        "discriminator": "authorityType"
      }
    }
...
```

**Comment by jannyHou** [comment]
hey @sahilanguralla I am trying to reproduce your problem, for a better debug, could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace it with your code? Thanks!

**Comment by sahilanguralla** [comment]
Here is the bug reproduced.
https://github.com/sahilanguralla/loopback-sandbox

**Comment by jannyHou** [comment]
hey @sahilanguralla it's quite a wired problem but I think I find out where the problem comes from:

To simplify the issue I change db to default and delete properties in model to just test the relation, you got error due to the sequence of models stored in `server/model-config.json`: 
https://github.com/sahilanguralla/loopback-sandbox/blob/master/server/model-config.json#L43

The error only happens when we define a polymorphic hasMany relation
```
"relations": {
    "myrelation": {
      "type": "hasMany",
      "model": "modelB",
      "polymorphic": "mypolymorphic"
    }
  },
```
in `common/modelA.json`
And modelA is stored after modelB in `server/model-config.json`


- The sequence doesn't affect hasMany
- ModelB could not exist but cannot stored before ModelA

**Comment by sahilanguralla** [comment]
Ya, it works. Actually, I already figured out same. The main concern about reporting the issue was that doesn't sound to be a good thing as far I know about loopback. As it happens in hasMany relations case, sequence of models in model-config.json shouldn't raise any such error for a polymorphic relation too.

**Comment by beaglez** [comment]
I found this occurring with hasOne polymorphic relations also. Seems to be resolved also by naming the relationship the same as the entity being referenced - but using plural if it is hasMany, and using singular if it is a hasOne relationship.

**Comment by jannyHou** [comment]
@beaglez thanks for providing us more details!

**Comment by Noob7** [comment]
:( it worked once but then i tried to include the containing models and it has not worked since even when i reverted back to the same code. While you are at it can you also let me know how to include/populate the include the contained model while querying because polymorphic relation doesnt work with include

**Comment by Noob7** [comment]
spend 3 hours on it for the second time. As i forgot i had the same error a couple months ago :(
