### ISSUE TITLE
How to automatically add the current user to a model on save?

### ISSUE THREAD

**Issue by johannesjo** [strongloop/loopback#2060]
I already asked this on [Stackoverflow](http://stackoverflow.com/questions/35277405/how-to-add-a-user-to-a-model-with-loopback) (with currently a 50 bounty!) and I'm trying really hard to make this work by myself by a using a combination of a middleware and a mixin, but I really wonder what you guys think, would be the best way to do this? 

If there ain't currently a good way to do so, maybe there should be a built in way to do so?

**Comment by richardpringle** [comment]
Hey @johannesjo, have you tried asking on [the Google Group](https://groups.google.com/forum/#!forum/loopbackjs) or [Gitter](https://gitter.im/strongloop/loopback)? 

I would ask in those two places as well but I will also give you my best answer:

I would *extend* the built-in `User` model so that you can create the relation `CustomUser` *hasMany* `MyModel` and POST to `CustomUser/{id}/MyModel`.

I am going to close this issue since it is a question, but feel free to continue the discussion with me on here, just mention me in your response. Also, if the above is not your specific use-case, please describe it in more detail.

Good luck!
