### ISSUE TITLE
How can I Add ACL rules at run time for all model?

### ISSUE THREAD

**Issue by katherdx** [strongloop/loopback#2061]
I am trying to create acl rules at run-time for all models. I have form that contain ACL information Like: 
 `id, 
model name,
property,
accesstype,
principalId, (here I am assign roldId from role table).
PrincipalType`

 

After submit the form, information will be stored in ACL table (DB: mysql). My question is how to get the data from ACL table  in mixin or boot scritpt or any and when will get acl data from acl table and how to assign to all model at runtime.

I am tried in mixin and boot script but I cant get clear idea.

In mixin file, how to get acl data and how to assing to all models..

I am realy confused because I dnt no when will push acl data in runtime for all model(like boot, mixin, operation hook).

Please give any ideas.

I want to like, In mixin or boot script or any.

Get all data from acl and assign to all models.

`In mixin.// I don't know how to get acl data from database in mixin files. 
ACL.find(function(err, data)
{
    var acl = data;
});

// doing some iteration..

 Model.settings.acls.push(data);`

**Comment by richardpringle** [comment]
Hey @katherdx, the best place to ask a question is in our [Google Group](https://groups.google.com/forum/#!forum/loopbackjs). I am going to close this issue since we are reserving GitHub issues for bugs and feature requests, please see [the wiki](https://github.com/strongloop/loopback/wiki) for more details. 

However, I will try to help you out here:
For starters, by default, the ACL model has a datasource of 'db' which is memory. You will have to change that to your specific datasource in the model-config.json

You'll see [here](https://github.com/strongloop/loopback-boot/blob/master/lib/executor.js#L18-L55) that all boot-scripts are run after the models are setup. So I think I can safely say that what you are trying to do is not supported by a boot script.

What you might be able to do however is modify the `server.js` file to populate your config files before **LoopBack-Boot** runs. You can use the [LoopBack API](https://apidocs.strongloop.com/loopback/) to setup your models manually ([see here for more details](https://docs.strongloop.com/display/public/LB/Working+with+LoopBack+objects#WorkingwithLoopBackobjects-Fromacustomscript)).

I know that's a vague answer, but that should at least get you started. Good luck!
