### ISSUE TITLE
embebs many updateById or set do not trigger database update

### ISSUE THREAD

**Issue by mamartins** [strongloop/loopback#2071]
In a embedsMany relation with no "belongsTo" the method parent.item.create triggers a mongo update while the parent.item.set(id, newData), or parent.item.updateById(id, newData) don't.

This methods should also be better documented

**Comment by jannyHou** [comment]
hey @mamartins I am trying to reproduce your issue, could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace with your code? thanks.

**Comment by mamartins** [comment]
sure! on it

**Comment by mamartins** [comment]
here it is:
https://github.com/mamartins/loopback-sandbox

**Comment by jannyHou** [comment]
@mamartins I am so sorry for replying you late, we have a deadline to pass so everything turns slow.

First in loopback we use `updateAttribute` and `updateAttributes` instead of parent.item.set(id, newData) to update data.
Please check [doc for updating data](https://docs.strongloop.com/display/public/LB/Creating%2C+updating%2C+and+deleting+data#Creating,updating,anddeletingdata-Updatingdata%28modelinstances%29) to see more details. And also  how to use [`updateAttribute`](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattribute) & [`updateAttributes`](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattributes)

Second I tried `b.updateAttribute(property, value, cb)` in a relation `a hasMany b`, `b belongsTo a`, the function works fine.
But the same function in relation `a embedsMany b`, `b belongsTo a` fails:
```
create new slot>>> { start: Mon Mar 21 2016 11:28:30 GMT-0400 (Eastern Daylight Time),
  id: 1 }
err>>> No slot found for id 1
```
I will upload my code later to reproduce it, I think it's a bug.
Thanks for your understanding:)

**Comment by mamartins** [comment]
if the relation is a one to many same happens

**Comment by JonnyBGod** [comment]
Any update on this. It seems like I am experience this bug.

Nothin works when trying to update a ```b``` in ```a embedsMany b```. Tried all possible methods, ```set```, ```updateById```, ```updateAttribute```, ```updateAttributes```, ```updateAll```.

The methods are not triggered, just hangs in there...

**Comment by JonnyBGod** [comment]
Test case: https://github.com/JonnyBGod/loopback-multi-emails-and-phones-mixin/tree/setPrimary
just ```npm i && npm test```

**Comment by JonnyBGod** [comment]
Relevant starting point https://github.com/JonnyBGod/loopback-multi-emails-and-phones-mixin/blob/setPrimary/multi-emails-and-phones.js#L620-L667

**Comment by JonnyBGod** [comment]
Found the problem. Not a bug at least in my use case.

The problem was a bug in my embedded model ```before save``` observer where ```next()``` was not being triggered.

**Comment by mamartins** [comment]
more than one year and this is still a bug?

**Comment by tqtran7** [comment]
And another year later, it is still a bug... I am having the exact same issue. Can not update an embedded model via set.

**Comment by tqtran7** [comment]
If anyone is attempting to use promises with this, it will not work. As soon as I switched it to the callback version, it worked.

**Comment by theblackcat102** [comment]
Will promise be ever supported to updateById?

**Comment by nahue086** [comment]
> If anyone is attempting to use promises with this, it will not work. As soon as I switched it to the callback version, it worked.

Experimenting the same issue here. Using the callback approach does work as expected.
