### ISSUE TITLE
Set property type as simple object

### ISSUE THREAD

**Issue by Nautigsam** [strongloop/loopback#2078]
Unless I'm wrong, it seems that for a model property of type "object", Loopback creates a Model instance in the setter. What if we want the data to be stored as a simple object and not as a model? That would be great to specify a new type "model" if we want to keep the current behaviour, and use the "object" type for simple JavaScript Object.

**Comment by davidcheung** [comment]
Hi @Nautigsam, in order to get the simple object, you might have to do `modelInstance.__data`, I believe for `data-source-juggler` (the connection piece that interfaces the database) to work it would need to be in the Model instance format, I believe currently there it is always a `modelConstructor`.
