### ISSUE TITLE
404 link in `Connecting to MySQL ` example

### ISSUE THREAD

**Issue by arkadiytehgraet** [strongloop/loopback#2079]
The title says it all: there is a [missing link](https://github.com/strongloop/loopback-example-mysql) on the [Connecting to MySQL](https://docs.strongloop.com/display/public/LB/Connecting+to+MySQL)  page, which produces rendering error.

**Comment by gunjpan** [comment]
@crandmck : hi Rand, could you PTAL, link is missing. thanks.

**Comment by crandmck** [comment]
This happened due to @superkhau combining the db examples back into the single https://github.com/strongloop/loopback-example-database repo but on different branches.

Thanks for catching!

Fixed, along with 
- https://docs.strongloop.com/display/LB/Connecting+to+Oracle
- https://docs.strongloop.com/display/LB/Connecting+to+MongoDB
- https://docs.strongloop.com/display/LB/Connecting+to+Microsoft+SQL+Server
- https://docs.strongloop.com/display/LB/Connecting+to+PostgreSQL
