### ISSUE TITLE
regexp where filter truncates first character of regex string when flags are passed

### ISSUE THREAD

**Issue by timgit** [strongloop/loopback#2098]
I think I may have found a minor docs issue in the [loopback where filter docs](https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Whereclauseforqueries) when using the regexp operator as a string with flags. The logic in question is datasource juggler's utils.js in `toRegExp()`.  In particular, I'm referencing the behavior in the following code.

```
  // strip regex delimiter forward slashes
  var expression = regex.substr(1, regex.lastIndexOf('/') - 1);
```

The code path is reached if `hasRegExpFlags()` returns true, and it strips the first character off.  There is currently only 1 example on this docs page that shows a regexp being used as a string with flags:

```
/api/cars?filter[where][make][regexp]=^t/i
```

I believe this should not actually work since the `^` would be removed by this code just find the letter t anywhere.  In my testing, the correct expression should be:

```
/api/cars?filter[where][make][regexp]=/^t/i
```

I've adjusted my usages of regexp to make sure I always pass the first slash when using flags.

**Comment by Amir-61** [comment]
Hi @timgit ,

I just created [a sample repo](https://github.com/Amir-61/2098) to reproduce the issue; in my sample repo I'm using a file based approach so you can some prepopulated data as well; when you clone the repo and start the server it seems both of the following endpoints work fine:

`http://localhost:3000/api/cars?filter[where][name][regexp]=^n/i` return all cars whose names start with lowercase `n` or uppercase 'N'

and `http://localhost:3000/api/cars?filter[where][name][regexp]=^n` returns just cars whose names start with lowercase `n`.

So I don't see any issue neither with the expected behaviour nor documentation. If you see any issue please try to reproduce it in our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox).

Thanks.

If this answers your question please let me know and I will close this issue :-)

**Comment by timgit** [comment]
@Amir-61, thanks so much for creating the repo.  I've confirmed my initial issue using this repo.

`http://localhost:3000/api/cars?filter[where][name][regexp]=^a/i` returns all cars with letter a, not cars that start with the letter a.

**Comment by Amir-61** [comment]
Oh Sorry I forgot to get back to this ticket; you are absolutely right, I will label it as a document issue and it will be fixed soon; thanks a lot for helping us improve the documentation.

**Comment by Amir-61** [comment]
@crandmck PTAL ^ Thanks :-)

**Comment by crandmck** [comment]
OK, I tried this out myself, and just to be clear, you only need the leading `/` when you are using a flag.  Without a flag, you don't need the leading slash.....
That's what I observed. I think the OP said that, but I just want to confirm.

**Comment by crandmck** [comment]
This was added to http://loopback.io/doc/en/lb2/Where-filter.html#regular-expressions, so closing.
