### ISSUE TITLE
Relation not appeared on extended User Model

### ISSUE THREAD

**Issue by raabbajam** [strongloop/loopback#2110]
I have a custom model extended from built-in `User` model named `Customer`.
The `Customer` model has `hasMany` relation with `BankAccount` model.

```json
// common/models/customer.json
{
  "name": "Customer",
  "base": "User",
  "relations": {
    "bankAccounts": {
      "type": "hasMany",
      "model": "BankAccount",
      "foreignKey": ""
    }
  }
}
```
I want to use `nestRemoting` as stated [here](https://docs.strongloop.com/display/public/LB/Nested+queries).

```js
// common/models/customer.js
module.exports = function(Customer) {
  Customer.on('attached', function() {
    Customer.nestRemoting('bankAccounts');
  });
}
```
I get error stating that `Customer` model doesn't have relation named `bankAccount`.

```
Error: Relation `bankAccounts` does not exist for model `Customer`
```

I do a little debugging
```js
// common/models/customer.js
module.exports = function(Customer) {
  Customer.on('attached', function() {
    console.log(Object.keys(Customer.relations)); // stdout: [ 'accessTokens' ]
  });
}
```
The stdout is `[ 'accessTokens' ]`. It only showed accessToken as relations. It can't find other relations.
When I try with other custom model with persisted model as base, it works as expected.
```
console.log(Object.keys(BankAccount.relations)); //[ 'customer', 'bank' ]
```
Expected: Customer model to has relations
Actual: Customer model only has accessToken relation

Can someone confirm where do I go wrong?

**Comment by richardpringle** [comment]
Hey @raabbajam, the easiest way for me to help you is for you to fork [the LoopBack sandbox](https://github.com/strongloop/loopback-sandbox) and re-create the issue you are having there.

I'm not sure what has gone wrong in your case but this definitely isn't a bug as I have managed to obtain the desired result. 

I am going to close the issue since we are reserving GitHub issues for bugs and feature requests (not questions), but feel free to fork the sandbox and post a link in here. If you mention me in the comment, I will go have a look and see if I can help you out.

Deal?

Good luck!

**Comment by raabbajam** [comment]
Sounds good. :tea:

**Comment by raabbajam** [comment]
[Recreated the issue here](https://github.com/raabbajam/loopback-sandbox).
All I do is create Customer and BankAccount models, and the `hasMany` - `belongsTo` relation. 
The issue still appeared. 
Is there any chance this is only my system's specific error?
```
// on common/model/customer.js
console.log('Customer.relations:', Object.keys(Customer.relations));
```
Here is what appeared in terminal:
```bash
starting `node server/server.js`
Customer.relations: [ 'accessTokens' ]
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
```

My system:
```bash
Additional information:

❯ node -v
v4.2.2

❯ which node
/home/raabbajam/.nvm/versions/node/v4.2.2/bin/node

❯ npm ls iron-node -g
/home/raabbajam/.nvm/versions/node/v4.2.2/lib
└── iron-node@2.2.15

❯ lsb_release -a  
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty

❯ uname -a  
Linux kat 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64 x86_6
```

Thank you.

**Comment by richardpringle** [comment]
Hey @raabbajam, `nestRemoting('...')` is only relevant to multiple nested relations another layer deep as stated in the docs: `/api/books/123/pages/456/notes`. 

So you should be able to see `Customer/{id}/BankAccounts`. The reason that your `console.log` doesn't display `'bankAccounts'` is because `on('attached', ...)` is firing before the app is finished booting. Try putting the same log in a boot script, you will see that the relation is there. 

Just a warning, you will want to read [the ACL info on related models](https://docs.strongloop.com/display/public/LB/Accessing+related+models) before using relations with an extended User model (`Customer` in your case). 

Hope that helps!

**Comment by raabbajam** [comment]
@richardpringle. Aah, I see. True enough, when I put it on boot script, it does show `bankAccounts` relation.

Yes, I do want to use nested relations e.g. `Customers/1/bankAccounts/1/transactions/`. I have set up the ACL for one level relation model, and will look up how to create ACL for two level if the `nestRemoting` works.

So to use `nestRemoting`, do I have to put the code in the boot script? Or is there any other event I could listened to to wait for BankAccount relation ready, as App object booted?

Cheers :tea:

**Comment by raabbajam** [comment]
In the end, I use this code to keep remote nesting in Model script.
The `Customer.app` will be ready when model emits `attached` event. But at this point, app still not fully booted. So I let app listen to `started` event that will be emitted when all models / boots script processed.

As for why `Customer.relations` only has `[AccessToken]` I figured this is because the loopback-boot attaching models alphabetically (randomly?), which is why when `Customer` attached, the `BankAccount` has not processed by loopback-boot. Weird...

```js
// file common/models/customer.js

export default function CustomerConstructor(Customer) {
  registerNestRemoting(Customer);
  return Customer;
}

function registerNestRemoting(Customer) {
  Customer.on('attached', () => {
    Customer.app.on('started', () => {
      debug('Customer has nestRemoting > bankAccounts');
      Customer.nestRemoting('bankAccounts');
    });
  });
}
```

Cheers :tea:

**Comment by richardpringle** [comment]
@raabbajam, did you get `Customers/1/bankAccounts/1/transactions/` to work?
