### ISSUE TITLE
The name attribute on the "Role" model should be unique

### ISSUE THREAD

**Issue by javefang** [strongloop/loopback#2111]
For now I can create many Role instances with the same name. But since roles are referenced by name in the ACLs of the model JSON definition files. It doesn't make sense to allow creating roles with the same name.

Looking at the example https://docs.strongloop.com/display/public/LB/Creating+a+default+admin+user, If I run the code example `/server/boot/script.js` every time API starts, it's going to create a new role with name "admin" (but different id) every time.

Plus, the implementation for `Role.isInRole()` (https://github.com/strongloop/loopback/blob/master/common/models/role.js#L325), seems dangerous to use `findOne` to look up role by name without adding uniqueness constraint on the `name` attribute in the first place.

**Comment by javefang** [comment]
@richardpringle apologize if I am wrong, but shouldn't this issue be considered as a bug? surely if can create two roles with the same name and break correct behavior when referencing the role in ACL?

**Comment by richardpringle** [comment]
@javefang, absolutely no need to apologize! I would say this is a feature simply because of the implementation. It is assumed that the developer would not create multiple *roles* with the same name. I can't imagine any scenario where one would do so (by accident or not). However, I agree that it could be a good idea to implement the Role Class is such a way that naming is enforced instead of assumed.

The behavior is as expected and therefore it is not a bug. It could however be improved, and thus a feature! Make sense? In any case, it's a matter of semantics.

@raymondfeng, do you have any thoughts here?

@javefang, if you would like to see this feature implemented right away, the best thing to do would be to make the change yourself! [Here's a link for instructions on code contribution](https://github.com/strongloop/loopback/wiki/Contributing-code) if you haven't done so before. If you do choose to open a PR, mention me in a comment and I will make sure that it gets reviewed as soon as possible.

**Comment by supasate** [comment]
Hi @richardpringle @raymondfeng @javefang, let's me take this feature.
