### ISSUE TITLE
Query for extracting info from one table based on other in strongloop

### ISSUE THREAD

**Issue by katherdx** [strongloop/loopback#2133]
I have two tables post and share, post has many share. I want to fetch all data in post table using userId(posted by owner user) and also check share table using same userid that is if some one shared post to other user, if any condition is true, I need to fetch data.

I want to fetch data in post table if posted by owner or shared by other user in share table.

Example :

**table name: post**

```
id(pk) postname userid
    1  abc       10
    2  xxx       10
    3  yyy       11
    4  zzz       12
    5  bbb       13 
```

**table name:share**

```
id postid(fk) userid
1   3           10
2   4           10
3   3           11
4   1           12
```

**Expected output: example find by userid 10**

```
 id postname userid
  1  abc       10  // this record created by user 10 (owner)
  2  xxx       10  // this record created by user 10 (owner)
  3  yyy       11  // this record shared by other user to user 10.
  4  zzz       12  // this record shared by other user to user 10.
```

**model relationship:post.json**

```
 "relations": {
    "shares": {
      "type": "hasMany",
      "model": "share",
      "foreignKey": "postid"
    }
  }
```

> I tried following queries but I am getting error

```
{
  "where": {
    "or": [
      {
        "userid": 10
      },
      {
        "include": {
          "relation": "shares",
          "scope": {
            "where": {
              "userid": 10
            }
          }
        }
      }
    ]
  }
}
```

> and // here I just checking postname also but no need for this question.

```
{
  "where": {
    "or": [
      {
        "userid": 10
      },
      {
        "postname": "xxx"
      }
    ],
    "include": {
      "relation": "shares",
      "scope": {
        "where": {
          "userid": 10
        }
      }
    }
  }

}
```

**Comment by katherdx** [comment]
my repo  https://github.com/katherdx/postshare

**Comment by richardpringle** [comment]
Hey @katherdx, you're actually not going to be able to do what you want with a single query.
Here are some docs on the [where filter](https://docs.strongloop.com/display/public/LB/Where+filter).

Forgive me if I am oversimplifying this explanation, but I hope it helps:
When you query with `where` using the `or` operator, you are doing this with *key-value* pairs. 
```json
{
  "where": 
    {
      "or": 
        [{"myProperty": "value1"}, {"myProperty": "value2"}]
    }
}
``` 
In your case, instead of a *property*, you tried to use another filter. 

And just to make things a little more difficult, you actually can't query `posts` based on properties in the related model.

Ideally, you would do the following:
  - create a `belongsTo` relation between `share` and `post`
  - create a static remoteMethod in the `post` class
  - (preferably using async) query both models
```node
Post.find({where: {userId: 10}}, function(err, instances) {...});
Post.app.models.Share.find({where: {userId: 10}, include: 'post'}, function(err, instances) {
  instances.forEach(function(element) {
    // You only want to return posts
    element = element.__data.post;
  });
  // you still need to save the instances data or pass it to an async callback
})
```
  - concatenate the `post` instance arrays
  - and finally send in the remoteMethod callback.

If you are set on getting that data from the endpoint `GET /Posts` there is another way... but it's ugly.
  - create a middleware function that runs in the 'routes:before` phase
    - create this function within the `post.js file`
  - within the handler function, grab a custom filter (with a custom name) from the `req.query.filter` string
  - set a flag such as `customFilter` 
  - query the shares model and pull out the `post` objects
  - check your flag in the callback of `afterRemote('find', ...)` 
  - If the flag is set, concatenate the data and set `ctx.result = concatenatedData`
  - call `next()` and you should be good to go

I tried the second method, it was a pain and I do not recommend it. Only use this if you can't hit a different remote method that you created. I also haven't given any code example for the second solution on purpose. I advise that if you must perform the workaround this way, you learn how to implement it yourself.

I hope this helps!

**Comment by katherdx** [comment]
@richardpringle  Thanks for your response. I will try both ways if any doubt I will ask to you.

**Comment by katherdx** [comment]
@richardpringle  I tried in remote method using  2 find (), then concatenate both data. is it good way ? in this scenario I need to apply same query to 2 find () method. that is I am filtering post table. my original post table has many column.

What Facebook doing for listing all the post to individual user (posted by me and shared by someone)?

**Comment by richardpringle** [comment]
@katherdx, it's definitely not ideal. Unfortunately, that's the only way you can do it with supported loopback features. You can also execute [native sql](https://docs.strongloop.com/display/public/LB/Executing+native+SQL) but the feature is not officially supported.
