### ISSUE TITLE
Unable to retrieve path param using source: path in remotemethod

### ISSUE THREAD

**Issue by emmlopez** [strongloop/loopback#2136]
I want to create an endpoint  /users/username/{id} but  I have not found a solution for  using a path param.{id}, when I tested on the explorer , it doesnt create the request Url with id, it is just 
http://localhost:3000/api/people/username

and it shows error
{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "nbkid is a required arg",
    "statusCode": 400,
    "stack": "Error: nbkid is a required arg\n    at new badArgumentError 
...
}

I created a 'Person' model  extends from Model

module.exports = function(Person) {
    Person.username = function(myid,cb) {
        console.log("myid"+myid);
        var response = "username is 1";
        cb(null, response);
        
    };
    
    Person.remoteMethod(
        'username', {
            accepts: {
                arg: 'myid',
                type: 'any',
                description: 'myid',
                required: true,
                http: { source: 'path'         }
            },
            returns: {
                arg: 'username',
                type: 'string'
            },
            http: {
                path: '/username',
                verb: 'get'
            }
        }
    );
};

**Comment by richardpringle** [comment]
Hey @emmlopez, in the future, could you please post any questions to one of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We are trying to reserve the issues section on GitHub for bugs and feature requestions only (just to make things a little more manageable). Thanks for your understanding!

However, since you have posted here, I may as well try to help you out. I will close the issue and label it as a `question` but feel free to continue to comment in here to get my response, just make sure you mention me directly. If you want help from the rest of the community, just check out one (or more) of the links above.

It looks to me like you are missing one little *thing* in the path declaration:
```node
http: {
  path: '/username/:myid',
  verb: 'get'
}
``` 
I hope that helps! If you're looking for some more documentation on remote methods, you can find it [**here**](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Options).

Also, checkout the [sharedMethod Class in the API docs](https://apidocs.strongloop.com/strong-remoting/#sharedmethod). A new `sharedMethod` is being constructed when you call `Person.remoteMethod(...)`

Good luck, and happy coding!

**Comment by emmlopez** [comment]
thanks @richardpringle for the prompt response and yes that helped, it is working now. I could not see an example that showed me how in the remote methods sections. 

I will start using the links you mentioned as I started working with loopback and have questions about:
1) environment configuration (how documentation describes it does not work for me https://docs.strongloop.com/display/public/LB/Environment-specific+configuration#Environment-specificconfiguration-DisablingAPIExplorer)

2) how to unit test

**Comment by richardpringle** [comment]
You should ask both of those questions on one of our community pages. I haven't seen too many issues with changing environments.

As for testing, that is really up to you. I have seen a few people using [supertest](https://github.com/visionmedia/supertest) but realistically, it shouldn't be any different than unit testing in any framework. All of the loopback code is visible on GitHub so you can take a look at some of [our own tests](https://github.com/strongloop/loopback/blob/master/test/rest.middleware.test.js). Again, this is something that you are going to want to ask in the community to see what other people are doing and what their experience has been like.
