### ISSUE TITLE
Another nested relationship question (sorry)

### ISSUE THREAD

**Issue by hq-mobile** [strongloop/loopback#2137]
Hey,

See a lot of people struggling with nested relationships, and a lot of answers. But I just cannot get the feature to work in the way that I (mis)understand it to work.  This feels like such a fundamental feature to me that a super simple example of it working would be great! Maybe I have missed that?

Conceptually my model is like this:
A Freelancer has one FreelancerBusiness (a type of business) and a FreelancerBusiness has one BankAccount, the relevant endpoints I can get to work are:

GET /freelancers/:id
POST /freelancers
PUT /freelancers/:id

GET /freelancers/:id/business
POST /freelancers/:id/business
PUT /freelancers/:id/business

However the next level proves elusive:
GET /freelancers/:id/business/bank_account
POST /freelancers/:id/business/bank_account
PUT /freelancers/:id/business/bank_account

My setup is like so:
freelancer,json:

``` json{
  "name": "Freelancer",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "business": {
      "type": "hasOne",
      "model": "FreelancersBusiness"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

business.json

``` json
{
  "name": "Business",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "registration_number": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "required": true
    },
    "address_line_1": {
      "type": "string"
    },
    "address_line_2": {
      "type": "string"
    },
    "town": {
      "type": "string"
    },
    "county": {
      "type": "string"
    },
    "country": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

freelancers-business.json

``` json
{
  "name": "FreelancersBusiness",
  "base": "Business",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "documents_folder": {
      "type": "string",
      "required": false
    },
    "shared_link": {
      "type": "string",
      "required": false
    }
  },
  "hidden": [
    "documents_folder"
  ],
  "validations": [],
  "relations": {
    "freelancer": {
      "type": "belongsTo",
      "model": "Freelancer"
    },
    "bank_account": {
      "type": "hasOne",
      "model": "BankAccount"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

bank-account.json

``` json
{
  "name": "BankAccount",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "account_number": {
      "type": "string",
      "required": true
    },
    "sort_code": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "business": {
      "type": "belongsTo",
      "model": "FreelancersBusiness"
    }
  },
  "acls": [],
  "methods": {}
}
```

On top of that I have a js file in server/boot with the following contents:

``` node
module.exports = function(app) {
  app.models.FreelancersBusiness.nestRemoting('bank_account');
};
```

and have also tried:

``` node
module.exports = function(app) {
  app.models.Freelancer.nestRemoting('business');
  app.models.FreelancersBusiness.nestRemoting('bank_account');
};
```

However when I make a request such as POST /freelancers/1/business/bank_account 

``` json
{
  "account_number" : "12345678",
  "sort_code" : "11-22-33"
}
```

I receive the error:

``` shell
404 Resource Not Found: {"error":{"name":"Error","status":404,"message":"Shared class \"Freelancer\" has no method handling POST /1/business/bank_account","statusCode":404,"stack":"Error: Shared class \"Freelancer\" has no method handling POST /1/business/bank_account\n    at restRemoteMethodNotFound (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:330:17)\n    at Layer.handle [as handle_request] (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)\n    at /Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)\n    at next (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)\n    at Function.handle (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/index.js:176:3)\n    at router (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/index.js:46:12)\n    at Layer.handle [as handle_request] (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/Dan/companies/arthur/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)"}}
```

It feels like I am probably missing something super simple here?

Thanks
Dan

**Comment by richardpringle** [comment]
Hey @hq-mobile, I need you to set up [a sandbox](github.com/strongloop/loopback-sandbox) so I can take a look at the structure of your application. 

I will help you from there

**Comment by richardpringle** [comment]
I also suggest removing all ACLs while you're trying to get this to work, but it's not necessary. 

Also, try `nestRemoting('BankAccount')`. I believe that the function is looking for the model to nest the remoting metadata, not the relation name. Again, I can take a deeper dive once you set up a sandbox.

**Comment by hq-mobile** [comment]
Hey,

When using `nestRemoting('BankAccount')` I get the error `Error: Relation `BankAccount` does not exist for model `Business`` so I am not sure it is looking for the model name as it works fine when I use 'bank_account'.

I have set up a sandbox now at https://github.com/hq-mobile/loopback-sandbox that shows the outline of the nested relationships.

When setting up accounts I can get the following to work:
POST /freelancers
POST /freelancers/:freelancer_id/business

I get a 404 when I try to access POST /freelancers/:freelancer_id/business/bank_account with the message: `Shared class \"Freelancer\" has no method handling POST /1/business/bank_account`

I also get a 404 when I try to access POST /freelancers/:freelancer_id/business/:business_id/bank_account with the message: `Shared class \"Freelancer\" has no method handling POST /1/business/1/bank_account`

Thanks
Dan

**Comment by richardpringle** [comment]
Thanks @hq-mobile, taking a look.

**Comment by hq-mobile** [comment]
Awesomoo!

**Comment by hq-mobile** [comment]
Just thought I'd add the result of some investigating to this (with the caveat that I have not spent long looking at the framework).

When I attempt to add bank_account using nestRemoting the create method does not appear to get added to the endpoints due to isStatic being true:

model.js
`
      727 sharedToClass.methods().forEach(function(method) {
      728 var methodName;
      729  if (!method.isStatic && (methodName = filter(method, relation))) {
      ...         // Code here appears to build up the methods on the parent model.
`

I may be completely misunderstanding the code, but just thought I would add my current findings here.

**Comment by richardpringle** [comment]
@hq-mobile, you are correct... I am still trying to investigate why though. This definitely is not as simple as it should be.

**Comment by hq-mobile** [comment]
Great - if there is anything you need me to try just drop me a message. It is pretty late here so I will pick it up in the morning. Thanks!

**Comment by hq-mobile** [comment]
I'll also begin to look at why the Freelancer -> Business creation works but this doesn't in the morning if you haven't managed to crack it before then.

**Comment by richardpringle** [comment]
Hey @hq-mobile (Dan), I cracked the case! To be completely honest, I didn't actually understand what `nestRemoting` was doing, I only knew the expexted output. After a bit of a deeper dive, I've figured it out. To me, it's not completely intuitive how to use this so what I will do is throw a `Doc` label on this issue so that we can improve the documentation.

@crandmck, could we include the following explanation in the docs? (We might have to work on my wording...) and realistically, a diagram or two would be nice as well.

When you define a relation in `ModelA.json` (ModelA -> relation -> ModelB), LoopBack automatically creates a set of "relation methods" corresponding to the API routes defined for the relationship and attaches them to ModelA. When you hit the api endpoint `/PluralModelA/:id/ModelBRelationName`, you are actually calling the remote method `__get__modelBRelationName` from ModelA's sharedClass. The remote method actually maps to a *ModelA prototype function*. For a complete list of all the "relation remote methods", see [this page](https://docs.strongloop.com/display/public/LB/Accessing+related+models).

The relation object in the `.json` model definition file will also define a *foreign key* for the relation, which becomes a property of the *child-model*. So @hq-mobile, in your case, you do not need the "belongsTo" relations as you do not need the "*belongsTo* remote methods", the same *foreign key* has already been created with the *hasOne* relationship. 

Now we can describe what the `nestRemoting` function does and why we need it. Let's say we have three models related as follows: 
```
ModelA -> relationX -> ModelB -> relationY -> ModelC
```
From my above statements, we can conclude that *ModelA* has a set of *relationX remote methods* for performing operations on *ModelB*. *ModelB* has a set of *relationY remote methods* for performing operations on *ModelC*. The *relationX* methods map to *ModelA prototype functions* and the *relationY* methods map to *ModelB prototype functions*. To operate on *ModelC* from an instance of *ModelA* we need to *nest* the *remoting metadata* of *ModelB* within *ModelA*. More simply put, *ModelA* needs those *relationY remote methods* contained in the remoting metadata of *ModelB*. 

It's not intuitive, and thus difficult to explain. 

@hq-mobile, to get the functionality you were looking for you need to do TWO things:
 1. `app.models.Freelancer.nestRemoting('business') // instead of Business.nestRemoting('bank...')
 2. Change the relation name for `bank_account`. The regular expression that looks for the *relation remote methods* will not match with relations containing an underscore.

I apologise for the long winded answer, but I hope that it will makes things easier in the future. Let me know if my solutions works too.

Good luck and happy coding!

**Comment by richardpringle** [comment]
>When I attempt to add bank_account using nestRemoting the create method does not appear to get added to the endpoints due to isStatic being true:

Update: this is incorrect. All of the *relation remote methods* are instance methods:
```
GET  PluralModelA/ModelBRelationName // static method of ModelA - will not work
```
```
GET  PluralModelA/{id}/ModelBRelationName // instance method of ModelA - will work!
```

**Comment by hq-mobile** [comment]
You sir, are a gentleman and a scholar!!!  

At one point I was calling nestRelation on the Freelancer object with 'business' as part of a try anything approach but it appears the pesky underscore put paid to any chance of fluking it.

Agree it needs some further documentation, as a nice to have (and I understand this might be technically challenging) something as fundamental as a modelling the graph of model objects feels like it should be a "it just works" feature when I generate my models and relations.  

Anyways that's a nice to have, thank you so much for all your time looking into and explaining this!!!

**Comment by crandmck** [comment]
I think this is worth keeping open.

**Comment by yuyudhan** [comment]
I had a query, how do you access the object of the immediate parent in case of nested queries in beforeRemote method.

The ctx object in the nested scenario contains the Main parent.

For example in my case the nested related models 

Manager.beforeRemote("*.__create__onboardings__morphons", function(ctx, instance, next) {
})

ctx.instance contains the values of the manager to whom an onboarding belogs to. How do I access the onboarding to which the morphon belongs to.

**Comment by jsylvester89** [comment]
How do we achieve the nestRemoting in Loopback4?
ModelA -> relationX -> ModelB -> relationY -> ModelC

**Comment by richardpringle** [comment]
@jsylvester89, I think you want to post this in the [loopback-next repo](https://github.com/strongloop/loopback-next/issues)
