### ISSUE TITLE
Custom Remote Methods do not work when a path is used

### ISSUE THREAD

**Issue by devotox** [strongloop/loopback#2146]
```
module.exports = function(Language) {
	'use strict';

	Language.uri_id = function(uri_id, cb) {
		console.log(uri_id, 'here');
		Language.findOne({where: {uri_id: uri_id || ''}}, function(err, modelInstance) {
	        cb(null, modelInstance);
	    });
	}
	Language.remoteMethod('uri_id', {
		http: { path: '/:uri_id', verb: 'get' },
	    accepts: {arg: 'uri_id', type: 'string', http: { source: 'path' } },
		returns: { arg: 'data', type: 'language', root:true }
	});

};
```

First it does not try and run my Language.uri_id function and then it also returns this from my database

```
database_1        | ERROR:  invalid input syntax for uuid: "{uri_id}"
database_1        | STATEMENT:  SELECT "id","uri_id","locale","label","description","image" FROM "public"."language" WHERE "id"=$1 ORDER BY "id" LIMIT 1
```

**Comment by gunjpan** [comment]
@devotox : Hi, few things regarding the code above:
first of all:
> `returns: { arg: 'data', type: 'language', root:true }` 

should be changed to:
`returns: { arg: 'data', type: 'Language', root:true }` 
considering that the model is named `Language` and it's identified as one of types allowed in LB, otherwise you should get a warning like: 
`Swagger: skipping unknown type "language".`

Re:
 > First it does not try and run my Language.uri_id function

It is happening because your resulting `Request URL` for remote method is: 
` "http://localhost:3000/api/Languages/{uri_id}" ` which is the same as end point: `api/Languages/{id}` and thus gets handled by the second point for `GET` request. 

Remote methods can take `path` format as follows:
`/apiroot/modelname/remoteMethod` or /`apiroot/modelName/:param/remoteMethod`
Thus, changing the code as follows should work:
```
 module.exports = function(Language) {
  Language.uri_id = function(uri_id, cb) {
    console.log('here' ,uri_id);
    Language.findOne({ where: { id: uri_id } }, function(err, modelInstance) {
      cb(null, modelInstance);
    });
  };

  Language.remoteMethod('uri_id', {
    http: { path: '/:uri_id/customMethod', verb: 'get' },
    accepts: { arg: 'uri_id', type: 'string', http: { source: 'path' } },
    returns: { arg: 'data', type: 'Language', root: true }
  });
};

```
or
can be changed to access at model level as:
```
...
Language.remoteMethod('uri_id', {
    http: { path: '/customMethod', verb: 'get' },
    accepts: { arg: 'uri_id', type: 'string', http: { source: 'query' } },
    returns: { arg: 'data', type: 'Language', root: true }
  });
};
```

Hope that helps.

**Comment by devotox** [comment]
Thank you for the help.

what I managed to do so I could still use the path following your process was and this worked exactly as i hoped. 

```
	Language.uri_id = function(uri_id, cb) {
		Language.findOne({where: {uri_id: uri_id || ''}}, function(err, instance) {
			if(err) { return cb(err); }
			else{ cb(null, instance); }
		});
	};

	Language.remoteMethod('uri_id', {
		http: { path: '/uri/:uri_id', verb: 'get' },
		accepts: {arg: 'uri_id', type: 'string', http: { source: 'path' } },
		returns: { type: 'Language', root: true }
	});
```
