### ISSUE TITLE
slc debug is not working

### ISSUE THREAD

**Issue by dineshi2it** [strongloop/loopback#2152]
```
dinesh@i2i:~/projects/todo(feature/save-individual-list)$ slc debug node .
Node Inspector is now available from http://localhost:8080/debug?port=5858
Debugging `node`

Debugger listening on port 5858
/usr/local/bin/node:1
(function (exports, require, module, __filename, __dirname) { ELF
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.runMain [as _onTimeout] (module.js:447:10)
    at Timer.listOnTimeout (timers.js:92:15)

```
Am I giving wrong cmd or something is wrong with node-inspector ?

Also I have tried the following but the app is not running
```
dinesh@i2i:~/projects/pipecandy(feature/save-individual-list)$ slc debug server/server.js 
Node Inspector is now available from http://localhost:8080/debug?port=5858
Debugging `server/server.js`

Debugger listening on port 5858
```

**Comment by gunjpan** [comment]
@dineshi2it : the first command: `slc debug node .` should be replaced as `slc debug .` 
_(Use `slc debug -h` for more info)_
>Am I giving wrong cmd or something is wrong with node-inspector ?
Also I have tried the following but the app is not running

Looks like this is happening due to `node-inspector` version, installed under `strongloop`. 
Current version in `strongloop` is `~0.7.0`, updating it to the latest resolves the issue. 
Meanwhile, you can edit the `package.json` in `strongloop` repo, installed globally, and change the `node-inspector` version in `dependencies` to:
`"node-inspector": "^0.7.0"`. This should fix it.

I'm closing this issue here and filing to strongloop repo for updating `node-inspector` version in `package.json`.

**Comment by dineshi2it** [comment]
@gunjpan: The second command is similar to `slc debug .` which actually worked. The thing is it took too much time to start the server. Just came to know this from [node-inspector documentation](https://github.com/node-inspector/node-inspector#node-inspector-takes-a-long-time-to-start-up). I think this needs to be added in [loopback doc.](https://docs.strongloop.com/display/SLC/Debugging+applications)
