### ISSUE TITLE
Where clause in beforeRemote related method

### ISSUE THREAD

**Issue by nivincp** [strongloop/loopback#2161]
Cart.beforeRemote('*.__destroyById__products', function(ctx, cart, next) {
});

How can I add a where clause in the above remote hook for example like the one follows

ctx.args.filter.where = {"id_product_attribute": id_product_attribute};

**Comment by richardpringle** [comment]
@nivincp please direct any questions about LoopBack to any of the three following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We keeping the "issues" section of GitHub for bug reports and feature requests only.

That said, I might still be able to answer your question. What seems to be the issue here? Can you not see the where filter in the `ctx` object? Or do you only want the remote hook to be triggered on a specified where clause?

If the latter is true, you will have to use an if statement to call `next()` and skip the rest of the functionality in the remote hook if the specific filter isn't used.

Does that make sense? As I said, I am closing this issue because it is a question, but please feel free to carry on the discussion with me in here.

**Comment by nivincp** [comment]
@richardpringle sorry for the inconvenience, will make sure to open further issues in stackoverflow / google groups.

Here the id_product_attribute is a field in products relation which is mapped to the CartProduct model.
The above remote hook is used in Cart model and I need to somehow apply the where clause to CartProduct context from within the CartModel context. I am also attaching the cart.json and cart-product. json for reference. Thanks for your help.

`{
  "name": "Cart",
  "plural": "carts",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "mysql": {
      "table": "pml_cart"
    }
  },
  "mixins": {
    "TimeStamp": {
      "createdAt": "date_add",
      "updatedAt": "date_upd",
      "required": false
    }
  },
  "hidden": [
    "recyclable",
    "date_add",
    "date_upd"
  ],
  "properties": {
    "id_cart": {
      "type": "number",
      "id": true
    },
    "id_shop": {
      "type": "number",
      "required": true
    },
    "id_lang": {
      "type": "number",
      "required": true
    },
    "id_currency": {
      "type": "number",
      "required": true
    },
    "id_customer": {
      "type": "number",
      "required": true
    },
    "recyclable": {
      "type": "number"
    },
    "date_add": {
      "type": "date"
    },
    "date_upd": {
      "type": "date"
    }
  },
  "validations": [],
  "relations": {
    "products": {
      "type": "hasMany",
      "model": "CartProduct",
      "foreignKey": "id_cart"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
`

`{
  "name": "CartProduct",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "mysql": {
      "table": "pml_cart_product"
    }
  },
  "mixins": {
    "TimeStamp": {
      "createdAt": "date_add",
      "updatedAt": "date_add",
      "required": false
    }
  },
  "properties": {
    "id_cart": {
      "type": "number"
    },
    "id_product": {
      "type": "number",
      "id": true,
      "required": true
    },
    "id_shop": {
      "type": "number",
      "required": true
    },
    "id_product_attribute": {
      "type": "number",
      "required": true
    },
    "quantity": {
      "type": "number",
      "required": true
    },
    "date_add": {
      "type": "date"
    }
  },
  "validations": [],
  "relations": {
    "image": {
      "type": "hasOne",
      "model": "ProductImage",
      "foreignKey": "id_product"
    },
    "price": {
      "type": "hasOne",
      "model": "ProductShop",
      "foreignKey": "id_product"
    },
    "lang": {
      "type": "hasOne",
      "model": "ProductLang",
      "foreignKey": "id_product"
    }
  },
  "acls": [],
  "methods": {}
}
`

**Comment by richardpringle** [comment]
@nivincp, please use code blocks like this
```json
"relations": {
  "image": {
    "type": "hasOne",
    "model": "ProductImage",
    "foreignKey": "id_product"
  },
  "price": {
    "type": "hasOne",
    "model": "ProductShop",
    "foreignKey": "id_product"
  },
  "lang": {
    "type": "hasOne",
    "model": "ProductLang",
    "foreignKey": "id_product"
  }
}
```
[GitHub documentation on creating and highlighting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

The easiest thing to do would be to create a [middleware function](https://docs.strongloop.com/display/APIC/Defining+middleware)

You can append a `where` filter onto the `request` object anywhere before the `routes` phase.
