### ISSUE TITLE
Spike: Lazy connect datasources on app start

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2176]
In order to generate swagger spec, e.g. inside `apic`, we need to load the app. At the moment, all datasources open connection to databases at the start time and if there is any problem, the whole app crashes, even though we only wanted to query metadata.

The proposal is to modify all connectors to correctly implement a lazy `connect` method and then modify juggler to allow the user to defer initialization of connections until later.

/cc @raymondfeng did I capture the intent correctly?
/cc @ritch

**Comment by jannyHou** [comment]
- **MYSQL**
Doesn't report error with invalid or empty settings
- **MONGODB**
Doesn't report error with invalid or empty settings
- **DB2**
Report empty and invalid settings

**Comment by jannyHou** [comment]
[loopback-boot/lib/executor.setupDatasources](https://github.com/strongloop/loopback-boot/blob/master/lib/executor.js#L32)

[loopback/lib/application.js.dataSource](https://github.com/strongloop/loopback/blob/master/lib/application.js#L221)

**Comment by jannyHou** [comment]
@bajtos When we boot the app, it triggers the datasource setup function of all connectors in `datasource.json`, within setup it creates a new datasource instance, which tries to connect using ds settings. 
I am not sure is it proper to add a flag parameter in `datasource.setup` then if it's called when booting the app, it skips [this block which tries to create a new datasource instance](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L334-L350)

**Comment by jannyHou** [comment]
@raymondfeng @bajtos I try to implement the lazy connect and take mongodb and mssql as an example:

https://github.com/strongloop/loopback-boot/pull/185
In loopback-boot, I add a flag variable `lazyConnect` to each datasource config when booting app(haven't thought of a proper name, so name it as `lazyConnect` temporarily)

https://github.com/strongloop/loopback-connector-mongodb/pull/241
https://github.com/strongloop/loopback-connector-mssql/pull/80
Then disable connect in initialization if `lazyConnect` is true. Details are explained and discussed under each pr.

**Comment by jannyHou** [comment]
**UPDATE**
Now when we run `apic loopback:refresh`, the connection error is not shown since the error check takes longer time than swagger generator finished. But it turns out that the swagger update still triggers connection. 

As a solution:
[1]. Since the boot is called when we [`require('app_path')`](https://github.ibm.com/apimesh/apiconnect-cli-loopback/blob/master/lib/swaggerGenProc.js#L21), I think we can add a `process.argv[index]` as a flag variable, which can be read in `loopback-boot`.

[2]. In connectors, add a property `lazyConnect` in datasource config as shown in [this pr](https://github.com/strongloop/loopback-connector-mongodb/pull/241) 

[3]. And in `loopback-boot`, set `dsConfig.lazyConnect = process.argv[index]`. Then when the app boot calls connector initialize, connector will know if lazyConnect is needed.

**Comment by bajtos** [comment]
> [1]. Since the boot is called when we require('app_path'), I think we can add a process.argv[index] as a flag variable, which can be read in "loopback-boot".

I am proposing to use an environment variable instead, e.g. `LB_LAZYCONNECT_DATASOURCES`.

**Comment by jannyHou** [comment]
@bajtos Thank you, using ENV is the right way, setting command line argument is pretty dangerous. Will change that part.

**Comment by jannyHou** [comment]
I am closing this spike issue. Track and move discussions in this issue https://github.com/strongloop/loopback/issues/2242. Also link prs to it.
