### ISSUE TITLE
How can I disable remote methods for Container model of Storage component ?

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback#2189]
Hello everyone, 

Seems I can not disable any remote methods of Container model of Storage component. I've tried to call `Container.disableRemoteMethod('find',true);` in `container.js` but the `Get /containers` api was still be there (on api explorer).

Can someone please take a look to help me out ?

Thanks.

**Comment by jannyHou** [comment]
@dongmai I am trying to help you reproduce your problem, I tried with a simple loopback app and it works:
1. `slc loopback` to create app
2. `slc loopback:model` to add a model
3.  `myModel.disableRemoteMethod('find', true);` in common/models/mymodel.js
4. `node .` and open explorer, `GET/ myModels` is hide.
If you still get error, could you fork this sandbox and replace it with your code: https://github.com/strongloop/loopback-sandbox
Thanks.

**Comment by dongmai** [comment]
Thanks @jannyHou , I still get other model methods disabled but the Container model of Storage component. It only happens for Storage component, you can refer the docs here : https://docs.strongloop.com/display/public/LB/Storage+component.

**Comment by jannyHou** [comment]
@dongmai I think this caused since model `Container` is created in facet `server`, not `common`
If you want to disable all REST endpoints of it, a workaround is set field `public` as false, it will hide all rest apis:
in `server/model-confg.json`, set Container's config as:
```
 "container": {
    "dataSource": "storage",
    "public": false
  }
```

I will dig more into the server facet, see is there a way to disable single remote method and how to do it.

**Comment by richardpringle** [comment]
Hey @dongmai, first of all, you should probably put this issue in the [loopback-component-storage repo](https://github.com/strongloop/loopback-component-stroage) so that we can track all issues related to that module there. 

Models that have loopback-component-storage as their datasource are set up differently than other models. That's how they get all the extra methods like `download`. 

What are you trying to accomplish in the end? If you don't want your users to be able to see all the files in a container, it mike make sense to only use the container as a private model as @jannyHou suggests in her example above. Then you would create another model with remote methods that make calls to the container model... make sense?

Let me know what your final intentions are and maybe I can give you some advice. 

Until then, good luck and happy coding!

**Comment by dongmai** [comment]
Hi @richardpringle ,

My purpose is just exposing `download` method. But I cant find any way to do this. If make container as a private model I see that users cant use `download`  (to load an image for example.).

**Comment by richardpringle** [comment]
@dongmai, here's what you do:

In `server/model-config.json`
```json
"container": {
  "datasource": "storage",
  "public": false
},
"file": {
  "datasource": "db",
  "public": true
}
```

So what I'm saying above is that you need to create another model and call it whatever, but "file" makes the most sense to me.

When you're creating your new model, `file`, make sure the base class is `Model` instead of `PersistedModel`. 

Add the following code in `file.js`
```node
module.exports = function(File) {
  var Container = File.app.models.Container

  File.download = function ([arguments]) {
    Container.download([arguments]);
  }
  File.remoteMethod();

}
```

I didn't fill out any of the logic, but I just use that example to illustrate my point. You create a remote method called `download` for the `File` model and just call the `download` method that belongs to `Container` from within `File.download`? 

You will have to take a look at the [stroage API](https://apidocs.strongloop.com/loopback-component-storage/#storageservice-download) to see what parameters you need as my `[arguments]` is just a place holder.

Also, if you need an example for populating the remoting metadata, you can find it [in the code](https://github.com/strongloop/loopback-component-storage/blob/f18d86392df9b1bb06a41030d2af7b2d75f89bdf/lib/storage-service.js#L321-L329)

If you make fork [loopback-example-storage](https://github.com/strongloop/loopback-example-storage), then I can take a look as you progress and help you along.

**Comment by richardpringle** [comment]
@dongmai, could you please also open a new issue in [loopback-component-storage](https://github.com/strongloop/loopback-example-storage/issues) as a feature request, asking for the additional feature to disable remote methods and mention me in the description? I think that is something that we could easily implement, but it won't get implemented unless you open a feature request in that repo.
