### ISSUE TITLE
Weird behaviour when creating embedded model instance

### ISSUE THREAD

**Issue by Nautigsam** [strongloop/loopback#2203]
Hello, I'm facing a strange behaviour with an operation hook triggered two times instead of one, you can check it out on this sample repo: https://github.com/Nautigsam/loopback-embed-create-test

**Comment by jannyHou** [comment]
@Nautigsam Thanks for your sandbox. I am debugging to find why it's triggered twice, the second one is triggered since `bookInstance.updateAttributes()` is called when you creating a pageInstance for it. But I still have no idea where the first one comes from.
Do you have any update or new findings?

**Comment by jannyHou** [comment]
@Nautigsam oh ok I think I find why it's triggered twice:
once by [`EmbedsMany.prototype.prepareEmbeddedInstance`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L2374)
and once by [`EmbedsMany.prototype.create`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L2644)

**Comment by Nautigsam** [comment]
Sounds right, I thought it was the source of a bug on my project but finally not so I close it. Thanks!
