### ISSUE TITLE
Cannot hide endpoints for hasOne relationship

### ISSUE THREAD

**Issue by nmklong** [strongloop/loopback#2214]
My Order class has "referral" as a hasOne relationship

I want to hide all endpoints of the relation referral, so i added this:

```
    Order.disableRemoteMethod('__get__referral', false);
    Order.disableRemoteMethod('__create__referral', false);
    Order.disableRemoteMethod('__findById__referral', false);
    Order.disableRemoteMethod('__updateById__referral', false);
    Order.disableRemoteMethod('__delete__referral', false);
    Order.disableRemoteMethod('__destroyById__referral', false);
    Order.disableRemoteMethod('__count__referral', false);
```

It did hide everything except for the PUT and DELETE endpoints. If i change the relationship to hasMany everything will be hidden, so i guess this is a bug for hasOne relationship. can somebody check? Thank you

**Comment by jannyHou** [comment]
hey @nmklong I think if you leave foreignKey as blank and use the default one, you need to use `Order.disableRemoteMethod('__get__referrals', false);` instead of `Order.disableRemoteMethod('__get__referral', false);`

I tried both `hasMany` and `hasOne`, yeah `hasMany` works fine with your code, but for `hasOne`, you will need to disable two more remote methods:
```
Order.disableRemoteMethod('__update__referrals', false);
Order.disableRemoteMethod('__destroy__referrals', false);
```

All of the buildin remote method for `hasOne` relation are defined here:
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js
Take `hasOne.prototype.update` as an example: 
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L1734

**Comment by nmklong** [comment]
@jannyHou thank you for your perfect response! However i suggest making this a bit clearer in "Exposing model" tutorial so that other users won't get confused when they use this relationship like me.

**Comment by jannyHou** [comment]
glad that it solves your problem:) @nmklong I think we already document here https://docs.strongloop.com/display/LB/Exposing+models+over+REST#ExposingmodelsoverREST-Predefinedremotemethods
The list of methods you disabled is only used to demo an example, for a full mapping between predefined method and endpoint, please check the link above and also https://docs.strongloop.com/display/LB/PersistedModel+REST+API
