### ISSUE TITLE
apic command should be changed to slc when generating ACL

### ISSUE THREAD

**Issue by supasate** [strongloop/loopback#2225]
https://docs.strongloop.com/display/public/LB/Controlling+data+access#Controllingdataaccess-UsingtheACLgeneratortodefineaccesscontrol

To generate ACL, the command
`$ apic loopback:acl`
should be changed to
`$ slc loopback:acl`.

**Comment by supasate** [comment]
@crandmck Is it correct to use apic? I just found it on that page while other commands use slc.

**Comment by crandmck** [comment]
Thanks @supasate That was a mistake.  I fixed it... It should be `slc` on that page.  Note that there is a corresponding page for API Connect https://docs.strongloop.com/display/APIC/Controlling+data+access that has the `apic` command.

**Comment by noderat** [comment]
@crandmck I'm finding apic all over the place in the loopback docs suddenly, perhaps there should be a new issue opened to help track down and fix all of them?

**Comment by crandmck** [comment]
@noderat The LoopBack docs should not refer to `apic` and a search of the LB space for "apic" does not return any results: https://docs.strongloop.com/dosearchsite.action?queryString=apic&startIndex=0&where=LB

However, note that there is now an APIC space that includes documentation for LoopBack, but with references to the StrongLoop tools replaced by API Connect tools--so a search for "apic" in APIC space does return lots of results: https://docs.strongloop.com/dosearchsite.action?queryString=apic&startIndex=0&where=APIC.  For example https://docs.strongloop.com/display/APIC/Command-line+reference.

Note that the space is part of the page URL, and in many cases the pages in each space are exactly the same, except links in the page go to other pages in the same space-- for example we have https://docs.strongloop.com/display/APIC/Using+built-in+models and https://docs.strongloop.com/display/public/LB/Using+built-in+models.

So I suspect you may have ended up on a page in the APIC space instead of the LB space.   If you find pages in the LB space that refer to "apic" please provide the specifics.

**Comment by noderat** [comment]
@crandmck Here's just a couple I found just in my open tabs:

https://docs.strongloop.com/display/public/LB/Defining+models
https://docs.strongloop.com/display/public/LB/Remote+methods

**Comment by crandmck** [comment]
OK, thanks.  I fixed those. 

Obviously Confluence search isn't finding them as it should.  I'll try to find other occurrences.. maybe Google will do a better job.

LMK when you run across any others.
