### ISSUE TITLE
disable caching

### ISSUE THREAD

**Issue by rweng** [strongloop/loopback#2257]
So I've been playing around with loopback but was not able to set up my models and api correctly. After a lot of debugging, it turns out that loopback (or datasource-juggler) is caching data and I am not able to bust it.

I've created this gist to illustrate the case: https://gist.github.com/rweng/148cea1d0d0d60016d168fbb4162139a

Now even worse is that the same problem occurs when using the API. Adding `user.reload()` does not work. Is there a way to disable caching completely? I am just getting started with loopback and would like to get a feel on loopback and not debug caching problems.

Thanks a lot,
Robin

**Comment by gunjpan** [comment]
@rweng : Hey Robin, yes, `loopback-datasource-juggler` caches the data. This is a known limitation at the moment, more discussion [here](https://github.com/strongloop/loopback/issues/256) 

Workaround for this issue is:
Always pass 'true' as the first parameter of "find-all" queries. 
In other words, in your test file, changing the code to:
```
app.models.account.find(true)
```
should refresh the cache. 

Hope that addresses your question. Please let me know if you have any questions/concerns, thanks.

**Comment by gunjpan** [comment]
@rweng:  Did above solution work for you?

**Comment by rweng** [comment]
@gunjpan Thanks for your help and feedback, but I decided to switch to Koa 2. I'm not yet in need of all the features that loopback provides, and after coming across some other stumbling stones (or making some more mistakes) with loopback I decided that the learning curve was too steep for the moment.

**Comment by lobabob** [comment]
I encountered `AssertionError: The query argument must be an object` when trying to use the above solution.
