### ISSUE TITLE
remoteMethod() has no request parameters when POSTed to. [Previously it was #440]

### ISSUE THREAD

**Issue by ks1974in** [strongloop/loopback#2290]
This issue has appeared again. My code is as follows

    Job.remoteMethod(
            'createJob',
            {
                description: 'Creates a Job',
                accepts:
                        [{arg: 'userId', type: 'string','required':true},
			 {arg: 'authToken', type: 'string','required':true},
			 {arg: 'job', type: 'Job','http':{source:'body'},'required':true}]	
                ,
                consumes:'application/json',
                returns: {
                    arg: 'result', type: 'Job', root: true, description: 'Create a Job'
                },
                http: {verb: 'post'}
            });

Job.createJob = function (userId,authToken,job, cb) {
       	Job.app.models.Job.create(job);
        return cb(null,{"response":{"responseMessage":"OK","responseStatus":0},"data":job});
}

When I try to post from the api explorer, the two request parameters userId and authToken do not get sent with the request. The request url is http://localhost:3000/api/Jobs/createJob instead of http://localhost:3000/api/Jobs/createJob?userId=001&authToken=500

![post issue in api explorer](https://cloud.githubusercontent.com/assets/19181476/15005939/7cdcd38c-11e8-11e6-9187-c0ffe0d97909.png)
![post from postman](https://cloud.githubusercontent.com/assets/19181476/15005960/c9d6b7c0-11e8-11e6-9f03-98d67bb7dc36.png)

**Comment by richardpringle** [comment]
Hey @ks1974in, first of all, you are passing in the arguments as formData so they won't get appended as a query string.

Side note: I think that `Job.app.models.Job.create` is redundant. You could just use `Job.create` and it would be the exact same thing... woops :wink:.

Also, is there any reason that you didn't use the following `http: { source: 'query' }` in the first two elements of your `accepts` array if that's where you wanted them?

However, there is something strange happening here. I don't think that this is a bug with strong-remoting or loopback though. Try removing the `consumes` option and try calling the callback `cb` instead of returning it. You also might want to test this out without your `jobs.create` function and get it to that stage before actually creating the job instance. 

I know it might not be the most convenient, but try building the function in small steps and you should find your problem. Otherwise, if you can fork a [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and reproduce the issue with a simplified example, then it's probably a bug.

Good luck and keep me posted. I'll see if I can try to help you out.

**Comment by ks1974in** [comment]
Hi Richard!
Thanks for the guidance. Yes, i will add http:{source:query}. But I send a
Job object in the Request body, and so i specified consumes .
I did not find anything wrong while using postman. The only problem was no
query parameters, which you resolved.

If you could describe in a bit more detail what is strange or unexpected, i
will try to reproduce it.

Also, thanks for the tip about using Job.create

I am just starting with loopback, and am loving it

Will keep you posted.

Regards,
Sagar
On May 4, 2016 7:27 PM, "Richard Pringle" <notifications@github.com> wrote:

Hey @ks1974in <https://github.com/ks1974in>, first of all, you are passing
in the arguments as formData so they won't get appended as a query string.

Side note: I think that Job.app.models.Job.create is redundant. You could
just use Job.create and it would be the exact same thing... woops [image:
:wink:].

Also, is there any reason that you didn't use the following http: { source:
'query' } in the first two elements of your accepts array if that's where
you wanted them?

However, there is something strange happening here. I don't think that this
is a bug with strong-remoting or loopback though. Try removing the consumes
option and try calling the callback cb instead of returning it. You also
might want to test this out without your jobs.create function and get it to
that stage before actually creating the job instance.

I know it might not be the most convenient, but try building the function
in small steps and you should find your problem. Otherwise, if you can fork
a loopback-sandbox <https://github.com/strongloop/loopback-sandbox> and
reproduce the issue with a simplified example, then it's probably a bug.

Good luck and keep me posted. I'll see if I can try to help you out.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/strongloop/loopback/issues/2290#issuecomment-216873001>

**Comment by richardpringle** [comment]
I don't believe that the `consumes` property of your remoting `options` object (the second argument of `job.remoteMethod`) is recognized at all by LoopBack or strong-remoting.

The weird part is that you got an error saying `userId is a required arg` when you had entered it (even without specifying the `http.source` object.

If you got it working, that's all that matters. If you come across the problem again, please re-open this issue or open another one. In either case, mention me in a comment and I will try to figure it out with you.

**Comment by ks1974in** [comment]
Userid was not part of the query string. Hence the error message. Btw,
specifying query as source resolved it.
