### ISSUE TITLE
Feature request for  PUT with WHERE in loopback .

### ISSUE THREAD

**Issue by mountain1234585** [strongloop/loopback#2331]
Currently, loopback framework provides support for performing updateOrCreate in case of primary key only. For cases, where upsert feature needs to be supported based on foreign key, we need to have an operation supporting *PUT with Where clause and data field. The same way, we have POST with Where  now. 

@bajtos .. please let me know if you have plans for supporting this anytime soon.

**Comment by bajtos** [comment]
@mountain1234585 we don't have immediate plans to support this feature. Would you like to contribute it yourself?

@Amir-61 has recently added two new methods `replaceById` and `replaceOrCreate`, you can use his work for inspiration, since adding "upsert by where filter" will be similar in many aspects. See https://github.com/strongloop/loopback-datasource-juggler/pull/788 and related issues and pull requests.

In general, you need to:

 - Implement the new method in loopback-datasource-juggler's `lib/dao.js`. I think you will need a new connector method to achieve what you need, see below. For connector that don't provide this new method yet, you should provide a fall-back implementation calling `find` and `create` or `updateAttributes` under the hood - take a look at how `findOrCreate` is implemented.
 - Implement the new connector method at least in the connectors you are going to use in your application. 
 - Expose the new DAO method in the REST API by modifying loopback's `lib/persisted-model.js`.

**Comment by Amir-61** [comment]
@mountain1234585 If you decided to contribute code please ping me on your PRs so I can help review the code as well.

Thanks!

**Comment by mountain1234585** [comment]
@Amir-61 @bajtos
I have added a method upsertWithWhere in loopback-datasource-juggler  and also changed the persisted-model.js in loopback/dao.js.

When I run the loopback application, I am able to see the new method in the explorer , but the operation fails giving the following error:

{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Cannot call Account.upsertWithWhere(). The upsertWithWhere method has not been setup. The PersistedModel has not been correctly attached to a DataSource!",
    "stack": "Error: Cannot call Account.upsertWithWhere(). The upsertWithWhere method has not been setup. The PersistedModel has not been correctly attached to a DataSource!\n    at throwNotAttached (/Users/sonalisamantaray/Documents/office/salesforceApp/node_modules/loopback/lib/persisted-model.js:62:11)\n    at Function.upsertWithWhere 

Please advise!

**Comment by Amir-61** [comment]
@mountain1234585 Please share the repo(s) to reproduce the issue.

**Comment by mountain1234585** [comment]
@Amir-61.  Pls find it here --> https://github.com/mountain1234585/myRepo .   dao.js and loopback lib/persisted-model.js

**Comment by Amir-61** [comment]
@mountain1234585 Assuming you are using memory connector and I don't see you have implemented your method `upsertWithWhere` in `loopback-datasource-juggler` in `lib\connector\memory.js`; here is your code which expects the connector to implement `upsertWithWhere()` method.
```
            if (connector.upsertWithWhere.length === 5) {
              connector.upsertWithWhere(Model.modelName, where, update, options, done);
            } else {
              connector.upsertWithWhere(Model.modelName, where, update, done);
            }
```
Also a quick note about this logic of your code ^:
We had the above checking for `connector.upsertWithWhere.length` for backward compatibility; however since `upsertWithWhere` is a new connector operation and we don't have to preserve backwards compatibility, you don't need this checking anymore.

I recommend sending PRs to different repos and discuss it there.

**Comment by mountain1234585** [comment]
@Amir-61
Thanks for your review. I am using salesforce connector and have the method implemented there in salesforce.js.  I will implement it in the memory.js as well .

**Comment by mountain1234585** [comment]
@Amir-61

Please consider these two PRs. I tested it manually and seems to work.
https://github.com/strongloop/loopback-datasource-juggler/pull/995
https://github.com/strongloop/loopback/pull/2496

**Comment by mountain1234585** [comment]
While doing further tests with connectors, I found out that, the changes work very well for connectors which have no specific  implementation for "upsertWithWhere". It invokes the default implementation and works as expected.

But, it dint work for connectors who would want their specific implementation in their respective lib folder,  and not point to this default implementation. Even if the method is implemented, it gets into the default implementation.  Please advise.
