### ISSUE TITLE
destroyAll does not respect normalizeUndefinedInQuery

### ISSUE THREAD

**Issue by tmikulcek** [strongloop/loopback#2364]
This bit us today. An undefined value got into the where clause of destroyAll and caused a delete of all items. We tried using normalizeUndefinedInQuery option as per https://github.com/strongloop/loopback/issues/637 but it only works in find queries.

Sample repo: https://github.com/tmikulcek/loopback-sandbox
Run the test with mocha

**Comment by loay** [comment]
Hi @tmikulcek 
I am having a look. I will get back to you ASAP.

**Comment by loay** [comment]
Hi @tmikulcek 
as I can see here in find: Error: Unexpected `undefined` in query
but the `err` in `destroyall` gives undefined and that's why the test fails. 
I will flag it as a bug.
Thanks for reporting the issue.

**Comment by angfal** [comment]
Hi, everyone!

The same problem with count and update methods. As I understand, all filter/where objects should 'removeUndefined' with 'normalizeUndefinedInQuery' parameter. And all data objects (for create, update) without it.

Could you please pay attention on this bug? Because it's an enough serious problem. The requests like `Model.remove({id: $id, cb});` and `Model.update({id: $id, $data, cb});` can totally corrupt data in the database if $id somehow equals 'undefined'

**Comment by raymondfeng** [comment]
@ssh24 See PR at https://github.com/strongloop/loopback/issues/2364

**Comment by loay** [comment]
Issue is fixed. Please have a look. 
If issue is still persisting, please leave a comment here. Thanks.
