### ISSUE TITLE
Incorrect Results With Count When Using "filter[where][...]" vs Just "where[...]"

### ISSUE THREAD

**Issue by infinisuite** [strongloop/loopback#2382]
I'm getting two different results when using **'filter[where][...]'** vs just using **'where[...]'** with the **count** end-point.

```
/api/account/count?filter[where][companyrowid]=1
// ---> RESULT: Total # of rows in the unfiltered table. (INCORRECT)

/api/account/count?where[companyrowid]=1 
//---> RESULT: Total # of rows in the table where companyrowid = 1 (CORRECT)
```

**Comment by richardpringle** [comment]
@InfiniSuite, interesting find. The optional parameter on the `count` function is supposed to exclusively be the "where" filter (see [API docs](https://apidocs.strongloop.com/loopback/#persistedmodel-count) for details). Will have to take a deeper dive to see what's causing the issue and if we can return an error if you try to use "filter" as a query parameter.

**Comment by schempy** [comment]
Looks like in the library strong-remoting file https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L224 is where the query parameters are extracted from the url. It's based on the method that is being accessed. In this case the acceptable query parameter for method ```count``` is ```where```. If ```where``` is not found in the query parameters then an empty object is returned which is why using ```count?filter[where][companyrowid]=1``` returns all values from that model.

A check could be added to the http-context.js file. I'm new to the code base so not sure if this is the best place for a check.
