### ISSUE TITLE
Model.find() returns undefined

### ISSUE THREAD

**Issue by madianas** [strongloop/loopback#2387]
In boot script, I am trying to query data from the model:

/server/boot/cron.js:
```
module.exports = function (app, cb) {
  var Transaction = app.models.Transaction
  app.on('started', function () {
    setTimeout(function () {
      Transaction.find({
        limit: 10
      }, function (res) {
        console.log(res);
      });

    }, 3000)
  });

  process.nextTick(cb); // Remove if you pass `cb` to an async function yourself
};
```
It comes out as  "undefined" in the console.
`console.log(Transaction)` comes out fine. The model is attached and it has a `find()` function. All the other functions, such as Transaction.count(), Transaction.findById() etc. return the same undefined.

I am using a loopback generated app. Is there an option somewhere, that causes this behavior? 

This is the shortened model's Transaction.json without properties and relations:

> {
>   "name": "Transaction",
>   "base": "PersistedModel",
>   "strict": true,
>   "idInjection": true,
>   "options": {
>     "validateUpsert": true
>   },
>   "properties": {
>     "amount": {
>       "type": "number",
>       "required": true
>     }
>   },
>   "validations": [],
>   "relations": { },
>   "acls": [
>     {
>       "accessType": "*",
>       "principalType": "ROLE",
>       "principalId": "$everyone",
>       "permission": "DENY"
>     },
>     {
>       "accessType": "*",
>       "principalType": "ROLE",
>       "principalId": "$authenticated",
>       "permission": "ALLOW"
>     }
>   ],
>   "methods": {}
> }

slc version
`
>slc --version
strongloop v6.0.1 (node v5.10.0)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.1 (6ab604c)
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.3 (ec2d95b)
├── generator-loopback@1.20.6 (c53788b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
`

**Comment by gunjpan** [comment]
Looking into it.

**Comment by gunjpan** [comment]
@madianas : Hi, it's happening because you're referring to the first argument of `find(err, res)`. The method [signature of `find()`](http://apidocs.strongloop.com/loopback/#persistedmodel-find) is:
`PersistedModel.find([filter], callback)` where callback function is called with (err, returned-instances) arguments.

Changing your boot script: `cron.js` as following should resolve the issue:
```javascript
module.exports = function (app, cb) {
  var Transaction = app.models.Transaction
  app.on('started', function () {
    setTimeout(function () {
      Transaction.find({
        limit: 10
      }, function (err, res) {
        if(err) console.error(err);
        console.log(res);
      });
    }, 3000)
  });

  process.nextTick(cb); // Remove if you pass `cb` to an async function yourself
};
```

Closing this for now. Should you need further assistance with this issue, please let me know.

For future reference, we encourage you to post questions to our Google group or StackOverflow channels ([links here](https://github.com/strongloop/loopback/wiki/Questions)) as we are trying to keep GitHub a medium for bug filing/feature requests only.

Thank you for your consideration and have a happy time LoopBack*ing* :)

**Comment by madianas** [comment]
OMG, I did not know that. Thank you so much!
I am new to this, I thought error is usually a separate function after the result function.

I will pay more attention to the docs now.
