### ISSUE TITLE
Nested object in response after create

### ISSUE THREAD

**Issue by gjrwebber** [strongloop/loopback#2404]
Is this possible?

```
Country hasMany Cities
City belongsTo Country
```
I first create a Country:
```
POST api/country
{
 "name": "Australia"
}
```
Now I want to create a new city and return the country in the response:
```
POST api/country/1/city
{
 "name": "Newcastle"
}
```

Wanted response:
```
{
  "id": 1,
  "name": "Newcastle",
  "country": {
    "id": 1,
    "name": "Australia"
  }
}
```

Actual response:
```
{
  "id": 1,
  "name": "Newcastle",
  "countryId": 1
}
```

I have tried adding an 'after save' hook to load the country, but it still does not get sent in the response. Is this possible? If not, is there a workaround?

**Comment by gjrwebber** [comment]
I have managed to get the nested model object using: 
```
    Country.afterRemote('*.__create__cities', (ctx, city, next) => {
        city.__data.country = city.country();
        next();
    });
```

But this feels like a hack. Is this the best way to do what I am after?

**Comment by gunjpan** [comment]
@gjrwebber : Hi, yes, that seems to be a right way. If I understand correctly, what you're trying to do is manipulate res object for `create` method with results of `find` method. I recommend separating the actions here as you won't get a `join` result on your create query. 

You can use [`include` filter](https://docs.strongloop.com/display/public/LB/Include+filter) for your find query which will give you the results in the format you want. 

hope that helps. Closing this for now. If you need further assistance with it, feel free to reopen and mention me.
For future reference, I encourage you to post the questions to our dedicated [question channels](https://github.com/strongloop/loopback/wiki/Questions) so that more people can benefit and also we can stay aligned with our goal of keeping GH space for feature requests/bug reports.
Thank you :)
