### ISSUE TITLE
Use loopback with limited api?

### ISSUE THREAD

**Issue by tomgie** [strongloop/loopback#2507]
Is there a way for an example delete something with a post request through the URL or headers? I am limited only on POST and GET requests for a program I am using. Otherwise can anyone point me in the right direction to a database type thing like loopback?

**Comment by crandmck** [comment]
A REST app should use the HTTP DELETE method to delete a record; otherwise it wouldn't truly be REST.  So that's how LB works, e.g. [PersistedModel REST API - Delete model instance](https://docs.strongloop.com/display/public/LB/PersistedModel+REST+API#PersistedModelRESTAPI-Deletemodelinstance).  You might be able to hack around it, e.g. using a remote method, but I don't think that is advisable.

**Comment by alexda14** [comment]
@crandmck 
What about [Express HTTP method override](https://github.com/expressjs/method-override) ? Does it solves an issue ?

**Comment by superkhau** [comment]
Remote methods as suggested by @crandmck is the recommended way if you want to craft your endpoint to your specification. As recommented, using HTTP DELETE makes more sense. Closing this as resolved.

**Comment by crandmck** [comment]
@alexda14 I'm not familiar with that module _per se_ but I believe it would be appropriate only to use it with an "standard" Express app, not as part of a LoopBack app.
