### ISSUE TITLE
So many issues

### ISSUE THREAD

**Issue by hoangtrongphuc** [strongloop/loopback#2511]
2 month ago, I check loopback source with more 500 Issues, and now, everything not change? So loopback maybe use in production.
Maybe I will wait for loopback v3

**Comment by superkhau** [comment]
@hoangtrongphuc You can take that as a sign of a healthy active project. We have a team of people working on triaging issues, but it takes time to go through each and every issues individually (we get roughly 60-70 issues every 2 weeks, so just to balance the incoming numbers is a feat in itself).

While comparing numbers, you could take a look at https://github.com/nodejs/node. They have about 500 issues too, and in two months, they'll probably have even more (hopefully less). So that metric itself isn't enough to say nothing is changing. People are working hard and if you run into any issues, you're also free to open an issue yourself (or better yet, contribute a fix).

Going to close this issue as there is nothing to resolve.
