### ISSUE TITLE
MongoDB - loopback.getCurrentContext() return null

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback#2519]
Hi everyone ,

Sorry for duplication, but I'm facing it again on nearly the latest version of loopback.
 Here is my `pacakge.json`

```
{
  "name": "test",
  "version": "1.0.0",
  "main": "server/server.js",
  "scripts": {
    "start": "node .",
    "pretest": "eslint .",
    "posttest": "nsp check"
  },
  "dependencies": {
    "async": "^2.0.0",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-mongodb": "^1.15.2",
    "loopback-datasource-juggler": "^2.39.0",
    "loopback-testing": "^1.2.0",
    "serve-favicon": "^2.0.1"
  },
  "devDependencies": {
    "eslint": "^2.5.3",
    "nsp": "^2.1.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "description": "test"
}
```

I've used a middleware to save current logged user data into context but it (`getCurrentContext`) always returned `null` when working with MongoDB (memory db works just fine.) 

Bellow is my code, 

```
app.use(loopback.token()); 
app.use(loopback.context());

app.use(function (req, res, next) {
    if (!req.accessToken) return next();

    app.models.User.findById(req.accessToken.userId, function(err, user) {
        if (err)   return next(err);
        if (!user) return next(new Error('No user with this access token was found.'));
        res.locals.currentUser = user;

        var loopbackContext = loopback.getCurrentContext();
        console.log('SERVER CTX?' +loopbackContext);
        if (loopbackContext) {
            loopbackContext.set('currentUser', user);
        }else{
            throw new Error('Current context is null.');
        }
        next();
    });
});
```

Can anyone please have a look ? Have I done something wrong ?

Thanks.

**Comment by 0candy** [comment]
Thank you for pointing out this issue. Due to the instability, there are plans to deprecate this method.
See https://github.com/strongloop/loopback/issues/1676

**Comment by syuhei176** [comment]
I had same problem, so I use loopback-connector-mongodb@1.15.1 . It work fine.

**Comment by beornharris** [comment]
Hey, I've run across this issue as well and just wanted to add some extra info (hope it helps somewhere).  I had quick look through [#1676](https://github.com/strongloop/loopback/issues/1676) and didnt see anything that might help me.

I initially had an earlier version of loopback running, where I had no problems calling loopback.getCurrentContext() from within a remote method.  I inadvertently updated to the current version, and started seeing issues.

I have created a demo repo (from scratch and using slc commands + customisation) to help explain.

https://github.com/beornharris/authtest

The issue I am experiencing is directly related to MongoDB and access tokens, as far as I can tell.  Using the repo, the steps to replicate (in api explorer) are as follows (note: requires mongo instance) :

1. go to endpoint /Networks/{id}/contacts, enter an ID (value irrelevant) and empty object {} and submit.  The console shows a context received at the endpoint (from common/models/network.js - Network.addContact)

```
CONTEXT:  Namespace {
  name: 'loopback',
  active: { accessToken: undefined },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
```

2. Login using /Accounts/login

`{ "email": "user1@username.com", "password": "user1"}

and set the Access Token.

3. Repeat step 1 - the console shows 

`CONTEXT:  null
`

Given this, I have a few other observations :
1. Issue does not occur when using memory DB connector
2. CONTEXT always shows null when ACL or AccessToken are set to mongo (this may well be by design, but I dont recall reading in the docs that these should ALWAYS be in-memory)
3. Error also occurs when using the built-in User model, and not just the derived (Account) model.

**Comment by dongmai** [comment]
Just try to use `loopback-connector-mongodb@1.15.1` And it isn't working. :(

**Comment by beornharris** [comment]
@dongmai - just to confirm, to downgrade the mongo connector you did something like the following...

1. change package.json from "^1.15.2" to "1.15.1"
2. npm install

so it is using 1.15.1, and not minimum 1.15.1 ?

**Comment by josieusa** [comment]
I had the same issue using the same connector.
I solved it using my own PR locally:
https://github.com/strongloop/loopback-context/pull/2
So far, so good.
Of course, it's going to need more tests.
I'd also mention that it solved many other similar issues with getCurrentContext() for me.
**Your mileage may vary**

**Comment by dongmai** [comment]
@beornharris Yes, I've downgraded the version number in package json and re-run `npm install` of course. 

Before downgrading it was working on local but not on remote server, and its the same after downgrading.

**Comment by evseevnn** [comment]
@beornharris +1

**Comment by Jeff-Lewis** [comment]
@josieusa try telling MongoDB to use [cls-bluebird](https://github.com/TimBeyer/cls-bluebird) instead and then use `cls-hooked` instead of cls when [initializing](https://github.com/TimBeyer/cls-bluebird#usage) `cls-bluebird`. 

In `MongoClient.connect` [we can pass in](http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html) the `promiseLibrary` to use.  Now I'm not sure if there is an easy way to tell `loopback-connector-mongodb` to use our instance of `cls-bluebird` without forking it.

**Comment by bajtos** [comment]
Issue moved to [strongloop/loopback-context #21](https://github.com/strongloop/loopback-context/issues/21) via [**ZenHub**](https://www.zenhub.com/)
