### ISSUE TITLE
Can't Create a New Datasource Using SLC

### ISSUE THREAD

**Issue by fargozhu** [strongloop/loopback#2528]
I am trying to create a new datasource using slc command line without success. The EISDIR states that looks like a permission issue but even going crazy (chmod 777) it still persists.

─$ slc loopback:datasource
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)

**Comment by jannyHou** [comment]
@fargozhu I am trying to solve your problem and I tend to believe it's a compatible problem which is fixed in https://github.com/strongloop/generator-loopback/commit/dc95736e5d825b71fcde36b7809ad3bf245b5f3a

Could you try updating your `generator-loopback` to version 1.23.0 and see if that error still happens?

How to update:
By default `generator-loopback` is a dependency of `strongloop` but if you install it globally, slc will use the global one.
So you can either run `npm install -g generator-loopback`,
or run `npm install generator-loopback` where your strongloop installed.

**Comment by fargozhu** [comment]
I'll update and check the fix highlighted.

**Comment by jannyHou** [comment]
I am closing issue here. Please feel free to reopen it if you still run into it or have any further questions
