### ISSUE TITLE
How to transfer built in AccessToken Model to common folder

### ISSUE THREAD

**Issue by inv-joseph** [strongloop/loopback#2576]
I need to transfer AccessToken Model to common working directory in loopback, I tried by simply copying the class , but it not working. I had added some custome code in the function

> AccessToken.findForRequest = function(req, options, cb) {
> }

So that I cannot place this file in node_modules folder. Please provide the steps to transfer this model class to common/model folder in the project.

**Comment by gunjpan** [comment]
@inv-joseph : Hi, you can create a new model by extending built-in `AccessToken` model. Read more on [Extending built-in models](https://docs.strongloop.com/display/public/LB/Extending+built-in+models).

Closing this for now. Should you need further assistance, please feel free to tag me in the comments and will reopen it.

For the future reference, please post questions like this to our [Google group](https://github.com/strongloop/loopback/wiki/Questions) so that it can benefit larger community as well help us in our efforts to keep GH space dedicated to feature requests and bug reports. Thank you.
