### ISSUE TITLE
ModelConstructor.User.verify : Cannot read property 'http' of null

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback#2578]
Hi there,

I got the error while trying to verify email of users after creation.

As the stack trace I found where the error was fired - 

`userModel.sharedClass.find('confirm', true)`

<img width="581" alt="screen shot 2016-08-02 at 5 27 57 pm" src="https://cloud.githubusercontent.com/assets/3855966/17325655/e42c9236-58d6-11e6-86f4-a264ccea114f.png">

Can someone please take a look? Many thanks!

**Comment by alihalabyah** [comment]
Same here ...

**Comment by richardpringle** [comment]
@dongmai, can you fork the [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and reproduce in the fork? Once it's up, I will clone and use my own email config (assuming that's not the problem). 

Please make sure to lock in the proper version of LoopBack.

**Comment by qvantor** [comment]
This message because you hide confirm user method

**Comment by ochimo** [comment]
@qvantor @richardpringle  -- There is still a bug here in User.verify in the following conditions: If you specify your own verification URL in verifyOptions.verifyHref, then it is reasonable that you also have hidden the confirm user method.  The bug is that urlPath should not be built if verifyHref is specified.  Instead urlPath is always built and joinUrlPath throws because confirm method is hidden and thus not a valid method..

  ```
  var urlPath = joinUrlPath(
      verifyOptions.restApiRoot,
      userModel.http.path,
      userModel.sharedClass.findMethodByName('confirm').http.path
    );

    verifyOptions.verifyHref = verifyOptions.verifyHref ||
      verifyOptions.protocol +
      '://' +
      verifyOptions.host +
      displayPort +
      urlPath +
      '?' + qs.stringify({
          uid: '' + verifyOptions.user[pkName],
          redirect: verifyOptions.redirect,
        });

```

**Comment by richardpringle** [comment]
@kjdelisle ^
