### ISSUE TITLE
GET /Users/change-stream fails with Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by adamgiacomelli** [strongloop/loopback#2586]
### How to repeat:

Expose the User model,
Call GET or POST /Users/change-stream in api explorer (/explorer)
This is the error I'm getting:

> GET /Users/change-stream`Error: Can't set headers after they are sent.
>     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
>     at ServerResponse.header (/adamg/node_modules/express/lib/response.js:719:10)
>     at ServerResponse.send (/adamg/node_modules/express/lib/response.js:164:12)
>     at ServerResponse.json (/adamg/node_modules/express/lib/response.js:250:15)
>     at ServerResponse.send (/adamg/node_modules/express/lib/response.js:152:21)
>     at defaultHandler (/adamg/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:391:11)
>     at restErrorHandler (/adamg/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:361:14)
>     at Layer.handle_error (/adamg/node_modules/express/lib/router/layer.js:71:5)
>     at trim_prefix (/adamg/node_modules/express/lib/router/index.js:310:13)
>     at /adamg/node_modules/express/lib/router/index.js:280:7

I have tested it with loopback 2.29.1 and it seems to be a common problem.
I am trying to create a live list of users and came across this problem while trying to figure out why my change stream wasn't pushing updates. Other models I've created have no problems of this kind.

The issue has come up in [https://github.com/strongloop/angular-live-set/issues/10](https://github.com/strongloop/angular-live-set/issues/10) where it was closed with a disabled compression fix.

**Comment by richardpringle** [comment]
@adamgiacomelli, wow... that was a difficult one to debug. 

As it turns out, the method isn't configured to properly return an error message if one exists. What you should receive is a `401 Unauthorized` .

What you need to do to get this working is extend the user-model and create a new ACL that allows access to `createChangeStream` (the same method is used for both GET and POST).

Hope that helps! Now to get that error fixed...

**Comment by richardpringle** [comment]
@superkhau @Amir-61 @gunjpan

We'll have to figure out what the main cause of this issue is. @superkhau and @Amir-61, can you guys did into `PersistedModel.js` to see if it's the actual implementation of the `createChangeStream` function? If not, the issue is in strong-remoting and you can pass it off to me and @gunjpan.

cc/ @bajtos
