### ISSUE TITLE
Set Instance Relation for BelongsTo not working

### ISSUE THREAD

**Issue by benjaminhon** [strongloop/loopback#2614]
In the following example (simplified), I am using postgres datasource

Relationship:
Node belongsTo Device

```
   // create Node
    app.models.Node.create({
      id: node
    })
    .then (function(node) {
      // create Device
      Device.create({
        type: type
      })
      .then(function(device){
        node.device(device);  // not working
      })
    })
```

however, in my database, the node and device gets created, however the deviceid for node us NULL, this means that node.device(device) is not working as in the documentation. Anyone can help? thanks

**Comment by benjaminhon** [comment]
It only works using a hasOne relationship with, 
```
device.create({id: node});
```
This seems to be a bug is it not? Seems like quite a basic functionality to be though.

**Comment by 0candy** [comment]
Where did you set Node to belongsTo Device?
Node.belongsTo(Device, {foreignKey: ‘nodeId’});

**Comment by benjaminhon** [comment]
I used the automatic generator,

in node.json

"relations": {
    "device": {
      "type": "belongsTo",
      "model": "Device",
      "foreignKey": ""
    }
  },

**Comment by alexkolson** [comment]
@benjaminhon Make sure you have explicitly defined the same value for `foreignKey` on both sides of the relation. In your device model definition: (I'm just guessing your model names as they were not provided)

```json
"relations": {
    "node": {
      "type": "hasOne",
      "model": "Node",
      "foreignKey": "nodeId"
    }
  }
```

```json
"relations": {
    "device": {
      "type": "belongsTo",
      "model": "Device",
      "foreignKey": "nodeId"
    }
  }
```

If you set up the relations this way, you should be able to create related models the way you want to.

**Comment by benjaminhon** [comment]
@alexkolson I was under the impression from the docs that if you leave the field empty using the automated too, it will do it automatically?

**Comment by benjaminhon** [comment]
https://docs.strongloop.com/display/public/LB/BelongsTo+relations

```
If the declaring model doesn’t have a foreign key property, LoopBack will add a property with the same name.  The type of the property will be the same as the type of the target model’s id property.
If you don’t specify them, then LoopBack derives the relation name and foreign key as follows:
Relation name: Camel case of the model name, for example, for the "Customer" model the relation is "customer".
Foreign key: The relation name appended with ‘Id’, for example, for relation name "customer" the default foreign key is "customerId".
```

also the derivation is wrong, i confirm this in my database as the foreign key is "deviceid" not "deviceId", it is not camel cased.

**Comment by alexkolson** [comment]
@benjaminhon Yeah I'm a fellow user of loopback and noticed some funky behavior with the generated / derived foreign key behavior as well which is why I opened up #2587 and then submitted a PR (strongloop/loopback-datasource-juggler#1043) to attempt to clear it up. @gunjpan & @raymondfeng are graciously helping me out by reviewing and giving feedback. Not exactly sure if we're running into the exact same issue but it's definitely in the same vain. 

Until some documentation is added or this behavior is cleaned up I'm just always going to explicitly define my foreign key names so I can avoid running into this.

**Comment by alexkolson** [comment]
> When i created the relation using the tool, "deviceid" was added into the table of node, but in the json file foreignKey is "". So the tool is possibly not the right way to do this? or is it just buggy right now?

This is happening because `""` is falsy and loopback-datasource-juggler does something like this to determine if it was given a foreign key (this exact code snippet from [belongsTo\(https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L1249)):

```js
fk = params.foreignKey || relationName + 'Id';
```

Not sure if that helps at all. That's just why in your model definition the foreign key property is `""` but the actual foreign key getting added to your DB is `deviceid`.

I can't speak as to why the foreign key isn't camel case in your DB though.

**Comment by benjaminhon** [comment]
Hmm I think its because postgres does not support camel case names unless it's in quotes.

But I'm not sure what is happening in the background, maybe it's converting Camel case to lower case

**Comment by auxcoder** [comment]
As @benjaminhon said postgres does change columns name to lowercase, this kind of details should be pointed in docs as it frustrate people using/learning LoopBack. It's true that it is a postgres matter but the whole documentation use foreign keys in camelCase without caveat.

**Comment by damon-shaw** [comment]
I had this issue and following the recommendation from @alexkolson didn't help, although it is good practice to have both ends of the relation defined. I found that calling `.save()` on the instance for which I was trying to define a relation solved the issue:

```js
node.device(myDevice);
node.save();
```

The save part is kind of implied in the LoopBack [documentation](https://loopback.io/doc/en/lb3/BelongsTo-relations#methods-added-to-the-model), but it doesn't seem to actually behave that way.
