### ISSUE TITLE
Patch Attributes needs to be updated on default user model

### ISSUE THREAD

**Issue by devotox** [strongloop/loopback#2633]
https://github.com/strongloop/loopback/blob/master/common/models/user.json#L65

this needs to use the new updateAttributes method

**Comment by gunjpan** [comment]
@devotox : As the built-in [`user` model extends `PersistedModel`](https://docs.strongloop.com/display/APIC/Using+built-in+models#Usingbuilt-inmodels-Overview) and `patchAttributes` is an [alias for `updateAttributes`](https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L500), there seems to be no need to get that updated.

**Comment by casamia918** [comment]
@gunjpan I think devotox is right. There's a problem related with acls. 
When I inherit the built-in User model (named MyUser) and set acls like this

    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "DENY",
      "property": "updateAttributes"
    },

This acl is not working. Because, current API path 'PATCH /users/:id' is routes to 'patchAttributes' methods.  When I change the 'property' as 'patchAttributes', Now the acl is working.

But, at currently, all the loopback documents tells about 'updateAttributes', not about 'patchAttributes' or 'replaceById'. Also same in the api document.

**Comment by devotox** [comment]
@casamia918 how did you go about getting the right ACLs could you show me how your extended User Model looks like

**Comment by casamia918** [comment]
@devotox 
```
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "DENY",
      "property": "patchAttributes"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "DENY",
      "property": "replaceById"
    },
```
I found the right method name by reading built-in user models's definition json file. Normally it is located in the node_modules/loopback/common/models/user.json
