### ISSUE TITLE
slnode is spamming PRs

### ISSUE THREAD

**Issue by azatoth** [strongloop/loopback#2648]
@rmg see for example #2636 slnode is asking 4+1 times for an admin to verify the patch

**Comment by rmg** [comment]
@azatoth thanks for opening an issue for it. I'm looking into it. Unfortunately it is happening because each of those comments is actually coming from a _different_ Jenkins server/webhook. The good news is that they all respond to the same comments, so we only have to answer it once.

I'm going to see if I can disable it for some of the server/webhook combinations and have it still function properly.

**Comment by davidcheung** [comment]
Closing inactive issues, not sure where the issue should belong anyways, seems to be org wide behavior.
