### ISSUE TITLE
Can i generate a diagram for relation between models?

### ISSUE THREAD

**Issue by roxanaspataru** [strongloop/loopback#2674]
I've made the relations between models from JSON but on the db there are no relations. When i migrate the models from browser thy seem ok. Also if i try to add a rol for a user like this: 

      User.find({where:{email:"user@gmail.com"}},function(err,user){
        roles[0].principals.create({
          principalType: RoleMapping.USER,
          principalId: user[0].id
        }, function(err, principal) {
          if (err) throw err;
          console.log('Created principal:', principal);
        });
      });

there is an error saying that roles[0].principals is undefined even if roles[0] is a json.

**Comment by richardpringle** [comment]
Hey @roxanaspataru, we're actually reserving GitHub issues for bug reports and feature requests.

Please ask questions in one of the following locations: 
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups or Stack Overflow so others may benefit from the discussions)

The best thing to do is to fork [the loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and reproduce the issue in your fork. Write the steps to reproduce in the readme.md file and post the link with your question so that someone can help you out with ease.

Good luck and happy coding!
