### ISSUE TITLE
calling buildModelFromInstance does not generate model file

### ISSUE THREAD

**Issue by sonoman** [strongloop/loopback#2713]
Hi !
I have this code in a /setup route:

`var db = req.app.dataSources.mongodb;
var customer = {name: "Paul", ... }
var Customer = db.buildModelFromInstance('Customer', customer, {idInjection: true});`
I understood from documentation, that model definition file is created automatically, but I cannot find it (instance is persisted in MongoDB though...)

**Comment by jannyHou** [comment]
@sonoman I think the model would be created dynamically instead of adding files into your workspace, like inside `/common/models/`. This is the doc page I can find for [`buildModelFromInstance`](https://docs.strongloop.com/display/public/LB/Creating+models+from+unstructured+data), but it doesn't metion that any **file** will be created, can you copy me the doc or the link you referred in
 
> I understood from documentation, that model definition file is created automatically,

? Thanks.
