### ISSUE TITLE
Can't update extended model (from default User) with angular-sdk $save() method 

### ISSUE THREAD

**Issue by ggiacomo** [strongloop/loopback#2731]
Hi all,
I've a model called 'Yuser', extended from built-in User model.
When I try to update the model, using angular-sdk, I got this error
`{"error":{"name":"ValidationError","status":422,"message":"The`Yuser`instance is not valid. Details:`password`can't be blank (value: undefined)...`

This is the code inside the controller:
`
// first I retrive the user
$scope.user = Yuser.findById({ id: USERID });

// than update user from html onclick
$scope.updateUser = function(){
        $scope.user.$save();
    }`

I've tested the PUT call from /explorer and is working. Any idea?
Thank you!

**Comment by jannyHou** [comment]
@ggiacomo I haven't tried angular but I believe without angular you still could not create user instance with empty password since it's a required property in User model:
https://github.com/strongloop/loopback/blob/master/common/models/user.json#L10-L12

Please check our doc for details about how to config model property:
https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Generalpropertyproperties
