### ISSUE TITLE
Overwriting / Resetting default scope is dangerous

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback#2748]
In the documentation its described to use the following method of resetting the default scope:

```
var defaultScope = Report.defaultScope;
  Report.defaultScope = function(){};
  Report.upsert({id: reportId, 'deleted': true}, function(...) {
    Report.defaultScope = defaultScope;
    ...
  });
```

However, if this endpoint is hit multiple times in parallel we could run into the case where the defaultScope is permanently reset because the Report model in the above example is a singleton.

Is there a better way to reset the defaultScope temporarily?

**Comment by jannyHou** [comment]
@stringbeans Thank you for the updates and I am glad that you find out the problem. 
Can you try to use custom scopes instead of defaultScope? See https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes

I think you read the doc from https://docs.strongloop.com/display/public/LB/_Default+scope
It looks like a workaround to me, if we really need a feature that "do not apply default scope when upsert", we should add a config option (I mean in loopback project, in this case it's loopback-datasource-juggler), eg:
```json
"scope": {
    "order": "name",
    "limit": 100
    "where": {
      "deleted": false
    }
    "options": {
      "applyWhenUpsert": false
    }
  }

```
, then in function `upsert`, we skip applying defaultscope when the option is false.

/cc @Amir-61 This issue maybe related to dao.js. In case you are interested :)

**Comment by stringbeans** [comment]
Any updates here?

I've also noticed that the default scope will overwrite the filter passed into a model query...

Suppose we have the model definition:

```
{
  "name": "Product",
  "base": "PersistedModel",
  "properties": {
    "isActive": {
      "type": "boolean",
      "default": false
    }
  }
}
```

with the default scope definition:

```
"scope": {
      "where": {
        "isActive": true
      }
    }
```

If I try to execute the query...

```
Product.find({
  where: {
    isActive: false
  }
}})
```

... The query generated (in mysql) is matching `isActive = true`. The user specified filter should ideally overwrite the default scope and not the other way around.
