### ISSUE TITLE
Deprecate loopback-example + loopback-contrib-docs in favour of new docs site

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2776]
- [x] @crandmck Will move the docs over to loopback.io and ping @superkhau when done
- [x] @superkhau will go through usual deprecation procedures
- [x] @superkhau will modify READMEs/repos to point at the new doc site
- [x] Coordinate with @crandmck for final LGTM

cc @bajtos

**Comment by crandmck** [comment]
Actually I think I already have loopback-example content in http://loopback.io/doc/en/lb2/Tutorials-and-examples.html . It looks the same to me!

@superkhau PTAL and if it looks OK, you can deprecate/remove https://github.com/strongloop/loopback-example since it's just a README.  But be careful, because there may be links to it from elsewhere...?

**Comment by superkhau** [comment]
>But be careful, because there may be links to it from elsewhere...?

Yeah, will think about what to do here. I think we'll just add deprecation notice that points to your doc and move to sl-archive (which keeps the links intact due to auto redirection).

**Comment by crandmck** [comment]
Re https://github.com/strongloop/loopback-contributor-docs, I'm thinking about the best place to put this in the doc site. We currently have http://loopback.io/doc/community/, which is currently empty, and I propose to retitle and broaden the scope of this "space" to be for all community-related information, including contribution guidelines.  So, it would have both info on community projects and the content of loopback-contributor-docs, separated logically of course in the sidebar.

For now, I'm going to keep [info on contributing to docs](http://loopback.io/doc/en/contrib/) separate, but we might consider consolidating it as well at some point.

Thoughts?

**Comment by superkhau** [comment]
I agree with your proposal in consolidating at some point. Needs to be one simple centralized consistent document across the board. Transparency is key here as we want everyone (community and internal) to be on the same page when it comes to contributions.

**Comment by crandmck** [comment]
OK @superkhau I added the docs from `loopback-contributor-docs` to the doc site at http://loopback.io/doc/en/contrib/code-contrib.html.  I made some small formatting edits, but nothing major.

I want to rework the navigation for the "Contributing to LoopBack" space because right now it's mostly about doc contributions, and the above docs on code contributions are on their own.. I want to separate info on code vs. doc contribs more clearly.  But the basic info is there that people need.  I'll reorg it  ASAP.

Also, what about http://loopback.io/contributing/ ?  This is mostly from Al's day.... do we want to save any of that?  Should we move it to be with the above?  I think the stuff about governance is fairly important to ensure that the project operates as (and is perceived as) a legitimate OS project.
@bajtos

**Comment by superkhau** [comment]
>Also, what about http://loopback.io/contributing/ ? This is mostly from Al's day.... do we want to save any of that? Should we move it to be with the above? I think the stuff about governance is fairly important to ensure that the project operates as (and is perceived as) a legitimate OS project.

We should take the parts that are still relevant and merge it with the other doc sections. Governance should probably be in it's own subsection.

**Comment by crandmck** [comment]
> We should take the parts that are still relevant...

Sounds good.  Do you want to take a first stab at it or shall I?

**Comment by superkhau** [comment]
Go for it. Ping me later if you need review and I'll chime in directly on the PR.

**Comment by crandmck** [comment]
@superkhau https://github.com/strongloop/loopback.io/pull/81

**Comment by crandmck** [comment]
I replaced all the content in https://github.com/strongloop/loopback/wiki with links to the corresponding pages on loopback.io.

**Comment by crandmck** [comment]
Changes LGTM.

**Comment by superkhau** [comment]
Follow up issue for final cleanup tasks after lb3 release at https://github.com/strongloop/loopback/issues/2826

cc @crandmck 

Closing this issue as done.
