### ISSUE TITLE
Access additional url parameters in a GET request

### ISSUE THREAD

**Issue by cburnicki** [strongloop/loopback#2792]
Hi,

I couldn't find a solution for my problem so far. Maybe I am using a wrong approach here. The idea is the following:

I am using loopback to write a simple service to manage translations. So far, I have a model `translation.json`:

```
{
  "name": "translation",
  "plural": "translations",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "idInjection": false,
  "properties": {
    "id": {
      "id": true,
      "type": "string",
      "required": true,
      "index": {"unique": true}
    },
    "en": {
      "type": "string"
    },
    "new": {
      "type": "boolean",
      "required": true,
      "default": true
    },
    "date_created": {
      "type": "date"
    },
    "date_changed": {
      "type": "date"
    }
  },
    "mixins": {
      "TimeStamp" : true
    },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

Later on, a translation should contain more languages, not only `en` but also, for example, `es` and `fr` for spanish and frensh translations. 

Also, my translations will contain variables like `%%price%%`. A GET request for a translation should look something like `GET localhost/api/translations/:id?lang=en&price=myPrice`.
Now I would like to access my `lang` and `price` params in this GET request in a loaded hook to manipulate the loaded data (i.e. substitute `%%price%%` with `myPrice`). However, the context json in my observe method doesn't seem to contain these extra url parameters.

Any ideas on how to deal with this?

Thanks!

**Comment by Amir-61** [comment]
Hey @cburnicki,

tbh I'm not sure what you want to accomplish here.

>A GET request for a translation should look something like GET localhost/api/translations/:id?lang=en&price=myPrice.

Do you need to have this endpoint `GET localhost/api/translations/:id?lang=en&price=myPrice`? Is this ^ the requirement?

I would think indetead of having a model with many preoperties like `en`, `es`, `fr`,... it is better if you normalize your models and create another model, lets call it `language` where you would have `id`, `languageName` and ...  and change `en` from your example schema to `translatedString` or whatever makes sense and then use [BelongsTo](https://docs.strongloop.com/display/public/LB/BelongsTo+relations) or [HasOne](https://docs.strongloop.com/display/public/LB/HasOne+relations) relationships. 

However, although normalizing models makes your project neater and gives it a better structure to your models schema, you do not achieve any performance, since `join` operation is not supported for relationships, unless you use [native-sql queries](https://docs.strongloop.com/display/public/LB/Executing+native+SQL). @jannyHou may have more to add about relations and performance view...


Also please bear in mind we do aim to have GH issues just for reporting `bugs` and `features` and we would like you to ask these types of questions in our [Google-group](https://groups.google.com/forum/#!forum/loopbackjs) where you would be able to chat with many others folks about the requirement for your specific project.

**Comment by cburnicki** [comment]
Hey @Amir-61 , thanks for your answer.
The model is denormalized on purpose. However, I will close this issue and reopen a discussion in your google group within the next day or so.
