### ISSUE TITLE
Can i easy write loopback app with TypeScript?

### ISSUE THREAD

**Issue by sinegovsky-ivan** [strongloop/loopback#2812]
Can you please provide any examples of TypeScript's loopback application?

Thank you!

**Comment by jannyHou** [comment]
@sinegovsky-ivan we have an issue discussing typescript related things: https://github.com/strongloop/loopback/issues/1692

**Comment by jannyHou** [comment]
We will create checkpoint/roadmap issue in the future after we figure out a concrete plan to fully support TypeScript. And at that time we will include an example loopback app with TypeScript  in our doc and example repos.

I am closing this issue now since we haven't supported it yet, but an example will be added after we move to implement the feature. Thanks for understanding and please feel free to reopen it if you have further questions.

**Comment by kapoorji** [comment]
Hi @jannyHou, is there any update on this?

**Comment by anodynos** [comment]
Hi @kapoorji - check https://github.com/strongloop/loopback-next which is written (and consumed) in TypeScript!
