### ISSUE TITLE
bug: create model with name "host" causes swagger explorer not working

### ISSUE THREAD

**Issue by guodong** [strongloop/loopback#2828]
bug: create model with name "host" causes swagger explorer not working.
![qq20161006-0](https://cloud.githubusercontent.com/assets/858637/19137960/7d77bcd0-8baa-11e6-9744-d98da2d5add8.png)

**Comment by superkhau** [comment]
@gunjpan PTAL

**Comment by gunjpan** [comment]
@guodong : Thank you for reporting this issue. I was able to reproduce it and raised it as a bug. 
While we prioritize this issue to be fixed in our workflow, would you please like to submit a fix? 
It would be a fix to : [loopback-component-explorer](https://github.com/strongloop/loopback-component-explorer), IIRC. 

Will update this issue when fixed. Meanwhile, as a workaround, please rename your model. Thank you again.
