### ISSUE TITLE
PersistedModel findById response 404 when id is biginteger or even string type

### ISSUE THREAD

**Issue by xerobuffer** [strongloop/loopback#2840]
### Bug or feature request
- [x] Bug
- [ ] Feature request
### Description of feature (or steps to reproduce if bug)

1) define model (UserOrder for example) with id as number
2) insert a record into database with id big enough (785301454754676736 for example)
3) request from loopback explorer ( UserOrders/{id} ), 785301454754676736 as the id parameter value
4) response 404 status
### Expected result

model data of the record in database
### Actual result (if bug)

http 404 stauts
### Additional information (Node.js version, LoopBack version, etc)

loopback 2.34.1

even if id defined as string type, loopback explorer response 404. 
mybe this because in javascript language 785301454754676736 lost its precision as number

**Comment by Amir-61** [comment]
Thanks @xerobuffer for bringing this issue to our attention.

I tried with your id `785301454754676736 ` and it works for me! I could not reproduce the issue; to make the triage process faster and label this issue as a bug, could you just create a simple app with [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue?


>mybe this because in javascript language 785301454754676736 lost its precision as number

Although I could not reproduce the issue, thats what I'm thinking too if the bug is genuine.

```
> 785301454754676736 > Math.pow(2, 53) - 1
true
```

Thanks a lot!

**Comment by xerobuffer** [comment]
hi Amir-61, I add some demo codes at https://github.com/xerobuffer/loopback-sandbox.

reproduce step as follows:
1) open loopback explore, navigate to UserOrder.
2) use put (url as UserOrders/) method to insert on record into db, {"id":"785301454754676736","name":"hello loopback"} as data param value.
3) use get (url as UserOrders/{id}) method to query record, 785301454754676736 as id param value, you can see 404 errors
