### ISSUE TITLE
Add support for audit trail

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback#2872]
### Bug or feature request

- [ ] Bug
- [X] Feature request

### Description of feature (or steps to reproduce if bug)

Add support for audit-trail middleware.

Can we put this in our agenda and plan it? If yes, I'm willing to work on it... 

/to: @bajtos @raymondfeng

**Comment by bajtos** [comment]
@Amir-61 could you please extend the description with more details? What data should be stored in the audit and for which operations?

**Comment by Amir-61** [comment]
>could you please extend the description with more details?

tbh this feature requires some internal discussions; but as a high level description I would like to introduce audit-trail middleware where:
* We give the users the option which RESTfull endpoint they want to have the audit middleware active for. Or introducing `exceptions` option which makes the middleware active for all endpoints except the ones mentioned in `exceptions`
* We give them option which `req.method`s they want to have this middleware active for... I think it does not make sense to have this middleware active for `req.method == 'GET'` since this  middleware would become a bottleneck of the application and you would not get that useful information either.

>What data should be stored in the audit and for which operations?

I'm thinking of this info to be logged:

* timestamp
* method: req.method
* path: req.path
* model
* ip: req.ip
* ips: req.ips
* user: user id of the one who called the endpoint; it can be anonymous depending on ACL for that model
* PK of the model instance
* ...

Please note this is the bare minimum I could think off the top of my head and it definitely needs some internal discussions

**Comment by bajtos** [comment]
Thank you for the details, @Amir-61, I have a better understanding now. How do you envision to store the audit data? How much flexibility in the configuration do we need?

**Comment by bajtos** [comment]
I am also wondering, is this something we have to implement in LoopBack (and keep maintaining)? Another options is to provide an example showing users how they can build their own auditing middleware, tailored to their specific needs.

**Comment by archenroot** [comment]
Why is this closed? I am comming from enterprise SOA and microservices stack and common approach I apply almost everywhere is as following:
in every service pipeline 1 action is to do Audit (ENTRY) and last action Audit (EXIT), anything between happen is Audit (ERROR). Of course everyone is interested in different kind of audit information.
In my case it is always mixture of pure technical information and those with business context:
- messageId
- correlationId (if not pure CRUD API, but service which is part of complex service chain)
- domain
- subdomain
- task
- service (static description of service)
- interaction (inbound context - what component issued the call, outbound context - what target is going to be called by exit)
etc... we usually capture about 50 parameters (including optionally to capture the payload itself - in case of "message tracing" is on)

The architecture I do is usually combination of synchronous REST API (for CRUD operations or as complex process proxy endpoint - for external clients), or fully asynchronous services which doesn't expose any API over HTTP, but only communicate via message broker - here for example previous and future interaction is important, so you can reconstruct complete flow trough number of services from both technical and business perspective easily.

So I am fan of idea just introduce some generic extendable audit system in loopback which can be extended. In my case it has impact on generate REST API interface as I define input header which loopback doesn't generate from database for example.

Thanks for continue with discussion on this item.

**Comment by bajtos** [comment]
> in every service pipeline first action is to do Audit (type of ENTRY) and last action Audit (type of EXIT), anything between happen is Audit (ERROR).

I think this should be possible to implement using our existing `beforeRemote`, `afterRemote` and `afterRemoteError` hooks.

>  I would like to define common header should loopback use and enhance every service REST request schema with.

This is a missing feature we are aware of. I am not able to find the specific issue keeping track of it, the closes one I found is this: https://github.com/strongloop/loopback/issues/3116

**Comment by archenroot** [comment]
During my research on this, I have found following project today. I didn't have yet look much, but maybe:
https://github.com/yantrashala/loopback-audit-trail

Will give it a try.., but looks very basic and not much as what I expect from basic look into code...

**Comment by archenroot** [comment]
I have prepared some schemas (converted from older times when on worked for IBM on SOA implementations) just to give you better idea what I am talking about

[audit-trail-schemas.zip.zip](https://github.com/strongloop/loopback/files/856009/audit-trail-schemas.zip.zip)

**Comment by archenroot** [comment]
Following my research I found out that actually Loopback already does something similar, but in different place :-)
There is implemented context in product https://github.com/strongloop/microgateway

Microgateway actually is having some of attributes mentioned by me to capture in audittrail and they call it middleware context, the difference is that such context is for example on Oracle Service Bus available directly within the service pipeline queryable at any time, the context also changes during pipeline processing depends if you are in inbound, or outbound stage already. Imagine your input is message queue and output is database table, then in OSB you have transport related information regarding message broker available in inbound part of pipeline and database not, later once you get into outbound half of processing, the message broker context is rewriten dynamically by context data of target, in this example by database.

This is in-directly related to the AuditTrail functionality, on ENTRY you log message broker metadata, on EXIT you log database metadata, both along with some generic set of message header.

**How I see microgateway**

Microgateway is actually having capability to do audittrail because:
- it implements from description "middleware context" - I am personally missing the inbound and outbound context as OSB has
- it can transform data from JSON, XML - so i assume it could be capable of extract from the request the AuditHeader part and pass it into the message queue/topic for all instances like ENTRY, EXIT, ERROR as I am looking for.

This will move audit-trail completely out of loopback.

The only problem remaining is that I am now working on Consul and HAProxy DNSMasq, etc. for dynamic service discovery used for not only service layer, but databases, microservices in Java, applications, .etc all dockerized. So I will need to look how and if easily I could integrate microgateway into my stack. 

Anyway I think it is worth look at microgateway, as soon as I can keep the "internal" loopback services working in standard way and keep any customizable auditing outside of postgreSQL generated APIs on "external" microgateway layer.

Any hints on this are welcomed.

**Comment by bajtos** [comment]
> Following my research I found out that actually Loopback already does something similar, but in different place :-)
> There is implemented context in product https://github.com/strongloop/microgateway
> (...)
> Microgateway is actually having capability to do audittrail
> (...)
> This will move audit-trail completely out of loopback.

@raymondfeng could you please chime in and help @archenroot to figure out what is the recommended way for setting up the microgateway to act as and audit logger?

If this proves to be a viable solution, then I think we should describe our recommended setup at http://loopback.io/doc/. cc @ritch @crandmck

**Comment by crandmck** [comment]
> If this proves to be a viable solution, then I think we should describe our recommended setup at http://loopback.io/doc/. 

Sure... If so, please open an issue in https://github.com/strongloop/loopback.io.  Thanks.

**Comment by archenroot** [comment]
Thanks community and IBM guys to discuss this, I will publish solution design for this to support in Java based applications. As I use loopback as generated API layer for any SQL database I have here, that is the reason I target it for auditing as well.

I have found https://www.npmjs.com/package/log4js-loopback package. Auditing in Java is also implemented by log4j2 Markers, Custom levels and also Stream Appender (for adding not only text message, but more into log) I will try to align those 2 worlds to support same.

I will publish later on our gitlab and post link here to review (scope for next few weeks).

Thanks again.
