### ISSUE TITLE
Setting ACL for Extended User Model with DB persistance

### ISSUE THREAD

**Issue by LakshmiPrasanna-Kotagiri** [strongloop/loopback#3032]
Bug 

- [x] Bug
- [ ] Feature request

**Comment by LakshmiPrasanna-Kotagiri** [comment]
We have requirement where users mapped to admin role should be able to create users. To satisfy the requirement  , followed below steps 
1. Created Extended usermodel with DB persistence
2. Created tables related to user, acl, role, rolemapping and accesstoken
3. Created custom role "admin", have added user "BOB" to the admin role.
4. Also created John , Jane users and assigned other role.
5. Created ACL with deny access to all methods and properties for extended user model.
6. Created ACL with 
{
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "create"
    },

Issue: When logged in with user Jane or John , able to create user.  Which should not allow.

Observation : When making a change in the ACL of  Built-in user model for method create with Principal id as "admin". Jane and John who are not admin role users are not able to create users. Only BOB is able to create user.
 
As such i should not making changes to base built in user model ACL as i am overwriting the ACL. Also tried with "inheritAcls": false in Extended user model. Its not helping.

**Comment by bajtos** [comment]
@ebarault thoughts? Is this related to the recent discussion about inheriting ACLs in subclassed models?

**Comment by ebarault** [comment]
yes and no

**yes**, because the builtin user model has already the following ACL:

```js
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "create"
    },
```

as it is more specific than

```js
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
```
(let's call it `DENY * *`)
the former gets a higher score and authorizes standard users.

**no**, because it could also be solved already by defining a user role, binding it to standard users and implementing the following ACL in the extended user model:

```js
    {
      "principalType": "ROLE",
      "principalId": "user",
      "permission": "DENY"
    },
```

LoopBack ACLs scoring logic is built this way. The proper way in future inheritance would be to first override the existing ACL with  
```js
{
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "create"
    }
```

that being said i log it into the related epic so i can have second thoughts about it when defining the new model settings merge method.

**Comment by bajtos** [comment]
In the light of the above comment I am closing this issue as resolved.
