### ISSUE TITLE
Loopback passport local auth doesn't save accessToken to database .

### ISSUE THREAD

**Issue by IzaGz** [strongloop/loopback#3040]
I am tryng to use the 'loopback-component-passport' [https://github.com/strongloop/loopback-example-passport](https://github.com/strongloop/loopback-example-passport). In my own repo and in this example  loopback doesn't save neither 'accessToken' neither 'userIdentity'. Authentication is successful, in browser i can see cookies as 'connect.sid', but where can i find accessToken from server-side ?

**Comment by steinhae** [comment]
I also encountered the behavior that no AccessToken is created on the server side. To be precise it is created as it is indicated by an increased id but deleted right after. 

This behavior is caused by the latest commit to "strongloop/loopback/common/models/user.js" (https://github.com/strongloop/loopback/commit/29a17f39d5aaee9072fb42e582863766f126f911). 
Which invalidates AccessTokens on password/email change. Since the loopback-component-passport module updates the email during 3rd party login the AccessToken is getting deleted right after creation.

Commenting out line 855 in "loopback/common/models/user.js" temporarily solved the problem for me.
`//ctx.Model._invalidateAccessTokensOfUsers(userIdsToExpire, next);`
