### ISSUE TITLE
Strict validation not looking at relation references

### ISSUE THREAD

**Issue by skyserpent** [strongloop/loopback#3060]
### Bug or feature request

- [X] Bug
- [X] Feature request

### Description of feature (or steps to reproduce if bug)
When you strict an API model and set the `strict` property value in the model.json to `validate` it does a great job of validating properties. 

However, if you have a relation, it doesn't count that relation name as a property and the application is forced to add the relation name as a separate property. 

Is the current way of doing this a good/best practice approach? Shouldn't looking at relational names as properties of the model to validate against be dynamic in order to keep the code DRY?

**Comment by jannyHou** [comment]
@skyserpent Interesting idea, while IMO, it's hard to apply same validate strategy on the relation property, because you cannot manipulate it in the same way you do with a common property, e.g:

model `Customer` has a property `name` and hasOne `Address`
you can do `Customer.create({name: 'myName'})` but you cannot do `Customer.create({address: {address_instance}})`

and take some validation function as example:
https://loopback.io/doc/en/lb2/Validating-model-data.html#examples
```js
module.exports = function(user) {
  user.validatesPresenceOf('name', 'email');
  user.validatesLengthOf('password', {min: 5, message: {min: 'Password is too short'}});
  user.validatesInclusionOf('gender', {in: ['male', 'female']});
  user.validatesExclusionOf('domain', {in: ['www', 'billing', 'admin']});
  user.validatesNumericalityOf('age', {int: true});
  user.validatesUniquenessOf('email', {message: 'email is not unique'});
};
```
none of the functions could be applied on a relation property.

/cc validation experts: @Amir-61 any thought?
