### ISSUE TITLE
customise error for ACL denying response

### ISSUE THREAD

**Issue by IzaGz** [strongloop/loopback#3092]
now its constantly sends 401 :
```
 "status": 401,
    "message": "Authorization Required",
```
issue to enable custom acl errors for specific method is required

**Comment by pierreclr** [comment]
hi @IzaGz, you can easily catch your errors at an higher level for example with `MyModel.afterRemoteError()` and define the comportment you need.

I did it to handle the (403 forbidden) when a user try to access a ressource without the rights to do so instead of (401 Authorization Required) in loopback by default

**Comment by HugoPoi** [comment]
For the few of us arriving here.

You doesn't need to use `MyModel.afterRemoteError()` for sending a different HTTP error code when a user is logged but doesn't have rights to access the resource. You can use `aclErrorStatus`
 option in your model.

In your model.json add this
```
"options": {
  "aclErrorStatus": 403
}
```

With this configuration you will have 401 when the user is not logged and try access a protected resource, and 403 when he is logged but haven't the needed roles/rights.

This behaviour has been discuss and implement in https://github.com/strongloop/loopback/issues/301 but not really well documented.
