### ISSUE TITLE
Exported Swagger file does not include host token

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback#3096]
### Bug/Feature request

Export Swagger via slc loopback:export-api-def.

### Expected result

The generated swagger should contain a ${host} token. It does not.

**Comment by bajtos** [comment]
This is intentional behaviour. 

Swagger spec explicitly allows hostname/port to be undefined, in which case the client should make the request to the same hostname/port where the swagger spec was fetched from. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields

> The host (name or ip) serving the API. This MUST be the host only and does not include the scheme nor sub-paths. It MAY include a port. If the host is not included, the host serving the documentation is to be used (including the port). The host does not support path templating.

Users wishing to set Swagger `host` to a certain value can set `swagger.host` in `server/config.json`, see https://github.com/strongloop/loopback-swagger/pull/47

**Comment by cfjedimaster** [comment]
Ok, but why (and I didn't test this, I was just told this) does APIC output ${host}?

**Comment by bajtos** [comment]
My guess is that since APIC manages the whole lifecycle of an API server, it knows the host where the app is being deployed and therefore it can provide that value in Swagger.

In vanilla LoopBack, where apps are run via `node .` (or preferably a process-manager like `strong-pm` or `pm2`), possibly behind a load-balancer like `nginx`, or even another gateway, it's difficult for the application to tell what's the host to advertise to Swagger consumers. This host may be even different depending on where is the consumer located - e.g. general public uses hostname of the internet-facing gateway, while internal company users can skip this extra layer and access the service at a different, internal hostname.

I think the more important question here is what `apic loopback:refresh` does? Does it create such Swagger YAML file that when the app is deployed via APIC, the API docs provided by APIC management portal show the correct URL?

**Comment by cfjedimaster** [comment]
Your comments make sense. Unfortunately I've got nothing for your question though. :)
