### ISSUE TITLE
Backbone support

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#318]
Is this on the roadmap? Otherwise, it would be great to have more documentation on using the 'raw' client-side support that's already provided (browserify workflow regarding models?), and what the Angular client actually solves on top of that. This would make it easier to implement support for other client-side frameworks (or no framework usage at all).

**Comment by brillout** [comment]
in the meantime you can do something along the following to use the AngularJS JavaScript SDK for other frameworks;

https://gist.github.com/brillout/8c2cd10404d915974242

**Comment by bajtos** [comment]
Hello, as part of our triage process, I am closing issues that have been inactive for extended period of time. 

While I see the importance of a Backbone.js SDK, I am afraid it's not a priority for us now.

If anybody from the community would like to contribute this SDK, then please leave a comment here so that we can help you to figure out details.
