### ISSUE TITLE
remote method PersistedModel.diff only receives one parameter [revisited]

### ISSUE THREAD

**Issue by mrjrdnthms** [strongloop/loopback#3188]
As far as I can tell there is a bug in the way PersistedModel sets up the diff remote method. I think @jouke was corrected when he assessed that "setRemoting is defined for remoteChanges with http: { source: 'body' }, and 'since' is not. I then discovered that strong-remoting only sets one parameter in the request body when it's defined like this."

I have created a pull request to fix this issue. Its a simple fix. The original issue opened by @jouke was closed due to inactivity. I will be response. Need it fixed :)

Original Issue:
[https://github.com/strongloop/loopback/issues/2223](https://github.com/strongloop/loopback/issues/2223)

Pull RequestL
[https://github.com/strongloop/loopback/pull/3189](https://github.com/strongloop/loopback/pull/3189)

**Comment by bajtos** [comment]
Hello, I am afraid I am still not able to reproduce the problem you are trying to solve. Please take a look at  https://github.com/strongloop/loopback/commit/8b8713e34b0baae333d7499828ddd81e078c013 which shows a test that invokes `diff` with `since` argument via the REST API and passes with the current implementation, therefore verifying that `diff` works correctly already.

I believe there is something else wrong in your application. 

To move this discussion forward, I need you to provide a small application reproducing the issue, see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
