### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridis-com** [strongloop/loopback#3199]

**Comment by zbarbuto** [comment]
Agree 100%. And this is only issues in the main loopback project. This doesn't include the data source juggler and various other connectors and components (the Postgres connector has 50 open issues and 19 open pull requests has been barely touched in months). It would be great if strongloop was a bit more open about what their priorities are and why so many issues (in some cases major ones) are left open and untouched for years.

**Comment by superkhau** [comment]
@lazaridis-com @zbarbuto We've been at this issue for awhile now and I've brought this up many times as one of our top priorities. I've been advocating opening up many of the repos to community so that members like you can help triage/maintain issues, docs, etc etc. Make it more open to the general public so that we can scale accordingly. There are discussions of what to do going forward with the next version of LoopBack -- no formal plans yet but there have been strategy discussions. Opinions are welcome -- I'll see what I can do to get your voices to the right people.

**Comment by bajtos** [comment]
Inspiring reading: http://words.steveklabnik.com/how-to-be-an-open-source-gardener

**Comment by lazaridis-com** [comment]
@bajtos , nothing could be of less relevance (to me) than ruby related material.

And subjecting Issue Management, you need just 2 words to keep issues under control:

**Professional Pride**

It's a matter of **professional pride**, to have a projects issue-tracker in a clean and rational state. 

Member should always try to kill issues by relevant check-ins.

Managers should reduce issues, by grouping them together (e.g. into relevant functionality/features).

Security related issues should be naturally fixed, immediately, zero delays.

-

I cannot understand why #382 is unprocessed. Does e.g. IBM use an alternate code-base? Or do they have security holes in their solutions?

You really need to clarify all this, as this can create much distrust in loopback. See, I've pre-selected loopback, as it seems to be the only relevant api-tool. But all those issues... very strange!
