### ISSUE TITLE
Recent loopback (2.X) update broke the updateAttributes / patchAttributes behaviors

### ISSUE THREAD

**Issue by pierreclr** [strongloop/loopback#3278]
Hi,

We recently encounter a problem related to `disableRemoteMethod` / (patch|update)Attributes : 

I have a mixin wich disable every remote methods excepted those whitelisted in mixin options. Our API is covered by tests which suddenly  were broken despite the fact that we fix dependencies version. The problem was the following : calling `disableRemoteMethod(patchAttributes, false)` disable updateAttributes too which was not the case until yesterday. 

I tried to find last backported commits but I can't understand what changes imply such a new behavior ... However, how do you apply some commits on previous loopback version ? Is there any channel we can subscribe to be notified of important changes ? 

Thank you

LB VERSION : 2.36.0

**Comment by bajtos** [comment]
Hello, thank you for reporting this issue. The change you are observing was an intentional bug fix - see #1936 and https://github.com/strongloop/strong-remoting/pull/395.

> However, how do you apply some commits on previous loopback version ? 

Yes, we are backporting most bug fixes that are backwards compatible. In my opinion, the intent of `disableRemoteMethod('patchAttributes', false)` is to disable the `updateAttributes/patchAttributes` endpoint, therefore arguably the change caused the code to behave as it was intended to. Even if it changes observable behaviour, which is unfortunate :(

> Is there any channel we can subscribe to be notified of important changes ?

Yes, based on community feedback, we started a low-volume announcements mailing list: https://groups.google.com/forum/#!forum/loopbackjs-announcements

This particular release was announced in this post: https://groups.google.com/forum/#!topic/loopbackjs-announcements/Ut_MF4mUszQ
