### ISSUE TITLE
Migration from Loopback 2.X to 3.0

### ISSUE THREAD

**Issue by DAVIDFlavien** [strongloop/loopback#3281]
Hi there,

I recently tried to migrate my project from Loopback 2.X to 3.0 and I got some error regarding validation on an embeded model. However, if I set `validate: false` in the model definition, it does work. Does anyone of you had the same issue while migrating ?

**Comment by loay** [comment]
Hi @DAVIDFlavien 
Here is a documentation that you will need to follow:
https://loopback.io/doc/en/lb3/Migrating-to-3.0.html

If you are still having troubles, can you please provide a sample repo for your app, so I can reproduce and debug? Thanks.

**Comment by pierreclr** [comment]
@loay It's should be a 'bug' label not 'triage'. We are not the only ones who encounter this problem. (Cf Loopback channel on Gitter)

@bajtos Are you aware of what changes imply such behavior ?

**Comment by bajtos** [comment]
@pierreclr The "triage" label means that we are gathering information about the issue, to make sure we understand the problem and can reproduce it on our machines.

That's why we need you to provide us with clear and complete steps for reproducing the issue you are experiencing - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

> Are you aware of what changes imply such behavior ? 

Nothing comes to my mind right now. We will know better once we can reproduce and debug the issue.

> However, we would like to know how far embeds(One|Many) relations are supported by StrongLoop.

We do support embedded relations the same way as other LoopBack features. Unfortunately, the initial implementation contributed by the community was less complete than is our usual standard, therefore there are more issues to fix.
