### ISSUE TITLE
date format not consistent before persist

### ISSUE THREAD

**Issue by autovipdeveloper** [strongloop/loopback#3294]
# Description/Steps to reproduce
mixins / timestamp.js
```
Model.observe('persist',function(ctx,next){
	ctx.data.modified = Date.now();  //modified: 1489986925985, ends up being stored as null 
	next();
})
Model.observe('before save',function(ctx,next){
	ctx.data.modified = Date.now();  //modified: 2017-03-20T05:14:16.471Z
	next();
})
```

# Expected result
date format should be consistent

**Comment by bajtos** [comment]
Hello, thank you for reporting the issue. How is your model defined? If `modified` is defined as `{ type: 'date' }`, then your `persist` hook is probably incorrect - you should call `new Date()` instead of `Date.now()`.

```js
Model.observe('persist',function(ctx,next){
	ctx.data.modified = new Date(); 
	next();
})
Model.observe('before save',function(ctx,next){
	ctx.data.modified = new Date();
        next();
})
```

Having said that, I see your point about inconsistent behaviour. Unfortunately I am not sure if we actually can detect this situation in our code.

**Comment by bajtos** [comment]
Closing as abandoned.
