### ISSUE TITLE
Modify model data during loaded hook

### ISSUE THREAD

**Issue by timlind** [strongloop/loopback#3336]
# Description/Steps to reproduce

Add a property in a loaded hook, onto ctx.data

# Expected result

Find property on the client http response. This does not seem to be happening.

# Additional information

postgresql connector

**Comment by timlind** [comment]
It doesn't help that remote hook are not run when the model is accessed directly as a relation on another model: #737 

It also doesn't help that remote hooks don't run when a model is included via another model's rest endpoint.

**Comment by sidewaiise** [comment]
I'm having this same issue. However I'm able to register the 'loaded' event when the model in question is being included by a related model.

The problem is that the data does not seem to return in it's modified form. Works fine when querying a single instance but not when you get an array of items.

**Comment by Goblinlordx** [comment]
I actually am having the same problem except I am seeing across any type of 'loaded' event.  The hook is called when I query for 1, multiple, or when I include the model.  The problem is this the modified data is not what is returned.  I have a [stackoverflow question posted here](https://stackoverflow.com/questions).

**Comment by Goblinlordx** [comment]
So I after some digging around the source, I found the issue for me.  The property I was seeing being returned in the response had a default value set on the model.  In `loopback-datasource-juggler` on [`allCB`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2005), after notifying listeners of `loaded` it then calls `buildResult`.  When `buildResult` is called it will create a [new Model instance](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2023).  This presumably is where default values get set (based on what I was seeing when I added some logging).

Regardless, I feel this is pretty much unexpected.  I would expect that a default value would be set when I created/updated some data in the database.  When I return the result I would expect I could purposefully remove that data and it would not be shown (similar to what is shown as an example in the [docs here](https://loopback.io/doc/en/lb3/Operation-hooks.html#operation-options)).  In fact, the docs seem to make no mention of this being potentially problematic.
