### ISSUE TITLE
Remove "noise" during model creation

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback#3421]
# Description/Steps to reproduce

Create a new model from the CLI. When it asks you for a property name, enter one, and notice the CLI says:

invoke loopback:property

This seems to have no purpose. I'm assuming it is debug output. Here is an example from another repo readme:

![screenshot](https://raw.githubusercontent.com/emckean/jeopardy-mongo-api/master/readme%3Aimages/LoopBack-model3.png)

See the output? It is just noise.

# Expected result

Remove it. ;)

**Comment by cfjedimaster** [comment]
Re-open.

**Comment by bajtos** [comment]
@cfjedimaster I have reopened the issue per your request. I think that this won't be an easy change, because I believe those extra lines are printed by yeoman, which we have only limited control of. (See also https://github.com/strongloop/loopback-next/issues/844.) Considering our limited bandwidth, I find it unlikely that we will have time to fix this issue ourselves.
