### ISSUE TITLE
No control over order of remotes().before hook

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback#3434]
I have two hooks attached to remotes().before, like so:

```js
app.remotes().before('*.*', test1)
app.remotes().before('Company.someAction', test2)
```

Regardless of which order I put them in, test2 always runs before test1.  What is the intended order of operation of these hooks?  Should I be able to control it by changing the order I define them in?

**Comment by bitmage** [comment]
I did some more testing.  The order is predictable as long as I have multiple hooks with the `*.*` pattern.  As soon as I introduce a more specific pattern though, it runs before any of the general hooks.

To work around this, I've implemented a custom 'before' hook that intercepts everything with `*.*` and lets me do my own matching.

```js
const _ = require('lodash')
const matchOrStar = ([p, s]) => p === '*' || p === s
const match = (pattern, string) => {
  if (!~string.indexOf('.')) return false
  const matchup = _.zip(
    pattern.split('.'),
    string.split('.')
  )
  return _.every(matchup, matchOrStar)
}

// Define a custom before hook because loopback changes the ordering based on the specificity of the pattern.
// We don't want that!
const before = (pattern, cb) => {
  app.remotes().before('*.*', (ctx, next) => {
    match(pattern, ctx.methodString) ? cb(ctx, next) : next()
  })
}

before('*.*', lookupAccountId)
before('Company.scan', cacheStuff)
```

This works, but it's pretty disapointing that I have to jump through these hoops.

**Comment by bajtos** [comment]
>  The order is predictable as long as I have multiple hooks with the *.* pattern. As soon as I introduce a more specific pattern though, it runs before any of the general hooks.

I believe this is by design: we run more specific patterns first, before running general patterns like `*.*`. See strong-remoting's [lib/remote-objects.js](https://github.com/strongloop/strong-remoting/blob/8b9f6fc01bda90aae1510aa719efa35223476074/lib/remote-objects.js#L452-L646)

@raymondfeng @ritch could you please confirm?

If you want to setup a "before" hook that's always executed before any other "beforeRemote" hooks, then you should use a custom strong-remoting phase as explained here: https://loopback.io/doc/en/lb3/Using-current-context.html#use-a-custom-strong-remoting-phase
