### ISSUE TITLE
problem to handle data from [include] in a query (because is a function)

### ISSUE THREAD

**Issue by kamilml** [strongloop/loopback#3480]
I am doing this `User.login(credentials, 'user', callback)` and getting a correct response with the token value, id, ttl, and a user object with all the data of that user instance.

`console.log(token)` give me this:
```
{ ttl: 300,
  userId: 5963bbe610dcbb27d812045e,
  created: 2017-07-10T19:33:39.119Z,
  id: '8qxNRBpxwzQFU9qssAHcCy7RSHr0rX1RbEDI4HQ1mfnc3aYTBZSZ9uzT7FVGW2zh',
  user:
   { username: 'Brewmaster 89162',
     avatar: 'img.jpg',
     password: '$2a$10$g5fBCW8z7XrNu.L.JvO01e/DKeODv98eGG1G4ZhcrddNmpGkxX79i',
     email: 'asd@asd.asd',
     id: 5963bbe610dcbb27d812045e } 
}
```

But I want to handle the user object. Making another object with some values from this. But I cant take any value of `user`. For example `token.user.username` is undefined.

`console.log(token.user)` give me this:
```
{ [Function: bound ]
  getAsync: [Function: bound ],
  update: [Function: bound ],
  destroy: [Function: bound ],
  create: [Function: bound ],
  build: [Function: bound ],
  _targetClass: 'User' }
```

Help me please :(

**Comment by Setogit** [comment]
@kamilml   I'm curious to see what `token.user.getAsync()` returns.

**Comment by kamilml** [comment]
@Setogit `token.user.username` return a promise, then i do `.then()` (also `.catch()`) to catch the response/error but I'm getting null 
![error](http://i.imgur.com/XGK6Be0.png)

**Comment by kamilml** [comment]
what happened with my question? :(

**Comment by SippieCup** [comment]
If you use callbacks rather than promises, does it work as intended?

**Comment by kamilml** [comment]
@SippieCup can you give me an example of how should be the callback for this please? :)

**Comment by kamilml** [comment]
I still have not found solutions for this :(

**Comment by SippieCup** [comment]
@Kamilml,

Sorry about not responding earlier, I didn't see your response.

`res.user` is a model which is yet to be instantiated and the output from console.log(res) is lying to you for logging purposes. It'll print the data which will be sent back to the client, not the current object.

`res.user` is actually a constructor, so you need to call it in order to get any data from it. Furthermore, and what probably confused you, is that this constructor does not support promises, so you have to use a regular callback.


Here's an example of how you should be doing it, please note that Employee is an extension of the User model:
The code that is being run:
```
router.post('/login', function(req, res) {
    Employee.login({
      email: req.body.email,
      password: req.body.password,
      ttl: 300
    }, 'user')
    .then( (response) => {
      console.log("\nthis output is lying to you. this is what will be returned to the client:")
      console.log(response); 
      // This fails because user is not yet truely instantiated.
      console.log(`\nEmail from user before instantiation: ${response.user.email}`)
      // To get data from user, we must call the user property as a function to instantiate it.
      // for some reason response.user() does not support promises, so you have to put it in 
      // a callback
      response.user(function(err, userData) {
        // now you can access data from the included `user` model
        console.log(`Email from user when instantiated: ${userData.email}`);
      });
    })
    .catch( (err) => console.error(err));
  });
```
basic console logging will print the following:
```
┌─[sid@dev01] - [~/Source/AnApp] - [Tue Oct 03, 10:25]
└─[$] <git:(master*)> node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

this output is lying to you. this is what will be returned to the client:
{ ttl: 300,
  userId: 77,
  created: 2017-10-03T14:25:13.234Z,
  id: 'sifC6iycomQArgb0jiSPwlh8febQflgLKCmTcvGdvh3mm6swEFENU6ygj9eonbjG',
  user:
   { emailVerified: true,
     password: '*snip*',
     employeename: ''*snip*,
     initials: ''*snip*',
     email: 'asidhu1@gmail.com',
     username: 'sid',
     verificationToken: null,
     id: 77 } }

Email from user before instantiation: undefined
Email from user when instantiated: asidhu1@gmail.com
```

If you want to see what the current object actually is, you have to attach it to a debugger. When you do that you can see what loopback is hiding from basic console.log calls.

![debugger](https://user-images.githubusercontent.com/679311/31130576-c85fd5c8-a825-11e7-8e78-3982a466bc14.png)


I hope this helps. Let me know if you have any other questions.

**Comment by kamilml** [comment]
@SippieCup I copy/paste your example but I got this :(

![error](https://i.imgur.com/b11FC27.png)

**Comment by SippieCup** [comment]
I'd double check to ensure you did everything correctly, it's probably a race condition.
