### ISSUE TITLE
In which phase the login's access_token is validated

### ISSUE THREAD

**Issue by aliartiza75** [strongloop/loopback#3535]
I have used ACL for my end-point and I want only authenticated users to access my end-point. ACL for my endpoint is: 
"acls": [
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "getInstances"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "getInstances"
    }
  ],

I have also defined three middle-wares that validates the POST data for my end-point. I use the endpoint in the python like this:

resp = requests.post('http://0.0.0.0:3006/api/Users/login',json=User_data);
from the resp object I get the access token
Using that access token I make request on another endpoint
resp = requests.post("uri?access_token="+access, json="json_data")

But the issues I am facing is that when I make request using access token. The request passes through my middle-wares. I want to know in which phase the access_token is validated? Before making request on the endpoint.

Thank you

**Comment by sebastianfelipe** [comment]
Is in the 3rd phase, it is called "auth" -> https://loopback.io/doc/en/lb2/middleware.json.html#phases. There you can change the AccessToken model for a CustomAccessToken model (that you can define by your own). You have to be careful with the $owner role because is not working. You can disable that validation step commenting the line "server.enableAuth()", inside the boot/authentication.js in your project.
