### ISSUE TITLE
Setting up sub-domain as an application realm

### ISSUE THREAD

**Issue by karan-kapoor90** [strongloop/loopback#3558]
I'm trying to create an application that has support for Organizations. In doing so, I'd like to isolate users from different organization using realms. Hence the end result would be 
**Company A**
Application URL : https://a.myapp.com

**Company B**
Application URL : https://b.myapp.com

Such that both "a" and "b" are separate organizations with their own distinct user realms.

Any hints on how this can be setup would be greatly appreciated! 

Regards

**Comment by kjdelisle** [comment]
@karan-kapoor90 This sounds like something that would be managed at a different level entirely.

You might have large, distributed clusters of your application(s), along with routers to spray your traffic across those instances.

Treating those clusters as logical application instances would be dealt with using API management software like [API Connect](https://developer.ibm.com/apiconnect/) or [Apigee](https://apigee.com/api-management/) would be used for managing API access for individual customers (the companies in your example).

There are certainly many ways to accomplish this, but in all of them, LoopBack would only be a small part of the final tech stack, IMO.

If you have any questions about using API Connect, check here: https://www.ibm.com/developerworks/

Hope that helps. :)

**Comment by karan-kapoor90** [comment]
@kjdelisle Thank you for the response. I know its not related to loopback per say but are there any resources to which maybe you could direct me so I can do this?
I understand that all customer will user the same api.myapp.com to access the Public API's I create using loopback, and those same API's are what the mobile app and the web frontend would also use, but I don't quite understand how the API Gateway fits into the picture overall, where it sits and how the subdomain logical separation happens. 

PS: I was able to use the subdomain express module to add that capability to the loopback server but I'm not sure how I can get that to work with user realms - each realm on a different database schema.

**Comment by kjdelisle** [comment]
>I understand that all customer will user the same api.myapp.com to access the Public API's I create using loopback, and those same API's are what the mobile app and the web frontend would also use...

@karan-kapoor90 Actually, that's not what I was saying. Tools like API Connect/Apigee would be _in front_ of those endpoints, directing traffic to those services/microservices based on policies and configuration you would make on your API management suite.

In this use-case, you wouldn't want to make the application handle this sort of thing, because it means you'll have to make each of your individual applications handle it as it comes up. The major advantage to tools like API Connect is that they allow you leverage common policies like security, access, billing, etc without having to bake all of that into each of your individual apps.

Check these links out for help with API Connect, you can try it out on Bluemix for free:
https://developer.ibm.com/apiconnect/resources/category/getting-started
https://developer.ibm.com/apiconnect/resources/category/diving-in

**Disclaimer**: I work for IBM, so naturally I'm going to plug API Connect for this sort of thing, but if you were looking for alternatives, there's [Apigee](https://apigee.com/api-management/), [Kong](https://getkong.org/), and a whole host of others you can find here: http://alternativeto.net/software/apigee/

**Comment by bienek** [comment]
I think the question was more related to loopback and not so much towards multiple applications (but rather a single application supporting multiple organisatons).

@karan-kapoor90  did you already find a solution for your loopback application? Reading the resources above about API management software didn't show me an approach. Unless you have separate instances for every organization you still need to separate your models within your application.

**Comment by minasvisual** [comment]
Me too! Please share your solutions. thanks
