### ISSUE TITLE
How to access custom method with related model?

### ISSUE THREAD

**Issue by EveX1** [strongloop/loopback#3612]
# Description
First please apologize my english.

I'm trying to access a custom remote method of one of my model with a related model.

I've created 3 models in Loopback which are related this way:

`User hasMany Shop` & `Shop belongTo User`

`Shop hasMany Credit` & `Credit belongTo Shop`

`User.nestRemoting("shops")` for `User` to reach `Credit` through `Shop`, `User` being the main entry point for the API.

`Credit` can be bought by a `User` for a `Shop` to execute some actions which cost `Credit`.

I've also created a custom remote method for `Credit`: `availableCredit(shopId)` which sum the `Credit` being available (those bought by `User` for a `Shop`and those spent by a `User` for a `Shop`).

    Credit.availableCredits = (shopId) => {
        return new Promise((resolve, reject) => {
            // return credits from DB related to a shop
            Credit.find({
                where: {
                    shopId: shopId
                }
            })
            .then(credits => {
                // Here is my logic which resolve an amount of available credits
            })
            .catch(err => {
                reject(err);
            })
        });
    }

I've registered my custom method in `credit.json` and it went fine.

    "methods": {
        "availableCredits": {
          "description": Returns the available credits for the shop",
          "accessType": "READ",
          "shared": true,
          "http": {
            "path": "/available",
            "verb": "get",
            "status": 200
          },
          "accepts": [
            {
              "arg": "shopId",
              "type": "string",
              "description": "shop id",
              "required": true
            }
          ],
          "returns": {
            "arg": "credits",
            "type": "number"
          }
        }
      }

Thanks in advance.

# Expected result
Everything works BUT my custom method DOESN'T show on API Loopback Explorer under `shops` or `user`.

I do see and have access to all the build-in methods like (in user):

    GET /users/{id}/shops/{nk}/credits

Or my custom method in credit:

    GET /credits/available

but I DON'T have

    GET /users/{id}/shops/{nk}/credits/available

nor

    GET /shops/{id}/credits/available

# Additional information

Question first opened on Stack Overflow last week, but nobody could help me:
https://stackoverflow.com/questions/46117324/loopback-how-to-access-custom-method-with-related-model
NodeJS v7.10
Loopback 3.9.0

**Comment by sebastianfelipe** [comment]
How did you define the nestRemoting relations? Where?. I'm still without seeing the extended paths in my loopback explorer (trying to reproduce it).

**Comment by EveX1** [comment]
Hi @sebastianfelipe !

You can init nestRemoting in the /server/boot/ folder. I created a initNestedRelations.js there, but name is up to you.
Here is the code:
```
'use strict';

module.exports = function(app) {
    app.models.use.nestRemoting('shops');
};
```

**Comment by EveX1** [comment]
As is said in my first post (lastest line), I do not have

```javascript
GET /shops/{id}/credits/available
```

**Comment by sebastianfelipe** [comment]
Ok, less it would be appear as a nest remoting relation, I don't know the exact definition to extend a custom remote method, yesterday I have a look to the persisted-model.js file to find the methods are defined in the way they could be passed to the next level.

I asked you about how you get that the endpoints appear in your explorer, because I've tried and never could' get them, but that's other problem.

In your comment above @EveX1, "nestRemoting" method doesn't belongs to "app.models.use". Are you sure you defined it as you say? I have defined it like this (to an example -> Book hasMany Chapter, using a server/boot/nest-remoting.js):

```javascript
'use strict'

module.exports = function(Server) {
  var Book = Server.models.Book;
  var Chapter = Server.models.Chapter;
  Book.nestRemoting('chapters');
}```

But Server.models.use is undefined (or app.models.use).

**Comment by EveX1** [comment]
My bad, I did a typo. It's:

```javascript
'use strict';

module.exports = function(app) {
    app.models.user.nestRemoting('shops');
};
```
where `user` is my user model based on `User`.
So basically it works with anything like:
```javascript
    app.models.<anyModel>.nestRemoting('<anyOtherModel>');
```

**Comment by sebastianfelipe** [comment]
Althoug this is nor related with nestRemoting, it was an update of the loopback-component-explorer few minutes ago that solved some issues related with restRemoting [https://github.com/strongloop/loopback-component-explorer/issues/167#event-1251549231](url). Well, but your issue is not related with nestRemoting and probably is not a problem. I think is a feature request.
