### ISSUE TITLE
ctx.currentInstance in 'before save' of a model with embedsMany relationship

### ISSUE THREAD

**Issue by solasky** [strongloop/loopback#3624]
# Description/Steps to reproduce

We have 2 models related via an embedsMany relation such that:
ParentModel.json

{
  "name": "ParentModel",
  "base": "PersistedModel",
  "properties": {
    "name":{
      "type": "string",
      "required": true
    }
  },
  "relations": {
    "childModels":{
      "model": "ChildModel",
      "type": "embedsMany"
    }
}
ChildModel.json

{
  "name": "ChildModel",
  "base": "Model",
  "properties": {
    "name":{
      "type": "string",
      "required": true
    }
  }
}

We would like to get the currentInstance of ParentModel before change in the ParentModel's before save hook when we create a ChildModel under a ParentModel using api
POST /api/ParentModels/{id}/childModels
data : {
  "name": "child name"
}

    ParentModel.observe('before save', (ctx, next)=>{
      const currentInstance = ctx.currentInstance;
      next();
    });

 However, the currentInstance contains the new posted ChildModel as below:
{
  "name": "my name",
  "childModels": [{
    "name": "child name"
  }]
}

# Expected result

The currentInstance in before save hook should be
{
  "name": "my name"
}
Cause we want to diff 2 objects in after save hook to know exactly the changes.

# Additional information

**Comment by sebastianfelipe** [comment]
No, you're wrong. If you want to achieve that, first, you need to use an observe('before save') or 'after save', but in the embedded model. Not in the parent model (at least using the ctx.currentInstance or ctx.instance). If you want to receive the data only, try with ctx.data. In other case, you have the solution you propose in but in the child (or embedded model), instead of the parent (if you have a list of embedded models, be careful with set the parent validate child-options to true, because is highly cost, every time you post/put a new instance, it reviews every embedded instance again. In that case setting parent child-validation to false, the validation checked the last instance. Asumming you have the validate options active in the child model).
