### ISSUE TITLE
'currentInstance' is undefined in 'before save' hook

### ISSUE THREAD

**Issue by taimoor736** [strongloop/loopback#3700]
As per the documentation of version 3 it says that in 'before save' hook the context parameter of its callback function contains a property with name 'currentInstance'. But it always gives me undefined.
I don't know if documentation is wrong or its a bug.
I am getting this error while performing update on multiple instances.

here is my code

> myMode.observe('before save', (ctx, next) => {
>     console.log('@@@', ctx.currentInstance)
>    next();
> });

Please help me out with this.
Thank You.

**Comment by viguirilo** [comment]
It seems that this property was changed to `instance`.

I have tried every operations involving saving instances into my test model and in every response, I have received `ctx.currentInstance = undefined`.

So, I concluded that the docs are out of date.

**Comment by taimoor736** [comment]
Thanks for the reply @viguirilo. Please update the docs.

Thank You.

**Comment by Harry97** [comment]
@viguirilo @taimoor736 `instance` is yeilding `undefined` :disappointed: Am I missing something?

**Comment by developermhayden** [comment]
As of version 3 (I believe I did not see this in version 2), you will see 'currentInstance' on the ctx (context) when you are performing a PATCH.

PUT requires the complete collection item.
PATCH only edits specific properties in the collection Item.

Which is why you don't see ctx.currentInstance on a PUT request, it is assuming you are overwriting the complete collection and not just a property in the collection.
