### ISSUE TITLE
Boolean type allways return true

### ISSUE THREAD

**Issue by Rikhart** [strongloop/loopback#3759]
I have a proble with loopback 3, when use boolean types allways return true, I can change the state of my property via PUT or PATCH method, how I can solve this trouble. Thanks for your answers.

**Comment by EnzoBer** [comment]
same here 
`{
  "name": "dim_carrefour",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "CAR_PK": {
      "type": "number",
      "required": true,
      "id": true
    },
    "CAR_DESC": {
      "type": "string",
      "required": true
    },
    "CAR_MODE_PILOTED": {
      "type": "Boolean",
      "required": true
    }
  },
    "validations": [],
    "relations": {},
    "acls": [],
    "methods": {}
}`
My model 

`[
  {
    "CAR_PK": 0,
    "CAR_DESC": "string",
    "CAR_MODE_PILOTED": true
  },
  {
    "CAR_PK": 5,
    "CAR_DESC": "string",
    "CAR_MODE_PILOTED": true
  },
  {
    "CAR_PK": 8,
    "CAR_DESC": "test3",
    "CAR_MODE_PILOTED": true
  }
]`
The response body

**Comment by jalgsg1** [comment]
The problem is because loopback boolean only check if the field in your database is null or not. Thus, if you have any value, ( 1, 0, some different to null) it will return true. One possible solution is use a Number type in loobback instead, a tinyint(1) instead and then in the code, compare with a number directly. Hope this help.
