### ISSUE TITLE
Duplication problem for custom logic in before remote hook for related model.

### ISSUE THREAD

**Issue by Chinmayans44** [strongloop/loopback#3797]
I am facing this issue of duplicating custom logic in "before remote" methods.
I have two models customer and email, which are related as hasMany relation.
Currently my custom logic is based on body of request that is made.
If request has lets say got two emails with same email Ids, I need to throw error.
This logic is implemented now in before remote of both email and customer models. I need to move the code to common place where in both related model API customer/email and Email/ should validate logic.
I tried to write logic in before save hook(which will be called in both related model API and Direct Email model API ), but I am not able to get whole body that is passed.
lets say if two emails are passed, I could not get both emails at once in before save
(If two emails are passed "before remote" is called once, and "before save" is called twice).
I need to get all body passed at once so that i can do validations on all body passed before hitting DB.
Is there any way to write logic in common place , and need to get whole body at once, so that i can do validations required. (Validation is based on all body passed ,Ex: can find duplicate email Id present in input body)
Any suggestion on writing custom logic  at one place in before remote hooks?

**Comment by bajtos** [comment]
I am afraid you cannot avoid having two before-remote hooks to accomplish what you want. However, you should be able to move the actual implementation to a single method that's shared by both hooks. 

A mock-up to illustrate my point:

```js
function validateNewEmails(/*...*/) {
  // ...
}

Customer.beforeRemote('__create__emails', validateNewEmails);
Email.beforeRemote('create', validateNewEmails);
```

Having wrote that, I feel that your approach is rather brittle. Let's say your hook is going to reject a request trying to send Email1 and Email2 when they both have the same id. But what happens when the client attempts to send those very same emails in two (parallel?) requests instead? Your remote hook will be invoked twice and won't detect the duplicate id.

I think you should rework the design of your email validation and for example move the "unique id" constraint to your database layer.

Anyhow, you have much better understanding of the application you are building than I am, feel free to ignore my advice.

I hope the code example shown above answers your question.
