### ISSUE TITLE
userId is NaN in CustomAccessToken model

### ISSUE THREAD

**Issue by blacktrue** [strongloop/loopback#3812]
Hi everyone

I have a model user extends from User model and CustomAccessToken extends from AccessToken.
Change the property id from user model

```
"id": {
      "id": true,
      "type": "string",
      "defaultFn": "guid"
    }
```

In CustomAccessToken insert a record with userId NaN

My relations:

in user model:

```
"accessTokens": {
      "type": "hasMany",
      "model": "CustomAccessToken",
      "polymorphic": {
        "idType": "string",
        "foreignKey": "userId",
        "discriminator": "principalType"
      },
      "options": {
        "disableInclude": true
      }
    }
```

in CustomAccessToken model:

```
"user": {
      "type": "belongsTo",
      "idName": "id",
      "polymorphic": {
        "idType": "string",
        "foreignKey": "userId",
        "discriminator": "principalType"
      }
    }
```

¿Any idea what's wrong?

**Comment by bajtos** [comment]
Hello, I don't see any obvious problem in your configuration. Since you have only a single user model in your application, you should not need a polymorphic relation - see the following documentation for more details: http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#access-control-with-a-single-user-model

Please create a small application showing how to reproduce the issue in isolation - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report. Ideally, write an automated test we can run via `npm test`, one that fails with the current LoopBack version.

**Comment by nagro** [comment]
Hi, I have the same problem with polymorphic relation. When idType is string, the field become NaN in my database. Any idea what's wrong?
