### ISSUE TITLE
Hide model from API Explorer but keep it available via REST

### ISSUE THREAD

**Issue by andy2046** [strongloop/loopback#3816]
# Description/Steps to reproduce
when I set public to false for model config json file, I don't see it in api explorer, nor i can access it via api

# Expected result
based on https://loopback.io/doc/en/lb2/model-config.json.html#model-properties it should not affect accessibility, it's hidden from explorer but it should still be accessible

@raymondfeng your advice is appreciated

**Comment by bajtos** [comment]
The current behavior is intended. Here is what the documentation you linked to says:

> public	Boolean	
> Whether the model API is exposed.
>
> If true, then the model is exposed over REST. Does not affect accessibility of Node API.

"accessibility of Node API" means that you can still access the model from your server-side javascript code.

If you would like to expose the model over REST but hide it from the API explorer, then you need to annotate all model's method as `documented: false`. Considering how tedious it is, I think it would make sense to enhance loopback-swagger to recognize model-level flag `documented` too. See here:

https://github.com/strongloop/loopback-swagger/blob/add406b5ee01c58c881f25f7fdc76d9b15ae2149/lib/specgen/swagger-spec-generator.js#L66-L78

We don't have bandwidth to make this change ourselves, but I am happy to help you along the way if you decide to contribute it yourself.

**Comment by andy2046** [comment]
@bajtos thanks for the reply, I can see the `documented` option for remote method in 3.x, doest it apply to normal method defined in JSON file?

we are using 2.x, can I cherry pick this `documented` option implementation to 2.x? maybe it's easier to just upgrade to 3.x?

thanks for pointing out the loopback-swagger code for this `documented` option, I can raise a pr to make the model-level flag `documented`, if you can point out the pr process

thanks

**Comment by bajtos** [comment]
> I can see the documented option for remote method in 3.x, doest it apply to normal method defined in JSON file?

Yes, it applies to all remote method, regardless of the place where they are defined.

> we are using 2.x, can I cherry pick this documented option implementation to 2.x? maybe it's easier to just upgrade to 3.x?

Since the support for this option is implemented in loopback-swagger, which is mostly independent from the LoopBack version, I think it should work with LoopBack 2.x applications too. Just make sure you are using the latest version of loopback-component-explorer and/or loopback-swagger.

>  can I cherry pick this documented option implementation to 2.x? maybe it's easier to just upgrade to 3.x?

We are not adding any new features to version lines that are in LTS mode, see https://loopback.io/doc/en/contrib/Long-term-support.html

If `documented` does not work with LoopBack 2.x, then I am afraid you will have to upgrade to LoopBack 3.x.

> I can raise a pr to make the model-level flag documented, if you can point out the pr process

Sure! Here is our guide: http://loopback.io/doc/en/contrib/code-contrib.html 

If you are new to GitHub, then you may find this article helpful too: https://www.nearform.com/blog/first-time-with-open-source/

**Comment by andy2046** [comment]
@bajtos 
I tried to add `documented` to model json file, but in loopback-swagger this property shows in `aClass.ctor.settings.documented`, not in `aClass.documented`, I believe I have to add one line to 
strong-remoting shared-class.js `this.documented = this.ctor.settings.documented !== false` in order to access `aClass.documented`, or it is ok to access via `aClass.ctor.settings.documented`, please advise so I can proceed the change, thanks

```json
{
  "name": "myUser",
  "documented": true,
  "base": "User",
  ...
}
```

```js
  classes.forEach(function(aClass) {
    if (!aClass.name) return;
    console.log(aClass.documented, aClass.ctor.settings.documented);
    // undefined true
```

https://github.com/strongloop/strong-remoting/blob/def5b72ce3b0743964f1b5a5ab87c3d6f5058ab0/lib/shared-class.js#L41

https://github.com/strongloop/strong-remoting/blob/def5b72ce3b0743964f1b5a5ab87c3d6f5058ab0/lib/shared-method.js#L116

https://github.com/strongloop/loopback-swagger/blob/add406b5ee01c58c881f25f7fdc76d9b15ae2149/lib/specgen/swagger-spec-generator.js#L66-L78

**Comment by bajtos** [comment]
> I tried to add `documented` to model json file, but in loopback-swagger this property shows in `aClass.ctor.settings.documented`, not in `aClass.documented`, I believe I have to add one line to 
strong-remoting shared-class.js `this.documented = this.ctor.settings.documented !== false` in order to access `aClass.documented`, or it is ok to access via `aClass.ctor.settings.documented`, 

Let's enhance strong-remoting to lift the `documented` flag from model settings to SharedClass as you proposed.
