### ISSUE TITLE
HTTP 401 on Users endpoints - even as admin

### ISSUE THREAD

**Issue by vinicius-ronconi** [strongloop/loopback#3828]
# Description/Steps to reproduce
I just cloned https://github.com/strongloop/loopback-sandbox.git and tried to run the project as-is, using in-memory connector.

Using the /explorer, I created a new user, logged in, set the token and then tried to get some resources of this user:
- GET /users
- HEAD /Users/{id}
- GET /users/{id}/accessTokens

All the above returned a HTTP 401.

Then I added a boot script to create a new admin user, using the following code:
file: /server/boot/01-create-admin.js

```
module.exports = function(app) {
  var User = app.models.User;
  console.log('Running 01-create-admin...');
  User.create({email: 'foo@bar.com', password: 'bar'}, function(err, userInstance) {
    console.log(userInstance);
    var Role = app.models.Role;
    Role.create({
      name: 'admin'
    }, function(err, role) {
      var RoleMapping = app.models.RoleMapping;
      console.log('Created role:', role);
      role.principals.create({
        principalType: RoleMapping.USER,
        principalId: userInstance.id
      }, function(err, principal) {
        console.log('Created principal:', principal);
      });
    });
  });
};

```

I logged in with the admin user, set the token and also got the same problems.

# Link to reproduction sandbox
https://github.com/strongloop/loopback-sandbox.git

# Expected result
Expected to be able to retrieve the data from the mentioned endpoints, but I'm always getting HTTP 401.

# Additional information
This problem is similar to: #3418 and #3533, but I was not able to find any solution there.

$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 9.7.1

$ npm ls --prod --depth 0 | grep loopback
loopback-sandbox@1.0.0 /Users/ronconi/Workspaces/OfficePools/loopback-sandbox
├── loopback@3.18.2
├── loopback-boot@3.1.0
├── loopback-component-explorer@5.3.0

**Comment by bajtos** [comment]
Hello @vinicius-ronconi, thank you for reporting the issue.

> GET /users

LoopBack's ACL system works and method (endpoint) level, not at the level of individual model instances. In order to allow `GET /users` for an ordinary user, we would have to filter the returned instances to include only the currently logged-in user - and that's something LoopBack cannot do (yet).

It may be possible to configure ACLs to allow people in "admin" role to access this endpoint, IDK. Please note that code snippet above creates "admin" role, but does not modify the ACL to allow admins to get all users.

> HEAD /Users/{id}

Assuming `{id}` is the id of the currently logged in user and `GET /Users/{id}` returns 200, then this looks like a bug to me. I am afraid I don't have bandwidth to investigate this myself. My recommendation is to find out what remote method is backing `HEAD /Users/{id}` and why a different ACL from the one for `GET /Users/{id}` is applied .

> GET /users/{id}/accessTokens

ACLs for model relations are tricky, our current implementation does not handle them well. If we agree that a user should be able to access their own access tokens via this API (which make sense to me), then we need to add more ACL entries to User model to allow remote access to methods contributed by the relation, e.g. `__get__accessTokens`.

Please note that we don't have bandwidth to work on these changes ourselves, but I am happy to help you along the way if you decide to contribute them yourself. See http://loopback.io/doc/en/contrib/code-contrib.html to get you started.
