### ISSUE TITLE
Cannot initialize connector "mongodb": slash in host identifier

### ISSUE THREAD

**Issue by abarbaro** [strongloop/loopback#3841]
Hi all,
I have installed mondogb correctly and crated a new datasource and relative model. Now when I run ```node .``` I have the following error:

```
Connection fails: Error: slash in host identifier
It will be retried for the next request.
/home/alberto/test/node_modules/loopback/lib/application.js:240
    throw err;
    ^

Error: Cannot create data source "Test": Cannot initialize connector "mongodb": slash in host identifier
```

I'm using ```4.2.0 (generator-loopback@5.7.0 loopback-workspace@4.1.1)```, with older version I don't have this problem. Any idea on how to solve it please?

Thanks

**Comment by abarbaro** [comment]
Problem solved.

Thanks anyway

**Comment by VAggrippino** [comment]
@abarbaro How did you solve the problem? I have the same problem.

**Comment by abarbaro** [comment]
Hi,
Please when you create a new model try to manually insert the plural for it
instead of leaving it blank and also add at least one property.

I'm not entirely sure what solved it but at least it worked :)

Let me know if it works.

Thanks

**Comment by VAggrippino** [comment]
@abarbaro I figured out the cause of the problem for me... my own stupidity. I forgot that my database connection information wasn't part of my git repository when I cloned it to my host. So, my MongoDB connection URL that was defined like this in the code:

    const mongoUrl = `mongodb://${username}:${password}@${dbhost}:${dbport}/${database}`

... ended up being interpolated like this:

    mongodb://:@:/
-----
I'm not familiar with the terminology you're using and it's probably because I'm very new to both Node and MongoDB. I'm not sure what a "model" is in this context and I don't know what the plural of a model would be.

My document schema is very simple. There's only two fields:

    {
      _id: <not Object Id, generated by a third-party library>
      url: <any typical web URI>
    }

I was getting the error message as soon as I tried to connect to the database and it never executed any of the database actions in my code.

If you're curious, this project was part of the freeCodeCamp curriculum and the finished code can be found at https://github.com/VAggrippino/fcc2018-urlShortener

**Comment by amoungui** [comment]
Hello, I'm developing a node.js project with mongodb, express, but I get this error when I start the server:


MongoDB connection error: Error: slash in host identifier
[nodemon] app crashed - waiting for file changes before starting ...

this is my files:
mongoose.js file:
```const mongoose = require('mongoose');
const { mongo, env } = require('./vars');

// set mongoose Promise to Bluebird
mongoose.Promise = Promise;

// Exit application on error
mongoose.connection.on('error', (err) => {
  console.error(`MongoDB connection error: ${err}`);
  process.exit(-1);
});

// print mongoose logs in dev env
if (env === 'development') {
  mongoose.set('debug', true);
}

/**
* Connect to mongo db
*
* @returns {object} Mongoose connection
* @public
*/
exports.connect = () => {
  mongoose.connect(mongo.uri, {
    keepAlive: 1,
    useMongoClient: true,
  });
  return mongoose.connection;
};
```

my var.js file:

```
const path = require('path');

// import .env variables
require('dotenv-safe').load({
  path: path.join(__dirname, '../../.env'),
  sample: path.join(__dirname, '../../.env.example'),
});

module.exports = {
  env: process.env.NODE_ENV,
  port: process.env.PORT,
  jwtSecret: process.env.JWT_SECRET,
  jwtExpirationInterval: process.env.JWT_EXPIRATION_MINUTES,
  masterAccount: process.env.MASTER_ACCOUNT_NUMBER,
  masterAccountPassword: process.env.MASTER_ACCOUNT_PASSWORD,
  mongo: {
    uri: process.env.NODE_ENV === 'test'
      ? process.env.MONGO_URI_TESTS
      : process.env.MONGO_URI,
  },
  logs: process.env.NODE_ENV === 'production' ? 'combined' : 'dev',
};
```
the index.js file:

```// make bluebird default Promise
Promise = require('bluebird'); // eslint-disable-line no-global-assign
const { port, env } = require('./config/vars');
const app = require('./config/express');
const mongoose = require('./config/mongoose');

// open mongoose connection
mongoose.connect();

// listen to requests
app.listen(port, () => console.info(`server started on port ${port} (${env})`));

/**
* Exports express
* @public
*/
module.exports = app;
```

thanks for you help
