### ISSUE TITLE
How to implement relational methods into connector

### ISSUE THREAD

**Issue by simonfr** [strongloop/loopback#3861]
Hi,

I'm trying to modify my connector to insert Neo4J relations. I dont see any other documentation on your website about how modify normal process by mine. I think there is some methods I can implement to my connector in order to modify belongsTo process ?

https://loopback.io/doc/en/lb2/Building-a-connector.html (the last sentences are not very clear.) 

Where can I find more documentation?

Thanks,
Simon

**Comment by jannyHou** [comment]
@simonfr 

> I'm trying to modify my connector to insert Neo4J relations

Thank you for the effort of building the community connector! 

We don't have relational methods in the connector. All the relation logic is handled in `loopback-datasource-juggler`, the connector only implements the CRUD methods. A connector cannot modify the `belongsTo` process, and we don't often change the relation code since it affects all the connectors.

See the mysql connector as an example:
https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js

I haven't used Neo4j database before, not quite sure what does "Neo4J relations" mean, could you elaborate more?
