### ISSUE TITLE
How to use async await on loopback 3.x models

### ISSUE THREAD

**Issue by meepeek** [strongloop/loopback#3867]
Using node 8 I am able to run async function in loopback but I stuck with 2 problems and would like to ask for your suggestions.

1. I cannot await for app.models.<name>.create, even though I promisify with util.promisify
2. I don't know how to catch async error since it was gone through module.exports

The following is my code, I have successfully print the await result. I did promisify the same way it works on fs.readdir but for loopback models, it throws error as if the promisified function was not an async one.

```
// 'use strict';

const moment = require('moment')
const sleep = require('sleep')
const {promisify} = require('util')

module.exports = async function(app) {

  const Path = require('path')

  const path = Path.resolve(Path.dirname('')) + '/rawData/eod/2017/'

  let a = require('../core/dataCollector')
  let b = a.siamchart.getEodFromFile
  let result = await b(path).catch( console.log )
// console.log(result)
  const promiseCreate = promisify(app.models.stockEod.create)
  result.map( v => {
    await promiseCreate(v).catch(console.log)
  } )

}
```

**Comment by timhuff** [comment]
You're promisifying the function without binding it to the model. You might want to try `promiseCreate.call(app.models.stockEod, v)`. Though if you're going to be using promises, I'd suggest using `bluebird`'s `promisifyAll` method. Take all this with a grain of salt, though, as I just started using loopback, myself.

**Comment by meepeek** [comment]
It works!! Thanks
bluebird.Promise.map is what I am looking for.

```
  const promiseCreate = promisify(app.models.stockEod.create.bind(app.models.stockEod))

  await bluebird.Promise.map(result, function(v) {
    return promiseCreate(v).catch(console.log)
  }, {concurrency: 2})
```

**Comment by timhuff** [comment]
Glad you got it sorted out. Though, since you're using bluebird, you might find it beneficial to use `bluebird.promisifyAll(app.models.stockEod)`. I've found that loopback's models have a name conflict with the `Async` suffix, so I've needed to do `bluebird.promisifyAll(app.models.stockEod, { suffix: 'P' })`. After you've done that, you can write `app.models.stockEod.createP(v)` and you can use the promisified form of any other model method simply by appending a `P` to the function name, rather than promisifying each function each time.
