### ISSUE TITLE
Default Property does not work for request argument of remote method in OpenAPI explorer

### ISSUE THREAD

**Issue by tgijasonyip** [strongloop/loopback#3869]
In the OpenAPI explorer page, I want to show custom default value for an argument of the request of an API. Unfortunately, the default value never display.

# Steps to reproduce

1. Set the default value in common/models/test-user.json
![image](https://user-images.githubusercontent.com/38749833/39418642-10157938-4c8e-11e8-83df-130c3ea150ce.png)

2. Run the application
3. Visit the OpenAPI Explorer page
4. Check the example value of the request argument displayed on the page

# Link to reproduction sandbox
https://github.com/tgijasonyip/loopback-sandbox

# Expected result
The example value for the "data" parameter in /TestUser/test API should be
```
{
  "username": "string",
  "password": "string"
}
```
Or the above value may be displayed in the value textarea of the parameter.

# Actual result
The example value displayed is
```
{
  "id": 0,
  "username": "string",
  "email": "string",
  "firstName": "string",
  "lastName": "string"
}
```
which is the schema of the model associated to this API

![image](https://user-images.githubusercontent.com/38749833/39418586-d30c4616-4c8d-11e8-8ac2-cbe207f25884.png)

# Additional information
The default value works for non-body and non-source argument.
The issue was reported in https://github.com/strongloop/loopback/issues/2730

**Comment by jannyHou** [comment]
@tgijasonyip Thank you for letting us know it and appreciate your sandbox! Labelled it as a bug, move to the planning column.

**Comment by Prancing-Pony** [comment]
Proposed solutions to help the explorer know if the parameter is a model

-  Make model remote methods have the signature  `arg`: `MODEL_PARAMETER` instead of `data`.  This seems easy, though if there are other hacks checking for `arg: data` then it will break them.

- Add a line in the documentation saying don't name your arg `data`.

- Add a property to the remote method config `modelArg: true`.

- Make models explicitly construct their remote method parameters with their own properties.
