### ISSUE TITLE
Can't run in DigitalOcean

### ISSUE THREAD

**Issue by andreascai** [strongloop/loopback#3925]
![img_2071](https://user-images.githubusercontent.com/19204109/42020360-ae652ce6-7add-11e8-918b-f2883bd512d3.JPG)

it shows this

**Comment by dhmlau** [comment]
@andreascai , could you please provide more details on the problem you're running into and how to reproduce it?  Better yet, if you could isolate the problem without having DigitalOcean, that would be great. thanks!

**Comment by mikeyb** [comment]
Works fine on digital ocean for me.

**Comment by yshing** [comment]
@andreascai If U run into this problem, It's probably due to npm install fail due to no enough ram.
Solution is to add some swap https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by andreascai** [comment]
@dhmlau thanks for you time. I provided detail in the first place and decided to clear after seeing a lot of open issue. Is it problem with PostgreSQL configuration

**Comment by andreascai** [comment]
@yshing I got standard Droplet with 1GB of RAM. Should I get more?

**Comment by mikeyb** [comment]
That error means postgres isnt running.  If you googled the error it would have told you.  The "Connection Refused" means the connection was refused due to nothing being there listening on port 5432.  Run something on port 5432 and the error will go away.

As stated previously, click the link someone took the time to provide you and follow the directions.

**Comment by mikeyb** [comment]
`netstat -tapn|grep LIST` should show you all the running processes with open ports bound by pid.  But it seems to me port 5432 isnt in use because no app is running on it.
