### ISSUE TITLE
Remote Method Bug (with security concerns)

### ISSUE THREAD

**Issue by sebastianfelipe** [strongloop/loopback#4002]
# Description
Hi, I found a problem using an extended model with a referencesMany relation. Consider a Model A hasMany ModelB and Model B referencesMany ModelC. Also Model B is nested to Model A, that means it inherits its endpoints to Model A (i.e -> `/api/modelas/{id}/modelbs/{nk}/modelcs/rel/{fk}`). 

# Steps to reproduce
Ok, having in mind all these considerations at this point, the problem can be reproduced following the next steps:

1. Develop a beforeRemote with a DEBUG 1 message in `prototype.__link__modelBs__modelCs` in Model A javascript file (common/models)
2. Develop a beforeRemote with a DEBUG 2 message in `prototype.__link__modelCs` in Model B javascript file (common/models)
3. Call `PUT /api/modelas/{id}/modelbs/{nk}/modelcs/rel/{fk}` to add the "fk" instance reference to a "nk" instance reference from Model A instance "id"

# Expected result
The expected result is that only DEBUG 1 should be executed, but in this case, DEBUG 2 also is executed. That means, that the beforeRemote in ModelB, that is a totally a different endpoint is also executing. That's wrong. Because that means that ModelA endpoint call another HTTP request behind and is not using an internal call to execute the method in Model B. That result is expected if you're using an "observe", but not when you're using a specific remote method that is totally different from where it is inherited.

# Additional information
The security concerns are in its implementations, if someone develop a role resolver with Grant 1 > Grant 2 and applies Grant 2 only in`"prototype.__link__modelbs__modelcs` from Model A and Grant 1 to `prototype.__link__modelcs` from Model B and its related beforeRemote are specific with strict operations in each of those processes, then the user with Grant 2, executing `prototype.__link__modelbs__modelcs` can reproduce the Grant 2 operations and also the Grant 1, using all the code developed in `prototype.__link__modelcs` from Model B . This scenario can be possible if that action doesn't validate the Grant 1 role resolver applied.

There's a lot of scenarios, but the important thing is the description above explaining a behaviour that is very different from the "hasMany" relations and what it should be expected.

Thanks,
Sebastián.

**Comment by sebastianfelipe** [comment]
@bajtos @kjdelisle this is important, it is necessary to have a look at it. Thanks.

**Comment by bajtos** [comment]
@sebastianfelipe thank you for the bug report. I am not able to fully envision how different parts of LoopBack are handling the scenario you have described. Could you please create a small application we can use to reproduce and debug the problem you have described? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report. Ideally, write an automated test we can run via `npm test`, one that fails with the current LoopBack version.

In general, strong-remoting is not aware of relations, and therefore the authorization layer cannot invoke ACLs for relations either. I suspect your problem would be the result of such design and thus very difficult to fix in the current code base.

**Comment by sebastianfelipe** [comment]
I'm gonna build that small application. Gonna do it during the next week. Thanks.

**Comment by sebastianfelipe** [comment]
Done!

I forked the loopback-sandbox, write code to make the bug show up and it happened. I used the "issue-4002" branch and you can find it here [https://github.com/sebastianfelipe/loopback-sandbox/tree/issue-4002](url)

There I created those 3 models already explained with its relations. also I created an instance for each one (modelA -> 1, modelB -> 1 belongs to modelA 1, and isolated modelC 1) and also the nested relation from modelB to modelA.

The idea of the test is make a relation between modelB 1 and modelC 1 using the endpoint from modelA, provided from the nestRemoting. There you can find in the server log the debugs. I put an error in the second phase to show you that it passes for both as it were a twice http request (like the bug explained). That error was a 401.

To run the test you have to:
1. Run the project with "npm start"
2. In another console, run "npm run issue-4002"

Try it and let me know what you think.

Sebastián.

**Comment by sebastianfelipe** [comment]
When you read the code, you will notice I had to add a patch in ModelB to the __exists__modelCs, well, that is another unsolved bug that I posted time ago in #3778, there I added a patch and it works, but it shouldn't need to have that patch, probably that bug is related with this issue. I think maybe there came from the same root.

Sebastián.

**Comment by bajtos** [comment]
Thank you @sebastianfelipe for the app reproducing the issue. I'll try to look into this problem later this week.

**Comment by bajtos** [comment]
I am having difficulties wrapping my head around all aspects of this scenario. 

However, as far as I can tell, it was an intentional decision to invoke both remote hooks (`ModelA.prototype.__link__modelBs__modelCs` and `ModelB.prototype.__link__modelCs`), see the discussion in https://github.com/strongloop/loopback/pull/435 for more details.

> The expected result is that only DEBUG 1 should be executed, but in this case, DEBUG 2 also is executed. That means, that the beforeRemote in ModelB, that is a totally a different endpoint is also executing. That's wrong. Because that means that ModelA endpoint call another HTTP request behind and is not using an internal call to execute the method in Model B. That result is expected if you're using an "observe", but not when you're using a specific remote method that is totally different from where it is inherited.

I am afraid your are making wrong assumptions here. There is still only one remote method being executed, it's just that we invoke remote hooks on both models. Here is the code registering special before/after hooks that will invoke before/after hooks on the other model:

https://github.com/strongloop/loopback/blob/aad97c20360de236af6afcb4e364f42d071664b0/lib/model.js#L1025-L1042

> The security concerns are in its implementations, if someone develop a role resolver with Grant 1 > Grant 2 and applies Grant 2 only in`"prototype.__link__modelbs__modelcs` from Model A and Grant 1 to `prototype.__link__modelcs` from Model B and its related beforeRemote are specific with strict operations in each of those processes, then the user with Grant 2, executing `prototype.__link__modelbs__modelcs` can reproduce the Grant 2 operations and also the Grant 1, using all the code developed in `prototype.__link__modelcs` from Model B . This scenario can be possible if that action doesn't validate the Grant 1 role resolver applied.

From what I remember, our authentication layer (`app.enableAuth`) is executed before any remoting hooks are triggered, therefore I think the authentication is always going to use the outermost remote method (`prototype.__link__modelbs__modelcs`).

Is this scenario still valid, now that we better understand how nested remoting works under the hood? Were you able to reproduce the problem you have described in practice, or is this only a theoretical concept? Do you use the built-in auth mechanism provided by LoopBack, or install custom remote hooks to handle auth?

> There's a lot of scenarios, but the important thing is the description above explaining a behaviour that is very different from the "hasMany" relations and what it should be expected.

IIUC, you are saying that when a relation uses nested remoting, then a different set of remote hooks is executed, compared to the setup when the relation is not nested. Is that correct? I am not sure if there is anything we can change about that runtime behavior, perhaps our documentation should be improved to explicitly mention which remote hooks are executed for relation methods?

@raymondfeng Since you were involved with #435 that introduced the code invoking remote hooks on the nested target mode, could you please take a look at this issue too?

**Comment by sebastianfelipe** [comment]
Thanks for the answer. Well, if that were the case, about the reasoning of #435, it should be the same behaviour when the relation were "hasMany" or "embedsMany", but it doesn't. It is only when it is a "referencesMany" relation.

I'm gonna try with ACLs, but by other hand, there could be problems when you use both endpoints with different functionalities inside beforeRemote. For example, send an email in "prototype.__link__modelcs" from Model B, but don't say anything when "prototype.__link__modelbs__modelcs" is called. In that case, it will send that email anyway. So is a problematic case. I think it shouldn't be called the remote hooks from nested models. Divide and conquerors. With that behaviour is not simple to develop reliable code without having in mind always what is happening in the next step.

Sebastián.

**Comment by bajtos** [comment]
@sebastianfelipe I see your point.

This issue is tricky for us to solve because we don't want to break existing applications that may be relying on the current behavior.

Would it help if LB provided a feature flag (e.g. at model level) that will control whether both remote hooks are invoked for nested relation? That will allow you to opt out of the hooks you don't want to use.

Please note that we don't have bandwidth to implement such feature flag, but I am happy to help you along the way if you decide to contribute it.

**Comment by sebastianfelipe** [comment]
I understand, but let me explain it again, this case only occurs when is used nestRemoting + "referencesMany" relation, in other relations like hasMany or embedsMany it doesn't happen. So I think it should be a whitelist instead of a blacklist opt.

**Comment by sebastianfelipe** [comment]
I'm gonna try it further to know better its behaviour (in other cases like not __link__ endpoints and with embedsMany and hasMany relations). I'm gonna update the sandbox with those cases, let you know then.

Sebastián.
