### ISSUE TITLE
Regular Expression Denial of Service with underscore.string

### ISSUE THREAD

**Issue by Ez3ki3l** [strongloop/loopback#4106]
# Description/Steps to reproduce
Expected to pass NSP, however, failed because it has a vulnerable dependency.
```
  Moderate        Regular Expression Denial of Service                         
  Package         underscore.string                                  
  Dependency of   loopback
  Path            loopback > underscore.string
  More info       https://nodesecurity.io/advisories/745
```

# Additional information
Remediation: Upgrade to version 3.3.5 or higher.

PR: https://github.com/strongloop/loopback/pull/4107

**Comment by bajtos** [comment]
Hi @Ez3ki3l, thank you for reporting the issue. In the future, please report security-related issues by sending an email to `callback@ibm.com`, as explained in https://loopback.io/doc/en/contrib/Reporting-issues.html#security-issues. That way we can fix them before they become known to wider public.

In this particular case, I feel the issue is rather minor. LoopBack specifies the dependency as `^3.0.3`, which allows the version `3.3.5`. You should be able to fix the problem by running `npm update` in your project.

Having said that, I also think it's a good practice to bump up the minimum version we require, thank you for opening the pull request #4107 the make that change.
