### ISSUE TITLE
Using user authentication to hide website content ?

### ISSUE THREAD

**Issue by Hadriaki** [strongloop/loopback#4173]
Hi All,

I'm trying to get my head around Loopback user authentication.

I got the basic authentication working with mongodb database and I'm able to lock the API content for specific users.

My question is what is the best way/correct way of using that authentication to lock the static content in client folder?

Do I store the access token in local storage and check every time im loading new website if user is still login via ajax call to the accessToken database?

or do I call /api/User to check that?

And finally if user is not logged in, the API content will be locked, but how to safely redirect to login page without exposing that piece of code in javascript?

**Comment by youknowme09** [comment]
> My question is what is the best way/correct way of using that authentication to lock the static content in client folder?

My conclusion is "no need".
I assume your "static content" are (js, css, images, including angular, react, vue , ...client side render framework) .
First, all these contents should not have authentication, because it loaded by browser( in many reasons.. cache, proxy, CDN..)

One thing has authentication is route, it means the URL. 
If you are using client side render framework like angular, react, vue, then you should assume your route are public to all user.
If you are using server side render, then you can protect content on server side,  before it loaded by browser.

> Do I store the access token in local storage and check every time im loading new website if user is still login via ajax call to the accessToken database?

Depend on which secure level  you need.
High secure level : NO
Medium secure level with xss risk: NO  
Medium secure level with no xss risk: YES
Low secure level: YES

> And finally if user is not logged in, the API content will be locked, but how to safely redirect to login page without exposing that piece of code in javascript?

Server side render: return 302 redirect
Client side render: not match your constraint, its javascript handle that.

**Comment by Hadriaki** [comment]
Thank you @youknowme09 for your detailed response!
