### ISSUE TITLE
Model.remoteMethod() should allow an optional third argument

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#420]
/to @ritch 
Currently, you define a remote method like this `app.models.ModeName.remoteMethod( 'foo', { ... options .. } )` where `foo` is the name of the function. This defines a remote method 'foo'. 

But @raymondfeng said we should also be able to do `remoteMethod( 'bar', { ... options .. }, ModelName.foo )` to define a remote method named 'bar' for the local function 'foo', essentially creating a "remote alias" for the method, ie. defining a remote name different from the local name.

**Comment by bajtos** [comment]
> Yes, that why I think the following signature makes sense:

```js
MyModel.remoteMethod(name, remotingMeta, fn);
```
> It basically creates an entry into remoting metadata for the model, keyed by the name. The underlying function is either the fn arg or the one matching the name.

@raymondfeng @ritch this issue has been inactive for more than a year, I am proposing to close it. We can re-open it when/if we start looking into ways how to refactor and improve the current implementation of remoted relation methods. Any objections?

**Comment by pulkitsinghal** [comment]
Hello @bajtos and @raymondfeng - my colleague ( @aquid ) and I were overriding a create method and testing our implementation when we saw something we had never seen before:
> three arguments passed to `create` instead of two 

The test we ran was with a `Model.relatedModel.create()` statement (correct me if I'm wrong here @aquid)

So I'm are just curious what is this second argument sandwiched in between? I dont' understand the conversation upstairs but this thread is the most relevant one we could find.

**Comment by pulkitsinghal** [comment]
I'm guessing that instead of using: `MyModel.create = function(data, callback){` ... we can instead write a bti more robust code if we don't care about the mysterious argument popping in and out of the picture:

```
    MyModel.create = function(){
      var data, callback;
      if (arguments && arguments.length> 1) {
        data = arguments[0];
        var possibleCallbackArg = arguments[arguments.length-1]
        if (typeof possibleCallbackArg === 'function') {
          callback = possibleCallbackArg;
        }
      }
      // whatever code was here before the above change ...
```

But still it would be good to know why related method invokes of create have a different argument-set than non-related ones? And what it means.

**Comment by bajtos** [comment]
@pulkitsinghal I am afraid your question is completely unrelated to the discussion here. If you find my answer bellow as not sufficient, then please open a new GH issue and/or ask in our mailing list, so that we do not derail the discussion here.

> So I'm are just curious what is this second argument sandwiched in between? I dont' understand the conversation upstairs but this thread is the most relevant one we could find.

The new middle argument is `options`. There aren't many options implemented OOTB yet, but because the `options` value is passed in `ctx.options` to [Operation Hooks](https://docs.strongloop.com/display/public/LB/Operation+hooks), users can implement arbitrary options themselves.

> we can instead write a bti more robust code if we don't care about the mysterious argument popping in and out of the picture:

In order to preserve backwards compatibility, all DAO methods that support `options` argument are still supporting two-arg invocation without `options` argument too.
