### ISSUE TITLE
loopback-boot dependency os-locale does not support Node v6.9.1

### ISSUE THREAD

**Issue by PragatiGarg** [strongloop/loopback#4218]
Hey
Recently, os-locale updated to v4.0.0 and it uses async in the latest version. Loopback-boot has a dependency on os-locale and has declared it in package.json. Now, we are facing problems in using loopback-boot with Node version 6. 

Please help.

**Comment by dhmlau** [comment]
@PragatiGarg, as you might already aware, Node.js v6 has reached end of life, see Node.js LTS schedule: https://github.com/nodejs/Release#end-of-life-releases.  You're strongly encouraged to update to a more recent version of Node.js.

In the meanwhile, @bajtos, do you know what might cause this issue? Thanks.

**Comment by raymondfeng** [comment]
@PragatiGarg Please run `npm ls os-locale` to see where it's pulled in.

**Comment by bajtos** [comment]
My recommendation is to use `npm shrinkwrap` to force npm to install an older version of os-locale (i.e. older than 4.0).

Other than that, as @dhmlau, Node.js 6.x is no longer supported by the Node.js project and since LoopBack is following Node.js direction, it's not supported by LoopBack either. I am afraid you are on your own now.

**Comment by PragatiGarg** [comment]
Okay. Thank you for your help :)
