### ISSUE TITLE
User.prototype.createAccessToken if first arg is object containing ttl and scopes you must provide a second true value arg 

### ISSUE THREAD

**Issue by Ahmedkholaif** [strongloop/loopback#4270]
## Steps to reproduce

when using async await with no callback arg
const tokenData = {
ttl,
scopes,
}
userInstance.createAccessToken(tokenData)

## Current Behavior
neither TTL or  scopes are set

## Expected Behavior
TTL and scopes are set for the token

## Link to reproduction sandbox
 const tokenData = {
      ttl: 24 * 60 * 60,
      scopes: ['reset-password'],
    };
    const token = await userInstance.createAccessToken( tokenData); //not working

    const  token2 = await userInstance.createAccessToken( tokenData,true); //this works
const token3 = await userInstance.accessTokens.create(tokenData); // this is the base of the above method and also working

## Acceptance Criteria
 - [ ] - fix method createAccessToken() to take custom ttl values and scope without second boolean argument

**Comment by deepakrkris** [comment]
I am able to recreate this error as described, this seems to be a bug.

**Comment by deepakrkris** [comment]
also for me with loopback version 3.25, the second argument had to be an object, otherwise the method complained.
```
userInstance.createAccessToken( tokenData,true)
```

**Comment by Ahmedkholaif** [comment]
At last, the token was created by the right scope, but the resetPassword method scope wasn't changed and is assigned to ["default"] and not applicable

**Comment by emonddr** [comment]
@deepakrkris , can you please add the `Acceptance Criteria`? thx

**Comment by bajtos** [comment]
Here is the code processing `createAccessToken` arguments:

https://github.com/strongloop/loopback/blob/f2f0b3aa91937fdd3c9cd73f1289ec58ba9efbbe/common/models/user.js#L106-L124

IIUC, when there is only a single object argument, it's interpreted as context `options`. See the documentation:

https://github.com/strongloop/loopback/blob/f2f0b3aa91937fdd3c9cd73f1289ec58ba9efbbe/common/models/user.js#L86-L92

I don't think it's possible to support both `createAccessToken(tokenData)` and `createAccessToken(options)`, because there is no way how to tell whether the only object argument is meant to be token data or context `options`.

I am proposing to improve the documentation to make it clear that a single object argument is always interpreted as context `options` and explain how to call the method when you want to supply custom token data.

**Comment by deepakrkris** [comment]
@bajtos , agree that both createAccessToken(data, options, cb) and createAccessToken(options, cb) cannot be supported. why not get rid of createAccessToken(options, cb) ?

**Comment by dhmlau** [comment]
Back to `Triaging` as @deepakrkris needs to look into it some more.

**Comment by bajtos** [comment]
> why not get rid of createAccessToken(options, cb) ?

Users should always provide `options` argument, it's the way how context is propagated (current db transaction, info about the current user, etc.).

In many cases, users don't need to tweak access token data, they are ok to use the defaults. That's why we allow `createAccessToken` with no `data` argument.

I guess it would make sense to prioritize clarity of API over convenience and force uses to always specify both `data` and `options` arguments. Unfortunately, removing `createAccessToken(options, cb)` variant is a breaking change that's not allowed by our LTS guarantees.

Our best option is to deprecate that variant, see how we are using `depd` module elsewhere in our codebase. I am not sure if that's a good idea though, because we may start printing warnings in existing applications that are working perfectly well. As an app developer, I don't want a framework in LTS version to start printing deprecation warnings for my app that works fine.
