### ISSUE TITLE
“loopback-connector-atg” does not exist or is private

### ISSUE THREAD

**Issue by garrettmac** [strongloop/loopback#4294]
The README.md has an enterprise section to a dead hyperlink

  https://github.com/strongloop/loopback-connector-atg

I would love to see this! Is it private or on the roadmap? Curious why no hyperlink or repo for this?

Thanks! Your project is new to me but looked exciting!

**Comment by dhmlau** [comment]
@garrettmac, the above link redirected to a private repo. It says "DEPRECATED AS OF 2016-09-19", and there hasn't been code change even earlier than that date. 

@raymondfeng , saw from the history that you're one of the key contributors in that repo. Since this repo has been deprecated, do you know of any alternatives? Thanks.
