### ISSUE TITLE
Compiler does not compile Loopback 4

### ISSUE THREAD

**Issue by khlilturki97** [strongloop/loopback#4324]
Hi

I was debugging a project when i found out that the compiler at some point does not work. It did not print any error to console.
I deleted the dist folder and ran compile command, no dist folder was created. Still no error to console

I tried to delete tsconfig.json and tsconfig.tsbuildinfo and then it worked.

I had this bug multiple time (i don't know when it happened neither why)

I am suspecting that the tsconfig.tsbuildinfo is getting reeeeeally big while running the watch command, but i am not sure

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/38277244/82198025-9f946980-98f3-11ea-9cca-897fd12bc43a.gif)

##  Steps to reproduce

Delete dist folder and try to compile

## Current Behavior

No dist folder is created

## Expected Behavior

A new dist folder is created

**Comment by deepakrkris** [comment]
@khlilturki97 , I think you are deleting the dist folder in your application (just to confirm, since video is not clear). that has nothing to do with lb4 packages. loopback is ts-compiled before release. So ts -compiler should have troubles either with your tsconfig , or project or lib references. also lb4 related issues must be open in https://github.com/strongloop/loopback-next
