### ISSUE TITLE
A question about LoopBack 3 EOL

### ISSUE THREAD

**Issue by dzhiwei** [strongloop/loopback#4336]
Hi Team,

Thank you so much for deliver a good product. It help many developers a lot.

May I know is EOL of LoopBack 3 finalized at 2020 DEC?
Is that possible LoopBack 3 will be supported time postponed to 2021?

**Comment by dhmlau** [comment]
@dzhiwei, thanks for your question. 

The EOL Dec 2020 date is applicable to community support (see our [LTS schedule](https://loopback.io/doc/en/contrib/Long-term-support.html)). IBM API Connect customers has extended support for LoopBack 3, see APIC release notes on LoopBack EOS timeline.

We also understand there are still LoopBack 3 users trying to migrate to LoopBack 4, so for the next few months after the EOL date, we'll try to support the community in the following ways:

- **Helping the community to migrate**: we will continue to help with questions on [GitHub](https://github.com/strongloop/loopback) and [Slack](https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw), but it will be best-effort basis.
- **Security vulnerabilities**: Critical security fixes will be applied as needed by API Connect.  
- **New features**: No features will be accepted.
- **Bugs**: Reported bugs won’t be fixed by maintainers. For critical bugs, maintainers will review and assess the risks of community-submitted PRs. If you’re planning to submit a fix, it’s the best to open a GitHub issue to discuss with the maintainers before proceeding.

**Comment by dhmlau** [comment]
We also published a blog post https://strongloop.com/strongblog/2020-lb3-eol/ regarding this topic that's pretty much the same as my response above. 
Closing this issue as answered. Thanks.
