### ISSUE TITLE
nodemailer security vulnerability

### ISSUE THREAD

**Issue by srihakum** [strongloop/loopback#4339]
The version of node module `nodemailer` is quite old and affected by the below mentioned security vulnerability.  Fix is required on Loopback 3 as well

[CVE-2020-7769](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7769):
This affects the package nodemailer before 6.4.16. Use of crafted recipient email addresses may result in arbitrary command flag injection in sendmail transport for sending mails.

Scanning the latest shows that we're pulling in nodemailer@4.7.0, which is old than recommended! Looking at the code in that old version (https://github.com/nodemailer/nodemailer/blob/533b94593f133cf353bca4b2648c1fb8326b7d0e/lib/sendmail-transport/index.js) the problem is still there.

**Comment by dhmlau** [comment]
@srihakum, thanks for reporting this. Would you like to submit a PR? Thanks.

**Comment by bajtos** [comment]
Please note: if your application is not using LoopBack's built-in `Email` model & the email connector, then I believe you are not affected by this vulnerability - the vulnerable code is invoked only when you are sending an email.

As the first step, we need you to compile a list of breaking changes made by `nodemailer` since the version 4 used by LoopBack now, so that we can asses the impact on LoopBack users if we upgrade to the latest version 6, and post the list as a comment in this issue. I would start looking here: https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md

**Comment by jannyHou** [comment]
The related breaking changes would be:

- Start using dns.resolve() instead of dns.lookup() for resolving SMTP hostnames. Might be breaking change on some environments so upgrade with care. [link](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md#500-2018-12-28)

- SMTPConnection: use removeListener instead of removeAllListeners (xr0master) [ddc4af15] Using removeListener should fix memory leak with Node.js streams. [link](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md#600-2019-03-25) 

Looking at our usage of `nodemailer` in file [mailer.js](https://github.com/strongloop/loopback/blob/f2f0b3aa91937fdd3c9cd73f1289ec58ba9efbbe/lib/connectors/mail.js#L12), we pass config to `mailer.createTransport()` function to establish the connection. If the config contains proxy setup, it may be affected:

https://github.com/nodemailer/nodemailer/blob/ba31c64c910d884579875c52d57ac45acc47aa54/lib/mailer/index.js#L114-L116
and
https://github.com/nodemailer/nodemailer/blob/ba31c64c910d884579875c52d57ac45acc47aa54/lib/mailer/index.js#L373

**Comment by jannyHou** [comment]
released as 3.28.0 🎉
