### ISSUE TITLE
Protect against query selector injection attacks

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#570]
See: http://thecodebarbarian.wordpress.com/2014/09/04/defending-against-query-selector-injection-attacks/ and http://blog.websecurify.com/2014/08/hacking-nodejs-and-mongodb.html

Can we guarantee to be not affected by this?

**Comment by bajtos** [comment]
AFAICT, the mongodb connector explicitly supports keys starting with `$` character, it's an intentional feature.

/cc @raymondfeng

**Comment by raymondfeng** [comment]
We introduce the `$` support for `update` under a connector setting property `allowExtendedOperators`. But there is no control at REST level. We should inspect the code and fix issues.

**Comment by deepakrkris** [comment]
catching up with this old thread, looks like custom disabling of https://loopback.io/doc/en/lb2/MongoDB-connector.html#additional-settings is the only way for the REST layer to handle this , please look at https://github.com/strongloop/loopback-connector-mongodb/blob/6c946d1278dbc4b0ea106127bbe793997157d46d/test/mongodb.test.js#L1318. otherwise model layer will have to override find() to check for sql injection.
