### ISSUE TITLE
remote call to custom methods are blocked by CORS, CRUD methods are allowed

### ISSUE THREAD

**Issue by adagio** [strongloop/loopback#575]
client platform: Angular SDK based

CRUD and all other methods ( find, findByID, etc. ) created by default can be called without problems from Angular SDK based client app. And that's great. Sending parametes, setting filters, etc. everything goes pretty well.

But.. calling remote custom method is impossible for me.

There is no problem with declaration of method, it appears correctly in API Explorer. And when called from API Explorer, all logic and persistence actions are executed properly. No authentication needed.

When called from client, CORS blocks the request

I have tried with [Authentication and authorization > Security considerations > CORS](http://docs.strongloop.com/display/LB/Security+considerations#Securityconsiderations-CORS), and failed.

¿How could I overpass this problem?

¿Do I have to configurate something on ACL section of model JSON?

I would be very gratefull if you could give me some guidance

**Comment by pasindud** [comment]
I had the some problem but just added ```var cors = require('cors');
app.use(cors());``` to the server.js was quick simple

**Comment by bajtos** [comment]
See strongloop/strong-remoting#165 and strongloop/loopback-workspace#192, you can configure the cors middleware declaratively too.

**Comment by denzelwamburu** [comment]
Was getting an error with `304` . This was due to local cache. Clearing it solves the issue.

**Comment by gabrielcabralbfr** [comment]
Can anyone help me on this? I`m still getting CORS errors. I'm currently working on a dev environment hosted on AWS. Running locally the error do not occur.

Here's the situation: I listen to the "After save" hook of a model, which the datasource is PostgreSQL. When this hook gets triggered, I call a Model that the datasource is MongoDB to perform an UpsertWithWhere operation in this MongoDB model.

The problem is that I get the following error: 

![Screen Shot 2019-10-09 at 15 04 12](https://user-images.githubusercontent.com/25314438/66507908-7d598400-eaa6-11e9-9b62-eecf1b0fa9bb.png)

So, you might think: "Missing cors configuration". But It's not. I have already configured it, in 3 different locations:

1 - server.js 
`const cors = require('cors')`
`app.use(cors())` 

2 - middleware.json
`"cors": {     "params": {
        "origin": true,
        "credentials": true
      }}`

3 - config.json
`"remoting: {cors: true}`

The MongoDB is at the Atlas server, with network access allowed to all IPs (0.0.0.0/0)

What am I missing?

Thanks!
