### ISSUE TITLE
[loopback-boot] Configure location of config.json file

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback#584]
For cleaner version control, I wish to move all of the installation specific files outside the app directory. The two files that change for each installation are config.json and datasources.json
 
Loopback boot allows the location of various config files to be passed to boot() e.g. modelsRootDir, dsRootDir. However, there is no provision for specifying the location of the config.json file.

**Comment by bitmage** [comment]
@rhalff this didn't quite work for me, I had to add the following fields to the config in order to restore boot script loading and other default behavior:

1. appRootDir
2. config
3. modelSources
4. bootDirs
5. models

Here is the [resulting config.js](https://gist.github.com/bitmage/0c7a3b4f08ddfcf0d2cc) for me.

@bajtos agreed on the flexibility, this is great.  Can you use my gist to create some documentation around this?  Hopefully that will save others the trouble of hunting through the code.  Thanks!

**Comment by rhalff** [comment]
@bitmage I think the tooling build around loopback relies on the config dir structure: e.g. http://strongloop.com/node-js/arc/

Drifting away from that convention does make things incompatible.

Also note I never finished the project mentioned above, it was a fork from:
https://github.com/beeman/loopback-angular-admin which still is actively being developed.

Anyway, I think one config file probably does fit some use cases.

**Comment by bajtos** [comment]
The feature requested in the issue description has been implemented by #43 and released in `loopback-boot@2.1.0`, I am closing the issue.

> @bitmage Can you use my gist to create some documentation around this? Hopefully that will save others the trouble of hunting through the code.

Sorry, I don't have bandwidth for that myself. Would you mind contributing the docs yourself? See the [instructions](http://docs.strongloop.com/display/LB/Contributing+to+LoopBack+documentation).

**Comment by bitmage** [comment]
Oh, cool.  I wasn't aware of any avenue for community contributions.  I'll check that out.  Thanks!

**Comment by bitmage** [comment]
@rhalff vim is my IDE.
