### ISSUE TITLE
improve geolocation docs

### ISSUE THREAD

**Issue by 0m15** [strongloop/loopback#664]
<del>It would be useful to have more kinds of geolocation filters available:</del>

- <del>minDistance</del>
- <del>maxDistance</del>

**EDIT**: it seems those methods are already available both on REST and Node.js, but they are undocumented.

**Comment by cfjedimaster** [comment]
I'd like to see this re-opened. I've spent the last hour or so trying to find out how to maxDistance works, and nothing seems to be working right. I can certainly sort by distance from a location, but I can't filter by a max distance.

**Comment by crandmck** [comment]
Happy to reopen, but I don't have the information on the methods.  Where are they implemented?

**Comment by cfjedimaster** [comment]
Heh, I wish I knew. I'm still trying to get maxDistance to even work.

**Comment by Sequoia** [comment]
@hacksparrow it doesn't look like that docs page was ever actually published (or if it was it became un-published). Are there any objections to publishing it now? /cc @cfjedimaster

**Comment by crandmck** [comment]
@Sequoia http://apidocs.strongloop.com/loopback-datasource-juggler/#geopoint is published, but doesn't have anything on `minDistance` or `maxDistance`.

(Note https://docs.strongloop.com/display/public/LB/GeoPoint+class is hidden, but it contains the same content as the API doc.)

**Comment by Sequoia** [comment]
AH OK. I'll fix links to point to there instead of wiki.

**Comment by crandmck** [comment]
So the question still remains:  Does Geopoint actually have `minDistance` and `maxDistance` methods, and if so, can we please add them to the API docs?

**Comment by Sequoia** [comment]
Here's what my investigation turned up:

## Conclusions
* There are no methods called `maxDistance` and `minDistance`, only filters on geop
* There’s no such thing as `minDistance`
* `where.field.near` is non-intuitive and a bit surprising: `where` queries typically affect the number of results, whereas `where.field.near` affects the **order** of results (more like an `order by` sql clause).
* adding `maxDistance` to `where.field.near` object causes results to be filtered by `GeoPoint.prototype.distanceBetween` using `maxDistance` in **miles**
* adding `maxDistance` **and `unit` to `where.field.near` object causes results to be filtered by `GeoPoint.prototype.distanceBetween` using `maxDistance` **in the unit specified**
* `where.field.near` accepts `string`, `object`, `GeoPoint`, or `array`

## Additional Notes
* `nearFilter` is a utility method in `geoJson` to be used **by data connectors**. It is invoked by data connectors and used if a query has a  [`where.field.near` filter](https://github.com/strongloop/loopback-datasource-juggler/blob/56aeeebfb080ae1605ac8a651b663adf5ab60906/lib/connectors/memory.js#L420-L425)
* There is a [todo in juggler](https://github.com/strongloop/loopback-datasource-juggler/blob/56aeeebfb080ae1605ac8a651b663adf5ab60906/lib/dao.js#L1589-L1596) related to coercing geopoints queries with `near` filter.
* `GeoPoint.prototype.distanceBetween` [documents the `unit` property](https://github.com/strongloop/loopback-datasource-juggler/blob/2.x/lib/geo.js#L175-L190) used in `near` queries
* [`EARTH_RADIUS`](https://github.com/strongloop/loopback-datasource-juggler/blob/2.x/lib/geo.js#L258-L265) is the source-of-truth for what types of units are supported
* mistyped unit (e.g. `”mile”` instead of `”miles”`) causes the filter to be **silently overlooked**

I'll work on adding the relevant bits of these findings to the docs tomorrow.

**Comment by cfjedimaster** [comment]
*Damn* good research!

**Comment by Sequoia** [comment]
@cfjedimaster Thanks! When updating docs I like to make sure I understand all facets. My thinking is that me finding all the relevant info & recording it correctly once can save 100 loopback devs from having to each do it one by one! :)

**Comment by Sequoia** [comment]
Updated page on filtering in confluence. See:
* [near (ordering)](https://docs.strongloop.com/display/APIC/Where+filter#Wherefilter-near(ordering))
* [near (ordering *and limiting by distance*)](https://docs.strongloop.com/display/APIC/Where+filter#Wherefilter-near(orderingandlimitingbydistance))

If this is sufficient please close when ready.

**Comment by crandmck** [comment]
I made some minor formatting/wording edits, but otherwise LGTM, thanks!
