### ISSUE TITLE
User logout problem "Authorization Required" 

### ISSUE THREAD

**Issue by Lipfroy** [strongloop/loopback#720]
My app used to work well, but then (after some update perhaps) it started to throw this error.
Please point me where I lost the net, cos I'm really stuck trying to fix logout. Thanks.
Tried  to update loopback and rescaffold  again, but keep getting this.

curl -X POST -H "Content-Type:application/json" -d '{"email": "q@q.com", "password": "1234", "ttl": 1209600000}' http://0.0.0.0:3000/api/users/login
{"id":"nHyGssW5sbYKx2ImFl8LfnB23dDX5Skn4D3sQ5MM9BKtMTtLoNVXCDzjGscHjPN6","ttl":31556926,"created":"2014-11-01T05:39:14.889Z","userId":"54545c5eeea445ea0bfc3214"
}
login is ok

curl -X VERB http://localhost:3000/api/users/logout?access_token=nHyGssW5sbYKx2ImFl8LfnB23dDX5Skn4D3sQ5MM9BKtMTtLoNVXCDzjGscHjPN6
curl: (52) Empty reply from server

curl -X VERB -H "Authorization: $ACCESS_TOKEN" http://localhost:3000/api/users/logout
curl: (52) Empty reply from server
_________________________________________________________________

[Usrepository userByLoginWithEmail:@"q@q.com"
                                      password:@"1234"
                                       success:^(LBUser *user)
             {NSLog(@"user found");
                 [Usrepository logoutWithSuccess:^(void){
                     NSLog(@"user logged out");
                 } failure:UserErrorBlock];
             } failure:UserErrorBlock];

When I try logout from iOS app I get user, but when it comes to logout it fails.

Error Domain=AFNetworkingErrorDomain Code=-1011 "Expected status code in (200-299), got 401" UserInfo=0x79ebde00 {NSLocalizedRecoverySuggestion={"error":{"name":"Error","status":401,"message":"Authorization Required","statusCode":401,"stack":"Error: Authorization Required\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/lib/application.js:328:21\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/lib/model.js:295:5\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/common/models/acl.js:427:21\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/node_modules/async/lib/async.js:254:17\n    at done (/Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/node_modules/async/lib/async.js:135:19)\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/node_modules/async/lib/async.js:32:16\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/node_modules/async/lib/async.js:251:21\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/node_modules/async/lib/async.js:575:34\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/common/models/acl.js:410:17\n    at /Volumes/Macintosh HDD/DEVELOPER/SERVER/backend/node_modules/loopback/common/models/role.js:147:9"}}, AFNetworkingOperationFailingURLRequestErrorKey=<NSMutableURLRequest: 0x7b230480> { URL: http://10.0.230.2:3000/api/users/logout }, NSErrorFailingURLKey=http://10.0.230.2:3000/api/users/logout, NSLocalizedDescription=Expected status code in (200-299), got 401, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x79e47f40> { URL: http://10.0.230.2:3000/api/users/logout } { status code: 401, headers {
    "Access-Control-Allow-Credentials" = true;
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sat, 01 Nov 2014 06:52:03 GMT";
    Etag = "W/\"V/EM3sYd11K0rUIckT9xRQ==\"";
    "Transfer-Encoding" = Identity;
    Vary = "Origin, Accept-Encoding";
    "X-Powered-By" = Express;
} }}

**Comment by shaunbruno** [comment]
Also reporting only scenario that works is logout with POST, and only works if access_token is set in the GET URL. POST access_token is ignored, and causes Model.findById error. Same with header 'Authorization:' field - also ignored and causes error. Plain GET with access_token in URL causes authorization required error.

strongloop v2.10.3 (node v0.10.32)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├─┬ strong-supervisor@1.4.1 (c945bd1)
│ └── strong-agent@1.3.2
├── node-inspector@0.7.4
├── strong-deploy@1.1.4 (5e25e21)
├── strong-pm@1.7.2 (315d448)
├── strong-registry@1.1.4 (aab3dbb)
├── nodefly-register@0.3.3
└── generator-loopback@1.7.1 (f9f97e5)

**Comment by atajwala** [comment]
I am seeing similar issue as 'shaunbruno' points out above. In my case, both the GET/POST with access_token is causing a 'Model.findById error'. Please advice.

**Comment by dbarbeau** [comment]
Hello, I'm having a similar issue with logout over REST api. A `MyUser` is derived from `User`. Then `api/MyUser/logout` doesn't work (not even in the API Explorer).

 - GET + Authorization header : Not found": "Unknown 'MyUser' id 'logout'"
 - GET + "access_token=xxx..." in query string : Not found": "Unknown 'MyUser' id 'logout'"
 - POST + Authorization header : "Bad request": "access_token is a required arg"
 - POST + "access_token=xxx..." in query string : "Bad request": "access_token is a required arg"

I'm very confused as I am pretty sure it used to work at one point with the 3rd method and don't recall changing anything in my configuration. I've probably been staring too long at this problem :) I'll try to force a rollback of my packages, some build script might have gone wacko and upgraded packages... dunno.

**Comment by dbarbeau** [comment]
Ugh... embarassing... forget about me, I had disabled authentication (commented out `server.enableAuth()`). Which adds to the confusion because login works perfectly in either way but logout needs enableAuth() to operate.

**Comment by philarmour** [comment]
Hi add me to the list.  Similar finding as @shaunbruno.  I'm using Postman for the requests and running loopback 2.19.0 on the backend.  I have an extended user model, with 2 remoteMethods defined and the following json definition:

{
  "name": "user",
  "plural": "users",
  "base": "User",
  "properties": {},
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "accessToken",
      "foreignKey": "userId"
    },
    "identities": {
      "type": "hasMany",
      "model": "userIdentity",
      "foreignKey": "userId"
    },
    "credentials": {
      "type": "hasMany",
      "model": "userCredential",
      "foreignKey": "userId"
    },
    "account": {
      "type": "belongsTo",
      "model": "Account",
      "foreignKey": "accountId"
    }
  },
  "acls": [
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "loginAsDemo"
    }
  ],
  "methods": []
}

My initial use case was calling logout with a valid access token sent via the X-Access-Token header.  

It does appear that the "Access Context" is set incorrectly with a property of "findByID" rather than "logout".  Strangely the modelId is "logout":

Mon, 20 Jul 2015 14:25:36 GMT express:router dispatching GET /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router query  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router expressInit  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router favicon  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router compression  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router <anonymous>  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router session  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express-session fetching gm5BMs4jN4ilfSZIpj3SPmYQ9oZclbwz
Mon, 20 Jul 2015 14:25:36 GMT express-session session found
Mon, 20 Jul 2015 14:25:36 GMT express:router initialize  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router authenticate  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router <anonymous>  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router setCurrentUser  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router trim prefix (/api/v1) from url /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router restApiHandler /api/v1 : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router dispatching GET /users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router <anonymous>  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router urlencodedParser  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT body-parser:urlencoded skip empty body
Mon, 20 Jul 2015 14:25:36 GMT express:router jsonParser  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT body-parser:json skip empty body
Mon, 20 Jul 2015 14:25:36 GMT express:router trim prefix (/users) from url /users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router router /users : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router dispatching GET /logout
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:role isInRole(): $everyone
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context ---AccessContext---
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context principals:
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context principal: {"type":"USER","id":5}
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context modelName user
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context modelId logout
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context property findById
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context method findById
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context accessType READ
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context accessToken:
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context   id "aywYPymhx601B2Bq2SPY0VD0kKeZF7aMra6Af4LdBhdgfGK0EGKTkNBC7VVAGU4q"
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context   ttl 1209600
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context getUserId() 5
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context isAuthenticated() true
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:role Custom resolver found for role $everyone
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:role isInRole(): $owner
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context ---AccessContext---
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context principals:
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context principal: {"type":"USER","id":5}
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context modelName user
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context modelId logout
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context property findById
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context method findById
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context accessType READ
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context accessToken:
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context   id "aywYPymhx601B2Bq2SPY0VD0kKeZF7aMra6Af4LdBhdgfGK0EGKTkNBC7VVAGU4q"
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context   ttl 1209600
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context getUserId() 5
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context isAuthenticated() true
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:role Custom resolver found for role $owner
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:role isOwner(): user logout userId: 5
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl The following ACLs were searched: 
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl ---ACL---
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl model user
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl property *
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl principalType ROLE
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl principalId $everyone
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl accessType *
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl permission DENY
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl with score: 7495
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:acl ---Resolved---
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context ---AccessRequest---
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context  model user
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context  property findById
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context  accessType READ
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context  permission DENY
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context  isWildcard() false
Mon, 20 Jul 2015 14:25:36 GMT loopback:security:access-context  isAllowed() false
Mon, 20 Jul 2015 14:25:36 GMT express:router restRemoteMethodNotFound  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router restUrlNotFound  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT express:router restErrorHandler  : /api/v1/users/logout
Mon, 20 Jul 2015 14:25:36 GMT strong-remoting:rest-adapter Error in GET /users/logout: Error: Authorization Required
    at /projects/enerchi-api/node_modules/loopback/lib/application.js:375:21
    at /projects/enerchi-api/node_modules/loopback/lib/model.js:313:7
    at /projects/enerchi-api/node_modules/loopback/common/models/acl.js:465:23
    at /projects/enerchi-api/node_modules/loopback/node_modules/async/lib/async.js:251:17
    at done (/projects/enerchi-api/node_modules/loopback/node_modules/async/lib/async.js:132:19)
    at /projects/enerchi-api/node_modules/loopback/node_modules/async/lib/async.js:32:16
    at /projects/enerchi-api/node_modules/loopback/node_modules/async/lib/async.js:248:21
    at /projects/enerchi-api/node_modules/loopback/node_modules/async/lib/async.js:572:34
    at /projects/enerchi-api/node_modules/loopback/common/models/acl.js:447:17
    at /projects/enerchi-api/node_modules/loopback/common/models/role.js:182:9
    at /projects/enerchi-api/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/projects/enerchi-api/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
Mon, 20 Jul 2015 14:25:36 GMT express-session saving gm5BMs4jN4ilfSZIpj3SPmYQ9oZclbwz
Mon, 20 Jul 2015 14:25:36 GMT express-session split response
Mon, 20 Jul 2015 14:25:36 GMT compression gzip compression

For reference, the successful logout (using POST and the Authorization param), has the Access context set like this:

Mon, 20 Jul 2015 14:23:17 GMT loopback:security:role isInRole(): $everyone
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context ---AccessContext---
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context principals:
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context principal: {"type":"USER","id":5}
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context modelName user
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context modelId undefined
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context property logout
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context method logout
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context accessType EXECUTE
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context accessToken:
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context   id "z3BSs0WfwQjq4274BV4dcBYCIPmqrmmBTTucvtT9pfHoSHdufst0Hd7GeNwIGUbV"
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context   ttl 1209600
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context getUserId() 5
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context isAuthenticated() true
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:role Custom resolver found for role $everyone
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:role isInRole(): $everyone
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context ---AccessContext---
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context principals:
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context principal: {"type":"USER","id":5}
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context modelName user
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context modelId undefined
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context property logout
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context method logout
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context accessType EXECUTE
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context accessToken:
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context   id "z3BSs0WfwQjq4274BV4dcBYCIPmqrmmBTTucvtT9pfHoSHdufst0Hd7GeNwIGUbV"
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context   ttl 1209600
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context getUserId() 5
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:access-context isAuthenticated() true
Mon, 20 Jul 2015 14:23:17 GMT loopback:security:role Custom resolver found for role $everyone

**Comment by loay** [comment]
Hi @Lipfroy 
Is this issue still occurring? Thanks.

**Comment by egel** [comment]
Hey @loay. In my case, yes. I'm currently trying to handle the same problem as @Lipfroy has.

**Comment by Lipfroy** [comment]
actually i gave up having that issue. no matter how many times I tried, that was a stuck for my project. Switched to different nodejs api server

**Comment by fabien** [comment]
What I discovered today is that the http method of the `logout` remote method is set to `all`. With this setting I wasn't able to logout, no matter what I tried. When I changed to just `get` it did work ...

**Comment by loay** [comment]
Thanks @fabien for the fix. 
@egel Can you try this fix and let us know if it resolves your issue? Thanks

**Comment by loay** [comment]
Hi @egel did fabien's fix work for you? thanks

**Comment by loay** [comment]
Hello, I am closing this issue for now.  If you are still running into problems, feel free to leave a comment and I will reopen the issue.

**Comment by devotis** [comment]
I'm currently running into the same issue and I am experiencing the same as reported above. I'm using an unmodified User model and the User.logout() method provided by lb-services.js. 

```
{
    "name": "Error",
    "status": 400,
    "message": "access_token is a required arg",
    "statusCode": 400,
    "stack": "Error: access_token is a required arg
       at new badArgumentError (...\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\shared-method.js:277:13)
       at coerceAccepts (...\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\shared-method.js:357:13)
       at SharedMethod.invoke (...\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\shared-method.js:226:16)
       at HttpContext.invoke (...\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\http-context.js:390:12)
       at phaseInvoke (...\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:654:9)
       at runHandler (...\\node_modules\\loopback\\node_modules\\loopback-phase\\lib\\phase.js:135:5)
       at iterate (...\\node_modules\\async\\lib\\async.js:146:13)
       at Object.async.eachSeries (...\\node_modules\\async\\lib\\async.js:162:9)
       at runHandlers (...\\node_modules\\loopback\\node_modules\\loopback-phase\\lib\\phase.js:144:13)
       at iterate (...\\node_modules\\async\\lib\\async.js:146:13)"
}
```

**Comment by devotis** [comment]
Nevermind, I had also commented out `server.enableAuth()`. Enabling it again (and restarting the server) fixed it.

**Comment by jjhesk** [comment]
i got the same issue from using the header in authorization in the `users/count`. As a result, i got `AUTHORIZATION_REQUIRED` error.

**Comment by jonathanwoahn** [comment]
I have this same issue. I'm not sure what caused it, but I was able to get around it be clearing localstorage. Hopefully it doesn't crop up again any time soon.

**Comment by iRajul** [comment]
@devotis  how are you providing access_token while using lb-services.js ?

**Comment by devotis** [comment]
I don't provide `access_token ` directly. I inject the User model in my controller or service and use the `User.login`, `User.logout`, `User.create`, `User.getCurrent`, `User. resetPassword ` methods. But that was quite some time ago, so I don't remember the details.

Make sure to check this example app here: https://github.com/strongloop/loopback-getting-started-intermediate . It's pretty much I started with at the time.
