### ISSUE TITLE
Rewrite Getting Started "Add a client app" section

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#751]
[Add a client app](http://docs.strongloop.com/display/LB/Add+a+client+app) currently used the Angular seed app, and is out of date.  We should probably change this to use the Yeoman Angular generator.  But the details will depend on the new intermediate tutorial planned.

NOTE: Moved from https://github.com/strongloop-internal/scrum-loopback/issues/21

**Comment by crandmck** [comment]
This is covered now by http://docs.strongloop.com/display/LB/Create+AngularJS+client in "Getting Started Part 2".

**Comment by jimmydale1977** [comment]
RANDY I DONT WANNA SOUND STUPID, BUT I DONT UNDERSTANMD ANY OF THIS, I JUST KNOW THAT IT WAS ON MY COMPUTER I SEARCHED DEEPERE AND IT CAME BACK TO LOOPBACK AND GITHUB, I KNOW KNOW HOW OR WHY IM TARGEDTED BUT I HAVE BEEN NOW FOR 5 YRS, I AMD WORKING ON XP NOW CAUSE ALL MY DEVICES WERE EFFECTED WHEN I PRINTED OUT THE DETAILS OF WAHT THIS WAS MY DEVICES CRASHED COMPLETELY LEAVING ME WITH NO OPERATING SYSTEM AND I CAN BARE USE THIS XP, I CAN EVEN DOWNLOAD CHROME ON THIS COMPUTER, IU DONT KNOW WHATS GOIGN ON BUT IT REALLY UPSETS ME THAT EVERYTIME I FIND SOMETHING I DIDNT PUT ON MY COMPUTER, ITS SEEMES TO CRASH EVERYTHING OF MINE, I HAVE ALOL NEW BNAND NEW DEVICES AND CANT USE ANY OF THEM, IF YOU COULD HELP ME UNDERSTAND, I WOULD APPREICIEATE THAT SO MUCH, I KNOW I SOUND STUPIDM, BUT I WAS AND AM PROTECTED IN LOTS OF WAYS, AND I JUST DONT KNOW WHY MY INFORMATION KEEPS GEETING STOLEN AND MY DATABASEM, WIPED OUT,THANK YOU FOR YOU CONCERNDS JDP 
. JUST TO FILL YOU IN WHAT I USE ARE THE FOLLOWING DEVICES AND PROGRAMS

-LENOVO 250GB PRO, WITH WINDOWS 8.1 SIGN IN MICROSTOFT, PROTECTED ONLY WITH WINDOWS DEFENDER, AND FIREWALL AS WELL AS NETWORK PROTECTION ENABLED, I EVEN HAVE SERVICES LIKE FTP, IPV6, PORT FORWARDING, ETC DISABLED,. BECAUSE PF THESE ATTACKS. IT IT HAS NOW RUINED A TOLAL OF 6 DEVICES, I HAVE A BRANK NEW PRINTER HP ENVY ALL IN ONE WIRELESS NETWORK, RPOTECTED AS WELL, BUT SOMETIMES THE IP ADDRESS CHANGES, I HAVE TO KEEP IT ONOLINE BECAUSE I PAY FOR INSTANT INK AND THEY SEND ME INK WHENEVER NEEDED AT A MONTHLY FEE. I HAVEE A BRAND NEW HP CHROMEBOOK THAT I WILL NOT EVEN SIGN ON AND I JUST GOT IT BOUT 4 WKS AGO. ITS THE HP CHROMEBOOK Q1000 SERIESS LATEST ONE. I HAVE A GAXALY SAMSUNG S11, AND A BRAND NEW SHARP AQUOOS PHONE AS WELL, I HAVE THROWN OUT 2 LAPTOPS AS WELL. AND IM NOW USING THIS XP UNUSABBLE REALLY JUST TO GET MY MAIL AND STUFF, I HAVE HAD TO DELETE 30GB OF FILES OFF MICROSOFF, AND I HAVE 115GB ON GOOGLE THAT I THINK ARE AFFECTED AS WELL SO I JUST
 DONT KNOW WHAT TO DO BUT JUST STAY OFF THE COMPUTER, AGAIN THANK YOU SO MUCH FOR TRYING TO TELL ME THESE THINGSL BUT I REALLY DO NOT UNDERSTAND ANY OF IF AND WHY IT IS GOING ON , AGAIN THANKS JIMMY PAYNE   PHONE: 6797718040 THATS THE ONLY ONE ILL USE OUT OF THE 4 PHONE NUMBERES I HAVE,. THANK YOU AGAION-------------------------------------
On Tue, 1/20/15, Rand McKinney <notifications@github.com> wrote:

 Subject: Re: [loopback] Rewrite Getting Started "Add a client app" section (#751)
 To: "strongloop/loopback" <loopback@noreply.github.com>
 Date: Tuesday, January 20, 2015, 6:08 PM
 
 Closed #751.
 
 —
 Reply to this email directly or view
 it on GitHub.
