### ISSUE TITLE
Add description in documentation for "refresh" parameter available for "belongsTo" and "hasOne" relations

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback#760]
Could you please describe the behavior of the "refresh" parameter and update swagger documentation with it. Missing it here: 
- https://github.com/strongloop/loopback/blob/2f1a1bcd7a54ba607acf6caa35042cee91e6a271/lib/model.js#L408
- https://github.com/strongloop/loopback/blob/2f1a1bcd7a54ba607acf6caa35042cee91e6a271/lib/model.js#L420

**Comment by bajtos** [comment]
IIRC, the `refresh` argument refreshes the cached data stored on the model instance at the source of the relation link. Since REST requests always create a new instance, this argument is irrelevant and we should remove it from remoting metadata.

@voitau would you like to submit that change yourself?

**Comment by rashmihunt** [comment]
@voitau would you be able to submit a patch based on @bajtos above comments?
