### ISSUE TITLE
Include with scope fields does not work for relations

### ISSUE THREAD

**Issue by Spark-star** [strongloop/loopback#773]
I have relation between model A and B , Bs : {A hasBany B}  and A: {B belongsTo A};
I defined scope in relation Bs, scope:{ includ: A}, I want the A when I get the route /as/:id/bs/:fk or route /as/:id/bs.
But it doesn't work ?
Is it something wrong in my code?

**Comment by Amir-61** [comment]
Hi @Spark-star,

Has your problem been solved by using lowercase `server` here:
'''
"scope": {
        "include": "server"
}
'''
 or still you experience the same issue? If so please share a repo using our [sandbox](https://github.com/sharkinsspatial/loopback-sandbox) and we can look into your code and see what is wrong; otherwise, please let us know and we close this ticket.

Thanks!

**Comment by Amir-61** [comment]
Hi @Spark-star,

I will be closing this ticket due to inactivity; please feel free to re-open it if you still have the same issue.

Thanks!
