### ISSUE TITLE
Add docs for "Using JWT for OAuth2"

### ISSUE THREAD

**Issue by lsdriscoll** [strongloop/loopback#789]
Please consider adding docs explaining how to configure JWT authentication with regards to applications and users, for the server and the client.

Ideally this would include an adaption of the API Gateway example, but using with the required client side code integrated into the client-side SDK.

**Comment by wilsonmar** [comment]
Last year I wrote up an explanation of Google's JWT OAuth2 implementation to go with code I wrote to explore Google's API and load test connections. I just jumped on the Lookback bandwagon, but would be happy to repurpose my write-up and the "beautiful" flowchart that I made to go with the text.

**Comment by raymondfeng** [comment]
@wilsonmar That would be fantastic. I look forward to your write-up.

**Comment by crandmck** [comment]
@wilsonmar That would be great.  In what format was your article written?  I can work with almost anything, but best for me would be Google Doc or just add a page to the LoopBack GitHub wiki: https://github.com/strongloop/loopback/wiki.  Then I can move and convert to Confluence on docs.strongloop.com.  Thanks!

**Comment by wilsonmar** [comment]
In my write-up I explain each step of the JWT process and what data goes
into it, all illustrated by a gradual-reveal graphic. But I'm embarrassed
that I wrote the thing in MS Word and the graphic is in PowerPoint.  I can
convert the text into wiki markup. What do you recommend that I use to
create the graphics? Most importantly, where can I find sample Node.js code
to make JWT OAuth2 calls (for Base64, signing, etc.)?

**Comment by crandmck** [comment]
@wilsonmar If you can convert to wiki format, that would be fine... Or you can just upload to Google Drive, and convert to Google Doc format--then I can take it from there (just make sure permissionss are set properly).  Or just email me the Word doc and I can convert it... Whichever you prefer.  

For the graphics in PowerPoint, you could just take screenshots of them (or save to .png or .jpg from PP if you can--I don't know PP very well) and then include your images into the Gdoc.  In the wiki, I think you need to commit the graphics files to the repo, so not sure that's the best way to go.   As a last resort, zip up the images and email to me: rand at strongloop dot com.  Thanks!

Re: your question
> where can I find sample Node.js code to make JWT OAuth2 calls (for Base64, signing, etc.)?
@raymondfeng may be able to answer that.

**Comment by wilsonmar** [comment]
Rand, I'll start by emailing you what I have, but only to show you my
starting point. Where do I find your email address?

I say starting point because the coding example I wrote refers to another
programming language. Nevertheless, I structured the coding so that someone
can just make a call and the rest of the coding is taken care of in the
library code. I would think we need to do the same for Node.js developers.

The example API is using Google's URL Shortener API. But I'm excited about
this because once someone figures out how to get into Google's API, the
same technique can be use to access many other (usually free) services that
Google offers. Google keeps adding new ones (and unfortunately also drops
them when it doesn't suit their fancy). Google's list of APIs is currently
at
https://developers.google.com/apis-explorer/#p/

@raymondfend, I searched around and found
https://github.com/strongloop/loopback-component-oauth2/blob/master/lib/oauth2-loopback.js

I my example I store API private keys in clear text files. Not good. So I'm
also investigating how API keys are managed within node, which is a whole
other "can of beans" that is different for each operating system node runs
on. I'm looking for a technical partner to help me on this endeavor. Is
there an enterprise grade secret key management system that node can use?
One is necessary for wide adoption of node within security paranoid
organizations (banks, health care, governments, etc.).

**Comment by crandmck** [comment]
My email is **rand at strongloop dot com**.

**Comment by Telemakhos** [comment]
Hi guys, any news on this? I think there's a lot of interest in a clear example of JWT with loopback. It would be great to have a detailed app/guide for reference and implementation.... cheers

**Comment by wilsonmar** [comment]
I've been working on it. Sorry for the delay in converting from the Word
file I had it in. I'm hoping for completion next week. Let me know if you'd
like to draft.

**Comment by jmls** [comment]
were you able to complete this ? I am also looking at using jwt with strongloop ;)

**Comment by sochka** [comment]
any success with this?

**Comment by dilshanraja** [comment]
Bump. Interested in seeing docs for this as well.

**Comment by GeoffreyEmery** [comment]
this is a serious long dated bump

**Comment by crandmck** [comment]
@wilsonmar or @raymondfeng Can someone address this?
@0candy perhaps you have some thoughts?

**Comment by 0candy** [comment]
@crandmck Did you get the draft from @wilsonmar? Maybe we can take a look and help with the updates.

**Comment by wilsonmar** [comment]
Hi. I'm sorry I didn't get back to this because I didn't hear back about
how to format the doc (GitHub markdown or what)?
If someone can point me to an example I can convert my detailed description
now in a Word file and PowerPoint file.

**Comment by wilsonmar** [comment]
Also, (more importantly) I need a developer of the module to answer some
questions because I don't think people here want a generic description of
JWT, but how Loopback makes use of it. Am I correct?

**Comment by 0candy** [comment]
@wilsonmar If you could upload your word file to google drive or email to @crandmck, we can get someone on the team to review it and see how we can add the usage with loopback. Thanks!

**Comment by crandmck** [comment]
Yes @wilsonmar virtually any format would be fine.
One easy way would be to create a markdown doc in [the wiki for this repo](https://github.com/strongloop/loopback/wiki).  That would make it easy to collaborate, and it should not require any special rights to edit the wiki...  

But really anything is fine: Create a Google Doc or email me anything.  Thanks!

**Comment by Sequoia** [comment]
@wilsonmar Please email what resources you have to @crandmck per email address above or to my email which you can find on my profile page. @crandmck please close this ticket when ready- there are no further action steps.

**Comment by crandmck** [comment]
@wilsonmar We're cleaning up old issues, so I'll close this since we haven't heard from you.  If you are still want to participate, please comment (or reopen).
