### ISSUE TITLE
Resolve open questions re roles

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#801]
Improve http://docs.strongloop.com/display/LB/Defining+and+using+roles with some more explanation:

- What is `context` and where does it come from?
  - ANSWER: It's is an object provided by loopback to give the user context into the request (ie. when the request comes in, they can access context.req or context.res, like you normally would with middleware)
- What is purpose of process.nextTick() ?
  - ANSWER: This is part of node and requires a whole explanation into the heart of node, (ie the event loop). basically this delays the `cb` call until the next `tick` of the event loop, so the machinery can process all events currently in the queue before processing your callback.
- what is `return reject()` and where does `reject()` come from?
   - ANSWER: `reject` is a function we define inline ie function reject() ... We basically say, if request is not a a request to api/projects (by checking the modelname), do not execute the rest of the script and reject the request (do nothing). Do this by calling "reject", which will return false during the next cycle of the event loop (returning false in the second param means the person is NOT a team member, ie is not in that role)
- The logic at the end that determines whether teamMember is in team based on Team.count() seems a bit convoluted. Explain, esp. how cb works in this specific case.
 - ANSWER: This example is provided verbatim by raymond but the idea is you have a team table and you do a query to count the "rows" because the requester can be on multiple teams, so any number you get greater than 0 is ok

**Comment by crandmck** [comment]
@bajtos Sorry, I was on vacation.... I think this still deserves some attention, but honestly I don't have the bandwidth.  Perhaps @sequoia can take it?

**Comment by Sequoia** [comment]
* [ ] Explain `context`: I'll look into this-- it *looks like* context is an instance of `AccessContext` as defined [here](https://github.com/strongloop/loopback/blob/6964914bab64496c789c434fec39d2914231ee23/lib/access-context.js#L10-L27), is that accurate? My certainty that it is is >90% so I'll go ahead & edit.
* [ ] `process.nextTick`: -- I don't see this in the document, was it removed? I don't *think* [zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony) is an issue here as none of the code paths throw & the return value is discarded (I assume, since it's a nodeback API).
* [x] `reject`:  simplified example, removing `reject` function.
* [ ] Further simplify/clarify bootscript example -- will do

**Comment by crandmck** [comment]
Thanks for your help @Sequoia....
> .. it looks like context is an instance of AccessContext as defined here, is that accurate? 

I believe so too, but perhaps @superkhau or another dev can confirm.

**Comment by Sequoia** [comment]
* Added note about `process.nextTick` with link to a blog post on it (I really don't know how to do a 1-sentence explanation of maintaining asynchrony-- if you can explain it more concisely edit away).
* Removed `reject` function for simplicity's sake
* littered boot script with comments to make it every easy to read thru. If this is too much, the alternative would be to provide a simpler example, IMO.

**Comment by crandmck** [comment]
Thanks @Sequoia, your changes look good.  I think this can be closed.  If there is any further work or open questions, feel free to reopen.
