### ISSUE TITLE
Write Getting Started Part II tutorial

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#808]
Take example app and basic instructions/notes from Simon and write finished "Getting Started Part II" tutorial.  Consider a better name/title for the series?

**Comment by crandmck** [comment]
@altsang This is ready for intial review.   

The work to create releases in the repo is not yet done.  I'd like at least one release, so the reader can easily get the entire client directory, _except_ for the `lb-services.js` file, which they should generate.

Do we want to have releases for each and every step along the way, so someone can "jump in" along the way--as we did for GS part 1?

I know I still need to add a few more AngularJS explanations and links in the final chapter, as wel discussed.   Specific suggestions welcome.

**Comment by altsang** [comment]
reviewed, I think releases for each step would be good so that someone who understands up to a certain point can jump ahead by fast forwarding

will take a more in-depth look at the Angular JS part to what should be linked out

please #923, we should release this as is and can work on ...

1) releases for each step
2) deploy step - #923

**Comment by chandadharap** [comment]
can we please close this then?
