### ISSUE TITLE
Further integration between oAuth 2.0 and LoopBack

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback#817]
1. Unify the access token model between oAuth 2.0 and User.login
2. Integrate scope with ACL

**Comment by gagan-bansal** [comment]
+1

**Comment by robotiko** [comment]
+1

**Comment by zetflo** [comment]
+1

**Comment by raymondfeng** [comment]
I did some basic testing. The oAuth 2.0 token based authentication is already working with ACLs if you enable the middleware on your resource/api server that serves the model endpoints.

**Comment by archana09** [comment]
Can you please direct me some code example how you are doing this?

**Comment by skyserpent** [comment]
+1

**Comment by XinV** [comment]
+1, some code examples and instruction walking through would be much helpful.

**Comment by Nebosky42** [comment]
+1

**Comment by asanchezdelc** [comment]
+1

**Comment by danielrvt** [comment]
+1

**Comment by luksch** [comment]
+1 this would be awesome! Thanks for all the effort that goes into this.

**Comment by mercuriete** [comment]
+1
I am working on an application that need throttling and autentication to get access to my api.
I need information because maybe i missunderstood the concept. If I create ACL and roles in the api server, the gateway doent know anything about this users and this roles.
the access_token is only to pass through the proxy and if you need an access_token to this end point its not the same.

By the way, i want to know if there are any chance to autenticate with oauth2 as an anonymous user, because in our use case makes sense to keep some state or session to a gest that doesnt have account yet.

I need to get working my application quickly so by the moment i am deleting all the gateway stuff and implement the autentication directly in the api server.

Thank you for your job because is a great framework to create apis really quick but some features are not yet ready to be in production.

**Comment by asanchezdelc** [comment]
Hey guys, I was able to get this integration working with some modifications here's an example:

[https://github.com/qbanguy/loopback-gateway2](https://github.com/qbanguy/loopback-gateway2)

**Comment by qbanguy** [comment]
Hey guys, I was able to get a working example with oAuth2, passport, and ACL. 

[https://github.com/qbanguy/loopback-gateway2](https://github.com/qbanguy/loopback-gateway2)

**Comment by Overdrivr** [comment]
> The oAuth 2.0 token based authentication is already working with ACLs if you enable the middleware on your resource/api server that serves the model endpoints

@raymondfeng Which middleware are you referring to ?

Does this mean that we can store OAuth tokens directly inside LB's AccessToken model, using node api equivalent of `POST /User/{id}/accessTokens` ?

**Comment by JonnyBGod** [comment]
Is this still in the pipeline or is it better to create our own solution?

**Comment by AlexDM0** [comment]
I've added an option for oauth2 and loopback to live side by side. If you're interested, it's all available:
https://github.com/crownstone/loopback-component-oauth2

**Comment by Yaty** [comment]
Any update ?

**Comment by Overdrivr** [comment]
The approach I would use is similar to what Gitlab does, use OAuth2 for first connection to acquire user email, then let the user generate a password. It's not exactly the full OAuth2 flow, but at least in the end you can create a regular User with Loopback, and benefit from ACL/Authentication/etc.

Eventually, if you need interaction with the OAuth provider, then you might be able to store credentials/token/whatever inside the Loopback User and pass those credentials to the OAuth provider when you need to.

I haven't completely tested this approach so I might be missing something here, but my guess is this should work.
