### ISSUE TITLE
Overriding validation

### ISSUE THREAD

**Issue by diasalvatore** [strongloop/loopback#879]
I have a class `MyUser` which extends built-in `User`.
How can I remove default validation (like the one on email and password)?

**Comment by slgoldberg** [comment]
Ah hah -- man, sometimes it's really hard piecing together what's what from a Google search given how active development is on this (though, that's a good thing of course).

Anyway, I think I figured out that in fact you do correctly support this dichotomy of uses in the current implementation of the built-in User model (as of 2016, anyway).  I see in the code, all I needed to do was add `"realmRequired": true` to the `options` object in my derived user model, e.g.:

```
{
  "name": "MyUser",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "realmRequired": true
  },
 ...
}
```

With `realmRequired: true`, email is not required to be unique. Excellent!

So that's pretty much just what I needed in my case (I am fine requiring `realm`, as I said above, it makes total sense that `realm`+`username` would replace `email` as the primary-ish key.

Thanks a lot  -- I'm good to go. Though as usual, maybe there's something I can do to help improve the docs, will look at it again later and update this if so with proposed improvement (or not :-) ).

   Steve

**Comment by pulkitsinghal** [comment]
> How can I remove default validation (like the one on email and password)?
In the sample below, I remove everything from the custom `MyModel` which extends `User`:
1. the validations on username and email are removed
2. the password field is removed
3. the username and email fields are removed
```
{
  "name": "MyModel",
  "base": "User",
  "properties": {
    "email": false,
    "username": false,
    "password": false
  }
}
...
module.exports = function(MyModel) {
  MyModel.disableRemoteMethod("login", true);
  MyModel.disableRemoteMethod("logout", true);
  MyModel.on('dataSourceAttached', function() {
    console.log('MyModel', 'on.dataSourceAttached()');
    delete MyModel.validations.email; //delete MyModel.app.models.User.validations.email;
    delete MyModel.validations.username; //delete MyModel.app.models.User.validations.username;
  });
};
```

**Comment by buzai** [comment]
In your built-in user model inside, a lot of places to use the mailbox this thing, so can not simply delete this thing. Delete will influence to reset the password, and even affect the secret key generation, I think we should provide an optional project, configuration into the phone number or e-mail address, user name is to make configuration options for unique personality, but need to choose a as a unique ID.
Of course, if you replace the mailbox with a phone number, a lot of places need to change, first of all, you may not need to change the token, but the certification section has to make a lot of changes.

**Comment by pulkitsinghal** [comment]
> In your built-in user model inside, a lot of places to use the mailbox this thing, so can not simply delete this thing. Delete will influence to reset the password, and even affect the secret key generation, I think we should provide an optional project, configuration into the phone number or e-mail address, user name is to make configuration options for unique personality, but need to choose a as a unique ID.
Of course, if you replace the mailbox with a phone number, a lot of places need to change, first of all, you may not need to change the token, but the certification section has to make a lot of changes.

In my example code in my previous comment, I am not changing the built-in `user` model, I'm changing `MyModel` which inherited from `user` model. So no harm done, I hope you agree @buzai? Unless I'm nuking a shared prototype unknowingly? Let me know.

**Comment by buzai** [comment]
@pulkitsinghal , I'm not saying you destroy something, I think if you do not use it's own mailbox, then how to generate the user's token it, then you have to write your own method of generating token, there is a lot of built-in methods you can not use the fact, I think if we do so, not as a direct write a model, rather than inherited user. I look at the code inside the user's login and also implements several methods to create a similar, but those methods and mailbox properties coupled together.
