### ISSUE TITLE
What does dynamic converters do? they only work if modelName is all lowercase

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback#906]
During `Model.setup()`, it registers a converter to `RemoteObjects` with a name which is usually capitalize (e.g. `User`).  See [L117](https://github.com/strongloop/loopback/blob/master/lib/model.js#L117)

But I also found that, `strong-remoting` looks up a converter by lowercase the `typeName` (e.g. `user`), hence it never find that converter. See [L120](https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L120)

So is this a bug or incomplete feature?

**Comment by jorrit** [comment]
I am having this problem too in the following situation:

I have a custom model with a date property. I have a remote method that accepts this custom model as an argument. When I change the comparison to case-insensitive, the right model converter is found and executed and my date property is converted from string to `Date`. When I don't have this change, the date property is interpreted as a string.

**Comment by jorrit** [comment]
What can I do to help here? I think this can be improved in either loopback or strong-remoting.

**Comment by raymondfeng** [comment]
@ritch What do you think?

**Comment by ritch** [comment]
So here is the issue: https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L169

Strong-remoting is trying to not be strict about specifying types... You can specify `date` or `Date` for example... LoopBack's type system on the other hand is more strict and requires that you specify the exact type.

We just need to pass the correctly cased version to the converted instead of the lower-cased one.

@jorrit do you want to submit a patch to strong-remoting? It should be fairly small and mostly a test that ensures case types match correctly.
