### ISSUE TITLE
using rethinkdb as storage backend?

### ISSUE THREAD

**Issue by sirvon** [strongloop/loopback#957]
Can you guys point me in the right direction towards getting rethinkdb to work in place of mysql or postgres?

Thanks you.
and thanks for your works.

**Comment by grantcarthew** [comment]
I would be interested in a connector for rethinkdb also.

**Comment by BerkeleyTrue** [comment]
Loopback is an opensource project and the main team is pretty busy these days. If someone would like to build one for rethinkdb, it is not too hard. You can use https://github.com/strongloop/loopback-connector to start! Anyone interested?

**Comment by AvivLander** [comment]
Why not use the existing https://github.com/fuwaneko/jugglingdb-rethink?

**Comment by BerkeleyTrue** [comment]
Is that compatible with Loopback? It does not mention it anywhere in the repo. It states it is a connector for jubgglingDB. What is your experience with it @AvivLander ?

**Comment by AvivLander** [comment]
It is compatible for version 1 of Loopback, but there is currently a bug with version 2. The issue is not really from the library though... On user login, the param userId is reaching the connector with a value as NaN. This causes the connector library to fail. There's an open bug for this here: https://github.com/strongloop/loopback/issues/1023

With version 1 of loopback it works wonderfully. It's a Jugglingdb connector. It has the same definition as the custom connector guide stated in the api documentation. There shouldn't be any reason for it not to be compatible.

**Comment by bajtos** [comment]
Hello, I am afraid there has not been a high enough demand for us to implement (and maintain) a connector for RethinkDB. I think the best option is to fork jugglingdb-rethink and rework it to satisfy LoopBack connector API, which can be done by anybody from the community.
