### ISSUE TITLE
ACL does not apply to related models

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#960]
Access is denied for related models even when the user is authenticated and has permissions on the primary model.

See https://github.com/strongloop/loopback-example-access-control/issues/41 and https://groups.google.com/forum/#!searchin/loopbackjs/access$20denied$20related$20model/loopbackjs/iCgMsTzuJ14/Efmdl33JcTQJ

**Comment by blainsmith** [comment]
I came across this issue to so I dug into the LoopBack code itself to find that by default all related model methods have a DENY ALL ACL set. You need to explicitly open them up.

http://docs.strongloop.com/display/public/LB/Restricting+access+to+related+models

The ACLs do not inherit from the target model's endpoint.

```
GET /user/{id}/books // default ACL is DENY all 
GET /books // default ACL is ALLOW $authenticated
```

This definitely tripped me up for a while and is not explained in the documentation and example app.

**Comment by richardpringle** [comment]
@superkhau, going through old issues... this can be closed right?

**Comment by superkhau** [comment]
@richardpringle Sure.

> This definitely tripped me up for a while and is not explained in the documentation and example app.

@crandmck ^ for docs, @loay ^ for example app

@blainsmith Closing this issue. Please open a new one if you are still having problems.

**Comment by blainsmith** [comment]
Thanks for following up. Closing this sounds good.

**Comment by crandmck** [comment]
I added a note to https://docs.strongloop.com/display/LB/Accessing+related+models.  I'll go ahead and close.

**Comment by proreact-mj** [comment]
Ehhm, Am I missing something or is "By default, all related model methods have a DENY ALL ACL set" explicitly wrong?

True, that for the example with the build-in user model, all relations are default DENY ALL, but that is only true for that model explicitly and (a few other build-in) any relations created from custom models are ALLOW ALL, unless a DENY ACL is set. Right?

**Comment by richardpringle** [comment]
@proreact-mj, a little confused with what you're asking. The best thing to do to understand is to just create a model and some ACLs and to just test it out. As far as relations go, the ACL should only affect the model that "has" the ACLs (the ACL array is populated in that model's JSON file). 

If ModelA *hasMany* ModelB and both models are "public" (set in the `model-config.json`), any ACLs attached to ModelA will affect that model only. ModelB can still be accessed through the api.

**Comment by proreact-mj** [comment]
Fair enough. I have ~200 relations in my app, and none of them have ALLOW ACL and they all work fine. 

My point is, that the general statement is in fact only true if the parent model has an explicit DENY ALL (i.e. not a default) 

The reason for the questions, was just in case there where some security setting that I haven't yet found that set implicit DENY on all relations

**Comment by richardpringle** [comment]
@proreact-mj 
>By default, all related model methods have a DENY ALL ACL set

Where did you see that line, in the docs? Can you point me to a link please?

**Comment by proreact-mj** [comment]
First line i a yellow warning box :)
[https://docs.strongloop.com/display/public/LB/Accessing+related+models](https://docs.strongloop.com/display/public/LB/Accessing+related+models )

**Comment by richardpringle** [comment]
@proreact-mj, you're right, that is a little misleading. The statement is really only relevant to the built-in User Model.

@crandmck, can you take a look at this when you get a chance?
I think it should be something like 
"By default, all related model methods will inherit DENY ALL ACL settings." 

You can word it anyway you would like, but as @proreact-mj pointed out, the way it is currently worded only holds true for models that already have the "DENY ALL" ACL set (on the parent model).

Make sense? That gets convoluted quite quickly...

**Comment by proreact-mj** [comment]
I would suggest to not use the word "inherit" at all. The ACL governing, is the ACL on the base model called and the ACL of the related model does not come into play at all. Inheritance would suggest that the ACL somehow propergates down to the related model, while the case is that ALL enpoints of the called model (which just happens to include some relation-defined endpoints) has been explicitly set to deny.

**Comment by richardpringle** [comment]
True, good call. @crandmck ^

**Comment by crandmck** [comment]
@richardpringle @proreact-mj Please suggest the wording you'd like to see, and I'll make the change.  Thanks.

**Comment by proreact-mj** [comment]
Suggestion (the yellow warning) to also cover the security risk in the issue:
Base statement (possible security risk)
> When accessing a related model, the active ACL is still the one for the model your are calling. So even if your model has DENY ALL, if ther model relating to it has no ACL, then all the relation endpoints will also be open

Example of security risk
>  eg GET /OpenModel/{id}/ACLSecuredModel will allow full access to secured model through the OpenModel's relations

Reversed base statement (risk of functionality missing / convoluted permission fails)
> Contrariwise if your model has a DENY ALL eg. the build-in user model which is has it pr default, but the related models have no ACL, they will still not be accessible through the user model

Original example (which only covers functionality risk)
> So, for example, even if the books model's default ACL is ALLOW $authenticated for GET /books, the route GET /user/{id}/books default will still be DENY ALL.

@crandmck 
You will also want to check (remove or rewrite) the warning box a bit further down the page.
I'm not affiliated with Strongloop, not a documentation writer and English is my second language, so please check, correct and rewrite as you see fit :)

**Comment by proreact-mj** [comment]
Might be worth pointing out (underlining) that the current wording can lead to security problems. If a developer assumes that related models have a default DENY all, thus failing to close down access to a secured model through a less secure model, potentially exposing the entire database through nested includes.

**Comment by crandmck** [comment]
Sorry it took me so long to fix this.  I changed the wording of the warning in https://docs.strongloop.com/display/LB/Accessing+related+models based on your suggestion @proreact-mj.    Does this cover it?

**Comment by proreact-mj** [comment]
First part looks good. But the is another warning box further down the page that is still contradictory.

Might be a good place to put the information about explicit opening (the Reversed base statement and original example). Also clearly stating in the example eg. "For example, the build-in User model always have a default deny all, so to access related models you need to ...."

**Comment by johncpang** [comment]
I'm looking for a way to secure a related model.  But I think I found a loopholes.

```
GET /pushIDs // ACL is deny for all, but everyone can create new records
GET /users/{id}/pushIDs // ACL is $owner can CRUD
```

In Explorer, it looks fine.  I cannot access other's pushIDs from the above APIs, even I know the `id` of pushIDs records.  However, I can get the pushIDs with this:

```
GET /users/{id}?filter={"include": "pushIDs"}
```

Is that a leak?

**Comment by proreact-mj** [comment]
As pr discussions in this thread and the subsequent documentation in [Accessing related models](http://loopback.io/doc/en/lb2/Accessing-related-models.html) this is by design. 

Specifically: 
_When accessing a related model, the active ACL is still the one for the model you are calling. So even if your model has DENY ALL permissions set, if the model relating to it has no ACL, then all the relation endpoints will be open. This can be a security risk because, for example, GET /OpenModel/{id}/ACLSecuredModel will allow full access to ACLSecuredModel through the OpenModel relations._

**Comment by johncpang** [comment]
Let me clarify more.  In following, I will use "members" to replace "users" (so we avoid the naming collision with system's `User` model).  `member` is extended from `User`.

member.json
```
{
  "name": "member",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "hidden": [],
  "properties": {},
  "validations": [],
  "relations": {
    "pushDevices": {
      "type": "hasMany",
      "model": "pushDevice",
      "foreignKey": ""
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": [
        "create",
        "findById"
      ]
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": [
        "__get__pushDevices",
        "__create__pushDevices",
        "__updateById__pushDevices",
        "__destroyById__pushDevices"
      ]
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

So the `members` has deny all ACL and then a read-only access.  The related endpoint `/members/{id}/pushDevices` has ACL for $owner only.  I had verified by:

When not log in, calling `GET /members/2/pushDevices` will returns 401.
When logged in as User#3, `GET /members/2/pushDevices` will returns 403.

This look perfectly okay.

Whether I am logged in as User#3 or logged out, calling
````
GET /members/2?filter={"include":"pushDevices"}
```

I got data of User#2 AND the push devices associated with User#2.  Push devices info is not accessible when I use the related endpoint.

So, I wonder if this is a security leak - if caller knows the name, he can avoid the related endpoints but act directly on the parent object and use "include"

**Comment by proreact-mj** [comment]
{
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }
takes priority over 
{
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }

Thus you allow everyone (even not logged-in users) to read everything in the user table. 
**This is pretty bad, but not a bug.** 

Reason why "include":"pushDevices" works and GET /members/2/pushDevices does not, is that "__get__pushDevices" is not included in push, thus not accessible and the relation to the pushDevices allows for include, thus the read on the model only can include the info. 
This can be prevented with options.disableInclude on the relation definition in model.json, but as pointed out above, you have bigger fish to fry.

**Comment by johncpang** [comment]
@proreact-mj I understood which ACL takes priority over which one.  And my example is pretty bad because it involve the user table (which is known to be contains sensitive data).  The reasons it allows read by everyone is due to project design: users (even not logged-in users) can read other user's information (such as name, avatar, number of posts etc).

Since it's bad / complicated / link with personal information, let's change it to a less complicated example.  Say, there is a book model with private reviews (read-only by book authors).  It's straight forward to secure `/books/{id}/private-reviews` via ACL.  But we can access the private reviews using  `/books/{id}?filters={"include":"private-reviews"}`.

I haven't seen anywhere mentioning `options.disableInclude` (maybe I missed it).  But since we are told that related model has, by default, DENY access.  We are explicitly open access to the related model.  I guess no one would aware that granting READ access to books model will also grant READ access to private-reviews here.

Most of the concerns are "unable to read related model via related model path" but seldom on the filter include.  So I guess many people have overlook the issue.

**Comment by proreact-mj** [comment]
> But since we are told that related model has, by default, DENY access.

This is not correct and if this is written somewhere(?), it should be changed. 
Relations are open, unless explicitly denied and the yellow box in [Accessing-related-models](http://loopback.io/doc/en/lb2/Accessing-related-models.html) warns about exactly this. 

`When accessing a related model, the active ACL is still the one for the model you are calling. So even if your model has DENY ALL permissions set, if the model relating to it has no ACL, then all the relation endpoints will be open. This can be a security risk because, for example, GET /OpenModel/{id}/ACLSecuredModel will allow full access to ACLSecuredModel through the OpenModel relations.
`
One could wish for implicit security handling, where includes has the same security context as the relation method, but that is not how it works today and I agree that it is something that is very easy (and very critical) to overlook. 

[options.disableInclude is mentioned here under the Relations section](https://loopback.io/doc/en/lb2/Model-definition-JSON-file.html)

**Comment by johncpang** [comment]
Thanks.  Now is clear.  Maybe the yellow box text should have mention `options.disableInclude` and other way to secure the `ACLSecuredModel`.

However, based on my previous test result, the yellow box isn't 100% right.

As you pointed out, I have grant READ permission to $everyone that leak my secureModel via include.  However, /members/{id}/secureModel returns 401/403.  That mean I didn't have security risk as said in the yellow box.  I'm a bit confused here - is that inherit from user.json (because my member is inherit from User)?

> The related endpoint /members/{id}/pushDevices has ACL for $owner only. I had verified by:
>
> When not log in, calling GET /members/2/pushDevices will returns 401.
> When logged in as User#3, GET /members/2/pushDevices will returns 403.

**Comment by proreact-mj** [comment]
Well. It isn't really that the box said you didn't have a problem, just that it didn't say that you had :) 
When build a secure Loopback application, is it critically important that one understands both relational endpoints and includes functionality and addresses the both security concerns. 

Do note that, when using include filters, I do believe that the ACL of the included model is validated, as that is in essence a new bootstrapped call to the related model, but I'm not 100% sure here.

If you need more information or advise on how to manage Loopback security, I would advice you create a post on StackOverflow or the Google Groups (StackOverflow usually yields better response).
